using CalamityMod.Walls;
using Microsoft.Xna.Framework;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Terraria.ID;
using Terraria.ModLoader;
using CalamityMod.Tiles.Astral;
using CalamityMod.Tiles.Ores;

namespace CalamityMod.Schematics.AutoGeneratedContent
{
    public class AstralBeaconSchematic
	{
		[GeneratedCode("ScreenCaptureToSchematic", "1.0.1")]
		public static ColorTileMap GetMap()
		{
			var tile1 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0);
			var tile2 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32);
			var tile3 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 18);
			var tile4 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 32, 0, 32).UseFrame(0, 36);
			var tile5 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 90);
			var tile6 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 32, 3, 32).UseFrame(0, 36).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 108);
			var tile7 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 144, 2, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 72);
			var tile8 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 22, 3, 32).UseFrame(36, 72).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 108);
			var tile9 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(144, 54);
			var tile10 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 18);
			var tile11 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(18, 18);
			var tile12 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 1, 3, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 108);
			var tile13 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 98, 2, 32).UseFrame(54, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 72);
			var tile14 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(144, 36);
			var tile15 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(0, 18);
			var tile16 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(0, 18);
			var tile17 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(0, 36);
			var tile18 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(18, 18);
			var tile19 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 87, 4, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 144);
			var tile20 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(18, 36);
			var tile21 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(18, 0);
			var tile22 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 28, 0, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 432, 0);
			var tile23 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(0, 36);
			var tile24 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile25 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(126, 36);
			var tile26 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(180, 36);
			var tile27 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 0, 0, 32).UseFrame(90, 0);
			var tile28 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 0, 0, 32).UseFrame(108, 54);
			var tile29 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 90, 3, 32).UseFrame(36, 36).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 108);
			var tile30 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 153, 2, 32).UseFrame(36, 54).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 324, 72);
			var tile31 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(144, 54);
			var tile32 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 140, 2, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 432, 72);
			var tile33 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 36);
			var tile34 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 36);
			var tile35 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 0, 0, 32);
			var tile36 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 16, 0, 32).UseFrame(90, 18);
			var tile37 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 54);
			var tile38 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(18, 0);
			var tile39 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(126, 36);
			var tile40 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(36, 18);
			var tile41 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 36);
			var tile42 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(18, 36);
			var tile43 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 1056);
			var tile44 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 36);
			var tile45 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 36);
			var tile46 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 8224);
			var tile47 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 1056);
			var tile48 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(36, 36);
			var tile49 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 8224);
			var tile50 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 54);
			var tile51 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 16416).UseFrame(0, 36);
			var tile52 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 4128).UseFrame(54, 0);
			var tile53 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 18);
			var tile54 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 18);
			var tile55 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(180, 54);
			var tile56 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 54);
			var tile57 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(144, 36);
			var tile58 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32);
			var tile59 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(162, 36);
			var tile60 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 54);
			var tile61 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 4128).UseFrame(36, 0);
			var tile62 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 18);
			var tile63 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(126, 54);
			var tile64 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32);
			var tile65 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 0);
			var tile66 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 18);
			var tile67 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(126, 54);
			var tile68 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32);
			var tile69 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 18);
			var tile70 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 36);
			var tile71 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 54);
			var tile72 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 12320).UseFrame(36, 36);
			var tile73 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 4128).UseFrame(36, 0);
			var tile74 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile75 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 18);
			var tile76 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 36);
			var tile77 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 54);
			var tile78 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 0);
			var tile79 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 18);
			var tile80 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 36);
			var tile81 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 54);
			var tile82 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 152, 0, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 0);
			var tile83 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 168, 3, 32).UseFrame(54, 36).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 108);
			var tile84 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 0);
			var tile85 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 18);
			var tile86 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 36);
			var tile87 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 54);
			var tile88 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 0);
			var tile89 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 18);
			var tile90 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 36);
			var tile91 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 54);
			var tile92 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 0);
			var tile93 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 8224);
			var tile94 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 12320).UseFrame(36, 36);
			var tile95 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 8224).UseFrame(54, 0);
			var tile96 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(54, 18);
			var tile97 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(180, 54);
			var tile98 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 12320).UseFrame(36, 36);
			var tile99 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 1056).UseFrame(36, 0);
			var tile100 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 133, 2, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 72);
			var tile101 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 69, 1, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 36);
			var tile102 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 132, 4, 32).UseFrame(18, 36).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 144);
			var tile103 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 92, 1, 32).UseFrame(36, 36).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 432, 36);
			var tile104 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 171, 3, 32).UseFrame(72, 36).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 108);
			var tile105 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 90, 3, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 108);
			var tile106 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 16, 0, 32).UseFrame(180, 36);
			var tile107 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 22, 3, 32).UseFrame(36, 36).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 108);
			var tile108 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseHeaders(0, 74, 3, 32).UseFrame(18, 54).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 108);
			var tile109 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 36);
			var tile110 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 32).UseFrame(36, 0);
			Dictionary<Color, TileDefinitionStructure> colorTileMap = new Dictionary<Color, TileDefinitionStructure>()
			{
				{ new Color(0, 0, 0), tile1 },
				{ new Color(69, 89, 217), tile2 },
				{ new Color(42, 157, 230), tile3 },
				{ new Color(26, 59, 82), tile4 },
				{ new Color(37, 51, 189), tile5 },
				{ new Color(201, 62, 244), tile6 },
				{ new Color(75, 7, 228), tile7 },
				{ new Color(88, 216, 67), tile8 },
				{ new Color(239, 83, 114), tile9 },
				{ new Color(224, 106, 75), tile10 },
				{ new Color(203, 232, 84), tile11 },
				{ new Color(158, 21, 124), tile12 },
				{ new Color(25, 39, 133), tile13 },
				{ new Color(113, 168, 156), tile14 },
				{ new Color(228, 222, 227), tile15 },
				{ new Color(184, 94, 97), tile16 },
				{ new Color(114, 102, 1), tile17 },
				{ new Color(118, 115, 249), tile18 },
				{ new Color(32, 85, 59), tile19 },
				{ new Color(61, 86, 5), tile20 },
				{ new Color(102, 74, 50), tile21 },
				{ new Color(154, 78, 82), tile22 },
				{ new Color(253, 134, 30), tile23 },
				{ new Color(64, 175, 22), tile24 },
				{ new Color(111, 218, 94), tile25 },
				{ new Color(71, 115, 249), tile26 },
				{ new Color(95, 54, 244), tile27 },
				{ new Color(17, 109, 4), tile28 },
				{ new Color(73, 85, 117), tile29 },
				{ new Color(90, 126, 192), tile30 },
				{ new Color(65, 220, 209), tile31 },
				{ new Color(127, 10, 93), tile32 },
				{ new Color(105, 74, 143), tile33 },
				{ new Color(145, 187, 216), tile34 },
				{ new Color(66, 50, 183), tile35 },
				{ new Color(234, 7, 153), tile36 },
				{ new Color(155, 217, 225), tile37 },
				{ new Color(66, 221, 32), tile38 },
				{ new Color(16, 85, 221), tile39 },
				{ new Color(46, 81, 249), tile40 },
				{ new Color(221, 162, 8), tile41 },
				{ new Color(94, 254, 210), tile42 },
				{ new Color(69, 239, 207), tile43 },
				{ new Color(0, 221, 40), tile44 },
				{ new Color(105, 206, 122), tile45 },
				{ new Color(28, 206, 59), tile46 },
				{ new Color(76, 94, 78), tile47 },
				{ new Color(220, 191, 165), tile48 },
				{ new Color(222, 255, 254), tile49 },
				{ new Color(176, 110, 181), tile50 },
				{ new Color(128, 59, 249), tile51 },
				{ new Color(150, 179, 24), tile52 },
				{ new Color(207, 228, 51), tile53 },
				{ new Color(228, 165, 23), tile54 },
				{ new Color(201, 154, 251), tile55 },
				{ new Color(184, 216, 14), tile56 },
				{ new Color(165, 243, 134), tile57 },
				{ new Color(161, 226, 242), tile58 },
				{ new Color(170, 0, 226), tile59 },
				{ new Color(99, 127, 255), tile60 },
				{ new Color(211, 148, 128), tile61 },
				{ new Color(25, 128, 162), tile62 },
				{ new Color(47, 210, 27), tile63 },
				{ new Color(98, 77, 233), tile64 },
				{ new Color(8, 104, 185), tile65 },
				{ new Color(55, 18, 37), tile66 },
				{ new Color(169, 37, 38), tile67 },
				{ new Color(240, 11, 122), tile68 },
				{ new Color(47, 223, 89), tile69 },
				{ new Color(6, 236, 179), tile70 },
				{ new Color(53, 108, 100), tile71 },
				{ new Color(52, 16, 16), tile72 },
				{ new Color(150, 176, 26), tile73 },
				{ new Color(89, 137, 6), tile74 },
				{ new Color(243, 67, 166), tile75 },
				{ new Color(156, 153, 121), tile76 },
				{ new Color(57, 115, 238), tile77 },
				{ new Color(189, 185, 90), tile78 },
				{ new Color(216, 227, 137), tile79 },
				{ new Color(5, 234, 160), tile80 },
				{ new Color(73, 41, 230), tile81 },
				{ new Color(103, 44, 224), tile82 },
				{ new Color(132, 212, 88), tile83 },
				{ new Color(168, 160, 98), tile84 },
				{ new Color(11, 80, 156), tile85 },
				{ new Color(32, 252, 200), tile86 },
				{ new Color(212, 146, 70), tile87 },
				{ new Color(223, 204, 120), tile88 },
				{ new Color(196, 120, 179), tile89 },
				{ new Color(10, 91, 44), tile90 },
				{ new Color(135, 144, 197), tile91 },
				{ new Color(121, 16, 95), tile92 },
				{ new Color(31, 139, 23), tile93 },
				{ new Color(198, 24, 196), tile94 },
				{ new Color(33, 145, 211), tile95 },
				{ new Color(139, 177, 105), tile96 },
				{ new Color(190, 183, 230), tile97 },
				{ new Color(193, 49, 88), tile98 },
				{ new Color(90, 105, 92), tile99 },
				{ new Color(109, 162, 179), tile100 },
				{ new Color(45, 122, 120), tile101 },
				{ new Color(43, 33, 15), tile102 },
				{ new Color(156, 146, 64), tile103 },
				{ new Color(60, 0, 112), tile104 },
				{ new Color(176, 13, 122), tile105 },
				{ new Color(129, 189, 59), tile106 },
				{ new Color(165, 57, 198), tile107 },
				{ new Color(74, 76, 164), tile108 },
				{ new Color(69, 198, 94), tile109 },
				{ new Color(109, 30, 166), tile110 },
			};
			return new ColorTileMap(colorTileMap);
		}
	}
}
