using CalamityMod.Walls;
using Microsoft.Xna.Framework;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Terraria.ID;
using Terraria.ModLoader;
using CalamityMod.Tiles.Astral;
using CalamityMod.Tiles.Ores;

namespace CalamityMod.Schematics.AutoGeneratedContent
{
    public class AstralBeaconSchematic
	{
		[GeneratedCode("ScreenCaptureToSchematic", "1.0.1")]
		public static ColorTileMap GetMap()
		{
			var tile1 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0);
			var tile2 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(0, 54).UseHeaders(0, 0, 0, 32);
			var tile3 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(36, 72).UseHeaders(0, 16, 0, 32);
			var tile4 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(54, 0).UseHeaders(0, 32, 0, 32);
			var tile5 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(54, 126).UseHeaders(0, 16, 0, 32);
			var tile6 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(0, 18).UseHeaders(0, 16, 0, 32);
			var tile7 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(0, 72).UseHeaders(0, 0, 0, 32);
			var tile8 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(72, 54).UseHeaders(0, 32, 0, 32);
			var tile9 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 108).UseFrame(54, 144).UseHeaders(0, 16, 3, 32);
			var tile10 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 0).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile11 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 0).UseFrame(54, 18).UseHeaders(0, 32, 0, 32);
			var tile12 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(0, 36).UseHeaders(0, 33, 1, 32);
			var tile13 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 0).UseFrame(0, 18).UseHeaders(0, 26, 0, 32);
			var tile14 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(0, 18).UseHeaders(0, 17, 1, 32);
			var tile15 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 0).UseHeaders(0, 10, 0, 32);
			var tile16 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseHeaders(0, 1, 1, 32);
			var tile17 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 0).UseFrame(0, 36).UseHeaders(0, 42, 0, 32);
			var tile18 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(0, 72).UseHeaders(0, 1, 1, 32);
			var tile19 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(0, 36).UseHeaders(0, 32, 0, 32);
			var tile20 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(54, 144).UseHeaders(0, 16, 0, 32);
			var tile21 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 0).UseFrame(36, 18).UseHeaders(0, 147, 0, 32);
			var tile22 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(54, 18).UseHeaders(0, 163, 1, 32);
			var tile23 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 36).UseFrame(18, 18).UseHeaders(0, 71, 1, 32);
			var tile24 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(36, 18).UseHeaders(0, 155, 2, 32);
			var tile25 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(18, 18).UseHeaders(0, 131, 1, 32);
			var tile26 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 72).UseFrame(18, 18).UseHeaders(0, 71, 2, 32);
			var tile27 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 36).UseFrame(18, 18).UseHeaders(0, 66, 1, 32);
			var tile28 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(36, 18).UseHeaders(0, 147, 1, 32);
			var tile29 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 36).UseFrame(36, 18).UseHeaders(0, 82, 1, 32);
			var tile30 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 72).UseFrame(36, 18).UseHeaders(0, 87, 2, 32);
			var tile31 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 36).UseFrame(54, 18).UseHeaders(0, 98, 1, 32);
			var tile32 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(54, 36).UseHeaders(0, 163, 1, 32);
			var tile33 = new TileDefinitionStructure(TileID.Trees).UseFrame(66, 0).UseHeaders(0, 0, 0, 32);
			var tile34 = new TileDefinitionStructure(TileID.Trees).UseFrame(44, 242).UseHeaders(0, 0, 0, 32);
			var tile35 = new TileDefinitionStructure(TileID.Trees).UseFrame(44, 132).UseHeaders(0, 0, 0, 32);
			var tile36 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile37 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 108).UseFrame(18, 18).UseHeaders(0, 0, 3, 32);
			var tile38 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 36).UseFrame(18, 18).UseHeaders(0, 64, 1, 32);
			var tile39 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(36, 18).UseHeaders(0, 17, 1, 32);
			var tile40 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 0).UseFrame(18, 18).UseHeaders(0, 10, 0, 32);
			var tile41 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(36, 18).UseHeaders(0, 152, 1, 32);
			var tile42 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(54, 18).UseHeaders(0, 171, 2, 32);
			var tile43 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(54, 18).UseHeaders(0, 168, 1, 32);
			var tile44 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(18, 18).UseHeaders(0, 136, 1, 32);
			var tile45 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(18, 18).UseHeaders(0, 139, 2, 32);
			var tile46 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(54, 36).UseHeaders(0, 171, 2, 32);
			var tile47 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 198).UseHeaders(0, 0, 0, 32);
			var tile48 = new TileDefinitionStructure(TileID.Trees).UseFrame(88, 0).UseHeaders(0, 0, 0, 32);
			var tile49 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 0).UseHeaders(0, 0, 0, 32);
			var tile50 = new TileDefinitionStructure(TileID.Trees).UseFrame(0, 22).UseHeaders(0, 0, 0, 32);
			var tile51 = new TileDefinitionStructure(TileID.Trees).UseFrame(44, 110).UseHeaders(0, 0, 0, 32);
			var tile52 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 88).UseHeaders(0, 0, 0, 32);
			var tile53 = new TileDefinitionStructure(TileID.Trees).UseFrame(110, 66).UseHeaders(0, 0, 0, 32);
			var tile54 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 66).UseHeaders(0, 0, 0, 32);
			var tile55 = new TileDefinitionStructure(TileID.Trees).UseFrame(0, 44).UseHeaders(0, 0, 0, 32);
			var tile56 = new TileDefinitionStructure(TileID.Trees).UseHeaders(0, 0, 0, 32);
			var tile57 = new TileDefinitionStructure(TileID.Trees).UseFrame(66, 132).UseHeaders(0, 0, 0, 32);
			var tile58 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 0).UseFrame(54, 18).UseHeaders(0, 33, 0, 32);
			var tile59 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 72).UseFrame(18, 18).UseHeaders(0, 136, 2, 32);
			var tile60 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 72).UseFrame(36, 18).UseHeaders(0, 152, 2, 32);
			var tile61 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(18, 18).UseHeaders(0, 1, 1, 32);
			var tile62 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 0).UseFrame(54, 18).UseHeaders(0, 42, 0, 32);
			var tile63 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(54, 18).UseHeaders(0, 33, 1, 32);
			var tile64 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 0).UseFrame(36, 18).UseHeaders(0, 26, 0, 32);
			var tile65 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 72).UseFrame(54, 18).UseHeaders(0, 103, 2, 32);
			var tile66 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(36, 36).UseHeaders(0, 147, 1, 32);
			var tile67 = new TileDefinitionStructure(TileID.Trees).UseFrame(66, 220).UseHeaders(0, 0, 0, 32);
			var tile68 = new TileDefinitionStructure(ModContent.TileType<AstralShortPlants>()).UseFrame(126, 0).UseHeaders(0, 0, 0, 32);
			var tile69 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 0).UseFrame(54, 18).UseHeaders(0, 163, 0, 32);
			var tile70 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 36).UseFrame(36, 18).UseHeaders(0, 87, 1, 32);
			var tile71 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 0).UseFrame(18, 18).UseHeaders(0, 11, 0, 32);
			var tile72 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 36).UseFrame(18, 18).UseHeaders(0, 75, 1, 32);
			var tile73 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 36).UseFrame(54, 18).UseHeaders(0, 38, 1, 32);
			var tile74 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(36, 0).UseHeaders(0, 16, 0, 32);
			var tile75 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 0).UseFrame(36, 18).UseHeaders(0, 82, 0, 32);
			var tile76 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 72).UseFrame(36, 18).UseHeaders(0, 154, 2, 32);
			var tile77 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 36).UseFrame(18, 18).UseHeaders(0, 74, 1, 32);
			var tile78 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 36).UseFrame(54, 18).UseHeaders(0, 106, 1, 32);
			var tile79 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(18, 36).UseHeaders(0, 136, 1, 32);
			var tile80 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 0).UseFrame(18, 18).UseHeaders(0, 66, 0, 32);
			var tile81 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 72).UseFrame(18, 18).UseHeaders(0, 6, 2, 32);
			var tile82 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 72).UseFrame(36, 18).UseHeaders(0, 144, 2, 32);
			var tile83 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 0).UseFrame(54, 36).UseHeaders(0, 42, 0, 32);
			var tile84 = new TileDefinitionStructure(TileID.Trees).UseFrame(66, 22).UseHeaders(0, 0, 0, 32);
			var tile85 = new TileDefinitionStructure(TileID.Trees).UseFrame(44, 198).UseHeaders(0, 0, 0, 32);
			var tile86 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 36).UseFrame(18, 18).UseHeaders(0, 6, 1, 32);
			var tile87 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 36).UseFrame(36, 18).UseHeaders(0, 91, 1, 32);
			var tile88 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 72).UseFrame(36, 18).UseHeaders(0, 148, 2, 32);
			var tile89 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 36).UseFrame(54, 18).UseHeaders(0, 100, 1, 32);
			var tile90 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 36).UseFrame(36, 18).UseHeaders(0, 84, 1, 32);
			var tile91 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 72).UseFrame(18, 18).UseHeaders(0, 132, 2, 32);
			var tile92 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 72).UseFrame(54, 18).UseHeaders(0, 160, 2, 32);
			var tile93 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 144).UseFrame(54, 18).UseHeaders(0, 164, 4, 32);
			var tile94 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 36).UseFrame(54, 36).UseHeaders(0, 98, 1, 32);
			var tile95 = new TileDefinitionStructure(TileID.Trees).UseFrame(0, 110).UseHeaders(0, 0, 0, 32);
			var tile96 = new TileDefinitionStructure(TileID.Trees).UseFrame(66, 66).UseHeaders(0, 0, 0, 32);
			var tile97 = new TileDefinitionStructure(TileID.Trees).UseFrame(0, 66).UseHeaders(0, 0, 0, 32);
			var tile98 = new TileDefinitionStructure(TileID.Trees).UseFrame(0, 132).UseHeaders(0, 0, 0, 32);
			var tile99 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(18, 18).UseHeaders(0, 131, 1, 32);
			var tile100 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 144).UseFrame(54, 18).UseHeaders(0, 99, 4, 32);
			var tile101 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(18, 18).UseHeaders(0, 32, 0, 32);
			var tile102 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(18, 18).UseHeaders(0, 16, 0, 32);
			var tile103 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(162, 126).UseHeaders(0, 0, 0, 32);
			var tile104 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(36, 180).UseHeaders(0, 32, 0, 32);
			var tile105 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 0).UseFrame(54, 18).UseHeaders(0, 98, 0, 32);
			var tile106 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 36).UseFrame(18, 18).UseHeaders(0, 68, 1, 32);
			var tile107 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 0).UseFrame(18, 18).UseHeaders(0, 4, 0, 32);
			var tile108 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(36, 36).UseHeaders(0, 152, 1, 32);
			var tile109 = new TileDefinitionStructure(TileID.Trees).UseFrame(66, 242).UseHeaders(0, 0, 0, 32);
			var tile110 = new TileDefinitionStructure(TileID.Trees).UseFrame(66, 198).UseHeaders(0, 0, 0, 32);
			var tile111 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 132).UseHeaders(0, 0, 0, 32);
			var tile112 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 144).UseFrame(18, 18).UseHeaders(0, 133, 4, 32);
			var tile113 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(144, 54).UseHeaders(0, 32, 0, 32);
			var tile114 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile115 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 108).UseFrame(36, 18).UseHeaders(0, 83, 3, 32);
			var tile116 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 72).UseFrame(18, 18).UseHeaders(0, 1, 2, 32);
			var tile117 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 324, 72).UseFrame(54, 18).UseHeaders(0, 169, 2, 32);
			var tile118 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 0).UseFrame(18, 36).UseHeaders(0, 10, 0, 32);
			var tile119 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 72).UseFrame(54, 18).UseHeaders(0, 163, 2, 32);
			var tile120 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 144).UseFrame(18, 18).UseHeaders(0, 71, 4, 32);
			var tile121 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 108).UseFrame(54, 18).UseHeaders(0, 165, 3, 32);
			var tile122 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 72).UseFrame(36, 18).UseHeaders(0, 149, 2, 32);
			var tile123 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 144).UseFrame(54, 18).UseHeaders(0, 32, 4, 32);
			var tile124 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 36).UseFrame(18, 36).UseHeaders(0, 66, 1, 32);
			var tile125 = new TileDefinitionStructure(TileID.Trees).UseFrame(44, 220).UseHeaders(0, 0, 0, 32);
			var tile126 = new TileDefinitionStructure(TileID.Trees).UseFrame(44, 154).UseHeaders(0, 0, 0, 32);
			var tile127 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 72).UseFrame(18, 18).UseHeaders(0, 66, 2, 32);
			var tile128 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 432, 0).UseFrame(18, 18).UseHeaders(0, 12, 0, 32);
			var tile129 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 108).UseFrame(54, 18).UseHeaders(0, 99, 3, 32);
			var tile130 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 108).UseFrame(36, 18).UseHeaders(0, 87, 3, 32);
			var tile131 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(54, 36).UseHeaders(0, 168, 1, 32);
			var tile132 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 242).UseHeaders(0, 0, 0, 32);
			var tile133 = new TileDefinitionStructure(TileID.Trees).UseFrame(44, 88).UseHeaders(0, 0, 0, 32);
			var tile134 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 44).UseHeaders(0, 0, 0, 32);
			var tile135 = new TileDefinitionStructure(TileID.Trees).UseFrame(88, 132).UseHeaders(0, 0, 0, 32);
			var tile136 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 144).UseFrame(54, 18).UseHeaders(0, 165, 4, 32);
			var tile137 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(180, 144).UseHeaders(0, 16, 0, 32);
			var tile138 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(198, 180).UseHeaders(0, 32, 0, 32);
			var tile139 = new TileDefinitionStructure(TileID.Trees).UseFrame(88, 110).UseHeaders(0, 0, 0, 32);
			var tile140 = new TileDefinitionStructure(TileID.Trees).UseFrame(88, 66).UseHeaders(0, 0, 0, 32);
			var tile141 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 154).UseHeaders(0, 0, 0, 32);
			var tile142 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 144).UseFrame(54, 18).UseHeaders(0, 103, 4, 32);
			var tile143 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 0).UseFrame(36, 18).UseHeaders(0, 152, 0, 32);
			var tile144 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 0).UseFrame(36, 18).UseHeaders(0, 16, 0, 32);
			var tile145 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 144).UseFrame(18, 18).UseHeaders(0, 0, 4, 32);
			var tile146 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(54, 36).UseHeaders(0, 33, 1, 32);
			var tile147 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 144).UseFrame(36, 18).UseHeaders(0, 87, 4, 32);
			var tile148 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 108).UseFrame(36, 18).UseHeaders(0, 149, 3, 32);
			var tile149 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 0).UseFrame(36, 18).UseHeaders(0, 20, 0, 32);
			var tile150 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(18, 36).UseHeaders(0, 131, 1, 32);
			var tile151 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 432, 36).UseFrame(36, 18).UseHeaders(0, 92, 1, 32);
			var tile152 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 108).UseFrame(198, 18).UseHeaders(0, 83, 3, 32);
			var tile153 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 36).UseFrame(198, 18).UseHeaders(0, 84, 1, 32);
			var tile154 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(36, 36).UseHeaders(0, 155, 2, 32);
			var tile155 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(144, 72).UseHeaders(0, 32, 0, 32);
			var tile156 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(18, 0).UseHeaders(0, 16, 0, 32);
			var tile157 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(0, 162).UseHeaders(0, 32, 0, 32);
			var tile158 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(180, 126).UseHeaders(0, 0, 0, 32);
			var tile159 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(180, 162).UseHeaders(0, 32, 0, 32);
			var tile160 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(198, 162).UseHeaders(0, 16, 0, 32);
			var tile161 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 22).UseHeaders(0, 0, 0, 32);
			var tile162 = new TileDefinitionStructure(TileID.Trees).UseFrame(22, 110).UseHeaders(0, 0, 0, 32);
			var tile163 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(108, 72).UseHeaders(0, 0, 0, 32);
			var tile164 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 108).UseFrame(18, 18).UseHeaders(0, 132, 3, 32);
			var tile165 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 36).UseFrame(36, 18).UseHeaders(0, 80, 1, 32);
			var tile166 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 108).UseFrame(216, 18).UseHeaders(0, 155, 3, 32);
			var tile167 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(18, 0).UseHeaders(0, 32, 0, 32);
			var tile168 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 108).UseFrame(18, 18).UseHeaders(0, 66, 3, 32);
			var tile169 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 32, 0, 1056);
			var tile170 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(0, 18).UseHeaders(0, 32, 0, 32);
			var tile171 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 0).UseFrame(18, 18).UseHeaders(0, 1, 0, 32);
			var tile172 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(18, 36).UseHeaders(0, 1, 1, 32);
			var tile173 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseSlope(2).UseHeaders(0, 0, 0, 8224);
			var tile174 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(18, 36).UseHeaders(0, 139, 2, 32);
			var tile175 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseSlope(2).UseHeaders(0, 32, 0, 8224);
			var tile176 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(0, 18).UseHeaders(0, 16, 0, 32);
			var tile177 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(144, 54).UseHeaders(0, 0, 0, 32);
			var tile178 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 0).UseFrame(36, 18).UseHeaders(0, 27, 0, 32);
			var tile179 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 36).UseFrame(36, 18).UseHeaders(0, 82, 1, 32);
			var tile180 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 36).UseFrame(54, 18).UseHeaders(0, 103, 1, 32);
			var tile181 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 36).UseFrame(36, 36).UseHeaders(0, 17, 1, 32);
			var tile182 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(0, 18).UseHeaders(0, 0, 0, 32);
			var tile183 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(0, 36).UseSlope(4).UseHeaders(0, 32, 0, 16416);
			var tile184 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(144, 54).UseHeaders(0, 16, 0, 32);
			var tile185 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 108).UseFrame(54, 18).UseHeaders(0, 98, 3, 32);
			var tile186 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 0).UseFrame(54, 18).UseHeaders(0, 36, 0, 32);
			var tile187 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 72).UseFrame(198, 36).UseHeaders(0, 164, 2, 32);
			var tile188 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(54, 0).UseSlope(1).UseHeaders(0, 0, 0, 4128);
			var tile189 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(54, 18).UseHeaders(0, 0, 0, 32);
			var tile190 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(180, 54).UseHeaders(0, 0, 0, 32);
			var tile191 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(126, 54).UseHeaders(0, 16, 0, 32);
			var tile192 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(144, 36).UseHeaders(0, 32, 0, 32);
			var tile193 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(0, 36).UseHeaders(0, 32, 0, 32);
			var tile194 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseHeaders(0, 0, 0, 32);
			var tile195 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 144).UseFrame(18, 18).UseHeaders(0, 1, 4, 32);
			var tile196 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(198, 144).UseHeaders(0, 0, 0, 32);
			var tile197 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 0).UseSlope(1).UseHeaders(0, 0, 0, 4128);
			var tile198 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 18).UseHeaders(0, 16, 0, 32);
			var tile199 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(126, 54).UseHeaders(0, 32, 0, 32);
			var tile200 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(18, 36).UseHeaders(0, 32, 0, 32);
			var tile201 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 108).UseFrame(36, 18).UseHeaders(0, 82, 3, 32);
			var tile202 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 0).UseHeaders(0, 0, 0, 32);
			var tile203 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(144, 36).UseHeaders(0, 0, 0, 32);
			var tile204 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(126, 36).UseHeaders(0, 32, 0, 32);
			var tile205 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 18).UseHeaders(0, 32, 0, 32);
			var tile206 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 18).UseHeaders(0, 0, 0, 32);
			var tile207 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 0).UseFrame(36, 18).UseHeaders(0, 17, 0, 32);
			var tile208 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseHeaders(0, 0, 0, 32);
			var tile209 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(0, 18).UseHeaders(0, 0, 0, 32);
			var tile210 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(0, 36).UseHeaders(0, 0, 0, 32);
			var tile211 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(0, 54).UseHeaders(0, 0, 0, 32);
			var tile212 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 36).UseSlope(3).UseHeaders(0, 16, 0, 12320);
			var tile213 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 0).UseSlope(1).UseHeaders(0, 32, 0, 4128);
			var tile214 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(126, 54).UseHeaders(0, 0, 0, 32);
			var tile215 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 72).UseFrame(18, 18).UseHeaders(0, 128, 2, 32);
			var tile216 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 72).UseFrame(54, 18).UseHeaders(0, 168, 2, 32);
			var tile217 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile218 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile219 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(18, 36).UseHeaders(0, 0, 0, 32);
			var tile220 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(18, 54).UseHeaders(0, 0, 0, 32);
			var tile221 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile222 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(18, 36).UseHeaders(0, 0, 0, 32);
			var tile223 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 108).UseFrame(36, 18).UseHeaders(0, 16, 3, 32);
			var tile224 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 0).UseFrame(54, 18).UseHeaders(0, 43, 0, 32);
			var tile225 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(36, 0).UseHeaders(0, 0, 0, 32);
			var tile226 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(36, 18).UseHeaders(0, 0, 0, 32);
			var tile227 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(36, 36).UseHeaders(0, 0, 0, 32);
			var tile228 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(36, 54).UseHeaders(0, 0, 0, 32);
			var tile229 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 0).UseFrame(54, 18).UseHeaders(0, 168, 0, 32);
			var tile230 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 72).UseFrame(54, 18).UseHeaders(0, 165, 2, 32);
			var tile231 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 72).UseFrame(18, 18).UseHeaders(0, 138, 2, 32);
			var tile232 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(54, 0).UseHeaders(0, 0, 0, 32);
			var tile233 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(54, 18).UseHeaders(0, 0, 0, 32);
			var tile234 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(54, 36).UseHeaders(0, 0, 0, 32);
			var tile235 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(54, 54).UseHeaders(0, 0, 0, 32);
			var tile236 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 72).UseFrame(36, 18).UseHeaders(0, 22, 2, 32);
			var tile237 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(72, 0).UseHeaders(0, 0, 0, 32);
			var tile238 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(72, 18).UseHeaders(0, 0, 0, 32);
			var tile239 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(72, 36).UseHeaders(0, 0, 0, 32);
			var tile240 = new TileDefinitionStructure(ModContent.TileType<AstralBeacon>()).UseFrame(72, 54).UseHeaders(0, 0, 0, 32);
			var tile241 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(0, 36).UseSlope(4).UseHeaders(0, 16, 0, 16416);
			var tile242 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(126, 36).UseHeaders(0, 0, 0, 32);
			var tile243 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(144, 36).UseHeaders(0, 16, 0, 32);
			var tile244 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 36).UseSlope(3).UseHeaders(0, 32, 0, 12320);
			var tile245 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 0).UseSlope(1).UseHeaders(0, 16, 0, 4128);
			var tile246 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 36).UseFrame(54, 18).UseHeaders(0, 96, 1, 32);
			var tile247 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseSlope(2).UseHeaders(0, 16, 0, 8224);
			var tile248 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 0).UseHeaders(0, 16, 0, 32);
			var tile249 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 36).UseFrame(54, 18).UseHeaders(0, 107, 1, 32);
			var tile250 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(54, 0).UseSlope(2).UseHeaders(0, 32, 0, 8224);
			var tile251 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(180, 54).UseHeaders(0, 32, 0, 32);
			var tile252 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 0).UseHeaders(0, 16, 0, 1056);
			var tile253 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 252, 0).UseFrame(54, 18).UseHeaders(0, 103, 0, 32);
			var tile254 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 72).UseFrame(54, 18).UseHeaders(0, 170, 2, 32);
			var tile255 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 108).UseFrame(18, 18).UseHeaders(0, 67, 3, 32);
			var tile256 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 72).UseFrame(18, 306).UseHeaders(0, 164, 2, 32);
			var tile257 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 72).UseFrame(54, 18).UseHeaders(0, 164, 2, 32);
			var tile258 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 108).UseFrame(36, 18).UseHeaders(0, 155, 3, 32);
			var tile259 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 108).UseFrame(18, 18).UseHeaders(0, 139, 3, 32);
			var tile260 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(252, 36).UseHeaders(0, 16, 0, 32);
			var tile261 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 36).UseFrame(36, 18).UseHeaders(0, 22, 1, 32);
			var tile262 = new TileDefinitionStructure(ModContent.TileType<AstralMonolith>()).UseFrame(36, 54).UseHeaders(0, 32, 0, 32);
			var tile263 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(162, 36).UseHeaders(0, 32, 0, 32);
			var tile264 = new TileDefinitionStructure(ModContent.TileType<AstralShortPlants>()).UseFrame(90, 0).UseHeaders(0, 0, 0, 32);
			var tile265 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(126, 72).UseHeaders(0, 16, 0, 32);
			var tile266 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 0).UseFrame(36, 18).UseHeaders(0, 22, 0, 32);
			var tile267 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 0).UseFrame(18, 18).UseHeaders(0, 5, 0, 32);
			var tile268 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 216, 72).UseFrame(54, 18).UseHeaders(0, 38, 2, 32);
			var tile269 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 0).UseFrame(18, 270).UseHeaders(0, 4, 0, 32);
			var tile270 = new TileDefinitionStructure(TileID.Trees).UseFrame(66, 44).UseHeaders(0, 0, 0, 32);
			var tile271 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 324, 0).UseFrame(18, 18).UseHeaders(0, 9, 0, 32);
			var tile272 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 108).UseFrame(36, 18).UseHeaders(0, 17, 3, 32);
			var tile273 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 144).UseFrame(54, 18).UseHeaders(0, 98, 4, 32);
			var tile274 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 144, 144).UseFrame(18, 18).UseHeaders(0, 132, 4, 32);
			var tile275 = new TileDefinitionStructure(ModContent.TileType<AstralShortPlants>()).UseHeaders(0, 0, 0, 32);
			var tile276 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 180, 108).UseFrame(18, 18).UseHeaders(0, 133, 3, 32);
			var tile277 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 0).UseFrame(18, 18).UseHeaders(0, 131, 0, 32);
			var tile278 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 36, 72).UseFrame(54, 18).UseHeaders(0, 33, 2, 32);
			var tile279 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(54, 54).UseSlope(1).UseHeaders(0, 16, 0, 4128);
			var tile280 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(36, 108).UseHeaders(0, 0, 0, 32);
			var tile281 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 0, 108).UseFrame(54, 18).UseHeaders(0, 32, 3, 32);
			var tile282 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 72).UseFrame(54, 18).UseHeaders(0, 98, 2, 32);
			var tile283 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 108).UseFrame(36, 18).UseHeaders(0, 90, 3, 32);
			var tile284 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(144, 126).UseHeaders(0, 0, 0, 32);
			var tile285 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(54, 18).UseHeaders(0, 32, 0, 32);
			var tile286 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 144).UseFrame(36, 18).UseHeaders(0, 82, 4, 32);
			var tile287 = new TileDefinitionStructure(ModContent.TileType<AstralOre>()).UseFrame(144, 144).UseHeaders(0, 16, 0, 32);
			var tile288 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(108, 198).UseHeaders(0, 0, 0, 32);
			var tile289 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(90, 54).UseHeaders(0, 32, 0, 1056);
			var tile290 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(36, 180).UseHeaders(0, 32, 0, 32);
			var tile291 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 360, 36).UseFrame(36, 18).UseHeaders(0, 90, 1, 32);
			var tile292 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 72, 36).UseFrame(144, 198).UseHeaders(0, 98, 1, 32);
			var tile293 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(54, 54).UseHeaders(0, 16, 0, 1056);
			var tile294 = new TileDefinitionStructure(ModContent.TileType<AstralGrass>()).UseFrame(72, 0).UseHeaders(0, 0, 0, 32);
			var tile295 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(72, 36).UseHeaders(0, 163, 1, 32);
			var tile296 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(72, 0).UseHeaders(0, 136, 1, 32);
			var tile297 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(72, 18).UseHeaders(0, 155, 2, 32);
			var tile298 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(72, 18).UseHeaders(0, 152, 1, 32);
			var tile299 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(72, 36).UseHeaders(0, 171, 2, 32);
			var tile300 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(72, 0).UseHeaders(0, 131, 1, 32);
			var tile301 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(72, 0).UseHeaders(0, 139, 2, 32);
			var tile302 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 108, 36).UseFrame(72, 18).UseHeaders(0, 147, 1, 32);
			var tile303 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 288, 36).UseFrame(72, 36).UseHeaders(0, 168, 1, 32);
			var tile304 = new TileDefinitionStructure(ModContent.TileType<AstralDirt>()).UseWall((ushort)ModContent.WallType<AstralDirtWall>(), 396, 72).UseFrame(18, 72).UseHeaders(0, 139, 2, 32);
			Dictionary<Color, TileDefinitionStructure> colorTileMap = new Dictionary<Color, TileDefinitionStructure>()
			{
				{ new Color(255, 255, 255), tile1},
				{ new Color(22, 190, 82), tile2},
				{ new Color(77, 171, 121), tile3},
				{ new Color(227, 189, 85), tile4},
				{ new Color(113, 89, 16), tile5},
				{ new Color(107, 51, 16), tile6},
				{ new Color(18, 113, 232), tile7},
				{ new Color(72, 174, 103), tile8},
				{ new Color(67, 153, 27), tile9},
				{ new Color(169, 151, 91), tile10},
				{ new Color(114, 25, 160), tile11},
				{ new Color(212, 85, 23), tile12},
				{ new Color(22, 119, 41), tile13},
				{ new Color(71, 156, 64), tile14},
				{ new Color(55, 15, 126), tile15},
				{ new Color(27, 142, 189), tile16},
				{ new Color(47, 178, 214), tile17},
				{ new Color(58, 117, 140), tile18},
				{ new Color(163, 167, 133), tile19},
				{ new Color(149, 211, 36), tile20},
				{ new Color(55, 164, 19), tile21},
				{ new Color(29, 112, 163), tile22},
				{ new Color(181, 156, 3), tile23},
				{ new Color(249, 84, 187), tile24},
				{ new Color(231, 203, 213), tile25},
				{ new Color(168, 17, 159), tile26},
				{ new Color(233, 39, 10), tile27},
				{ new Color(94, 122, 229), tile28},
				{ new Color(133, 56, 163), tile29},
				{ new Color(19, 49, 174), tile30},
				{ new Color(145, 129, 164), tile31},
				{ new Color(4, 15, 248), tile32},
				{ new Color(44, 25, 158), tile33},
				{ new Color(219, 101, 241), tile34},
				{ new Color(185, 53, 93), tile35},
				{ new Color(26, 83, 170), tile36},
				{ new Color(183, 251, 150), tile37},
				{ new Color(229, 171, 171), tile38},
				{ new Color(25, 216, 41), tile39},
				{ new Color(46, 151, 56), tile40},
				{ new Color(255, 162, 107), tile41},
				{ new Color(85, 103, 211), tile42},
				{ new Color(23, 226, 187), tile43},
				{ new Color(220, 123, 247), tile44},
				{ new Color(1, 13, 193), tile45},
				{ new Color(25, 164, 69), tile46},
				{ new Color(135, 106, 229), tile47},
				{ new Color(249, 91, 53), tile48},
				{ new Color(23, 172, 213), tile49},
				{ new Color(248, 234, 54), tile50},
				{ new Color(206, 254, 129), tile51},
				{ new Color(101, 219, 195), tile52},
				{ new Color(133, 100, 205), tile53},
				{ new Color(137, 3, 112), tile54},
				{ new Color(238, 218, 128), tile55},
				{ new Color(158, 227, 158), tile56},
				{ new Color(234, 0, 52), tile57},
				{ new Color(228, 166, 45), tile58},
				{ new Color(82, 5, 71), tile59},
				{ new Color(54, 61, 187), tile60},
				{ new Color(254, 30, 247), tile61},
				{ new Color(132, 13, 124), tile62},
				{ new Color(118, 155, 49), tile63},
				{ new Color(254, 147, 64), tile64},
				{ new Color(119, 253, 103), tile65},
				{ new Color(117, 10, 128), tile66},
				{ new Color(181, 121, 200), tile67},
				{ new Color(55, 14, 234), tile68},
				{ new Color(2, 234, 88), tile69},
				{ new Color(84, 19, 214), tile70},
				{ new Color(123, 79, 39), tile71},
				{ new Color(18, 139, 229), tile72},
				{ new Color(120, 105, 205), tile73},
				{ new Color(3, 40, 72), tile74},
				{ new Color(108, 235, 109), tile75},
				{ new Color(244, 108, 168), tile76},
				{ new Color(197, 221, 250), tile77},
				{ new Color(199, 128, 195), tile78},
				{ new Color(242, 199, 16), tile79},
				{ new Color(13, 130, 35), tile80},
				{ new Color(36, 33, 136), tile81},
				{ new Color(91, 130, 67), tile82},
				{ new Color(24, 101, 114), tile83},
				{ new Color(129, 252, 161), tile84},
				{ new Color(179, 178, 80), tile85},
				{ new Color(128, 202, 34), tile86},
				{ new Color(124, 14, 125), tile87},
				{ new Color(175, 142, 53), tile88},
				{ new Color(219, 180, 207), tile89},
				{ new Color(99, 31, 195), tile90},
				{ new Color(213, 107, 231), tile91},
				{ new Color(169, 223, 7), tile92},
				{ new Color(192, 16, 105), tile93},
				{ new Color(42, 219, 7), tile94},
				{ new Color(53, 68, 225), tile95},
				{ new Color(89, 19, 206), tile96},
				{ new Color(114, 114, 252), tile97},
				{ new Color(237, 144, 116), tile98},
				{ new Color(165, 116, 146), tile99},
				{ new Color(83, 128, 206), tile100},
				{ new Color(115, 181, 69), tile101},
				{ new Color(175, 172, 145), tile102},
				{ new Color(185, 9, 210), tile103},
				{ new Color(73, 192, 186), tile104},
				{ new Color(185, 82, 50), tile105},
				{ new Color(117, 121, 74), tile106},
				{ new Color(83, 129, 160), tile107},
				{ new Color(1, 240, 173), tile108},
				{ new Color(198, 231, 218), tile109},
				{ new Color(115, 4, 106), tile110},
				{ new Color(116, 108, 143), tile111},
				{ new Color(154, 182, 38), tile112},
				{ new Color(194, 134, 151), tile113},
				{ new Color(79, 160, 10), tile114},
				{ new Color(251, 41, 178), tile115},
				{ new Color(66, 52, 62), tile116},
				{ new Color(65, 47, 250), tile117},
				{ new Color(71, 255, 255), tile118},
				{ new Color(45, 114, 197), tile119},
				{ new Color(151, 232, 196), tile120},
				{ new Color(182, 70, 5), tile121},
				{ new Color(103, 212, 83), tile122},
				{ new Color(42, 30, 156), tile123},
				{ new Color(12, 179, 243), tile124},
				{ new Color(179, 3, 224), tile125},
				{ new Color(150, 5, 199), tile126},
				{ new Color(251, 132, 179), tile127},
				{ new Color(156, 49, 212), tile128},
				{ new Color(112, 45, 109), tile129},
				{ new Color(144, 109, 68), tile130},
				{ new Color(97, 43, 157), tile131},
				{ new Color(210, 152, 90), tile132},
				{ new Color(5, 148, 84), tile133},
				{ new Color(94, 23, 21), tile134},
				{ new Color(161, 53, 124), tile135},
				{ new Color(6, 148, 251), tile136},
				{ new Color(30, 151, 108), tile137},
				{ new Color(254, 155, 100), tile138},
				{ new Color(17, 26, 20), tile139},
				{ new Color(49, 247, 167), tile140},
				{ new Color(230, 153, 177), tile141},
				{ new Color(87, 171, 135), tile142},
				{ new Color(86, 224, 106), tile143},
				{ new Color(134, 145, 113), tile144},
				{ new Color(114, 156, 108), tile145},
				{ new Color(158, 250, 251), tile146},
				{ new Color(87, 105, 153), tile147},
				{ new Color(113, 114, 214), tile148},
				{ new Color(215, 98, 143), tile149},
				{ new Color(56, 193, 126), tile150},
				{ new Color(69, 211, 157), tile151},
				{ new Color(172, 120, 125), tile152},
				{ new Color(100, 74, 138), tile153},
				{ new Color(244, 176, 179), tile154},
				{ new Color(144, 151, 5), tile155},
				{ new Color(251, 139, 255), tile156},
				{ new Color(247, 115, 32), tile157},
				{ new Color(25, 217, 141), tile158},
				{ new Color(14, 116, 39), tile159},
				{ new Color(218, 128, 72), tile160},
				{ new Color(248, 29, 31), tile161},
				{ new Color(236, 65, 189), tile162},
				{ new Color(212, 198, 36), tile163},
				{ new Color(238, 57, 176), tile164},
				{ new Color(113, 98, 184), tile165},
				{ new Color(229, 224, 218), tile166},
				{ new Color(208, 220, 215), tile167},
				{ new Color(144, 64, 78), tile168},
				{ new Color(94, 44, 250), tile169},
				{ new Color(15, 157, 3), tile170},
				{ new Color(86, 137, 201), tile171},
				{ new Color(66, 252, 147), tile172},
				{ new Color(148, 164, 86), tile173},
				{ new Color(72, 39, 196), tile174},
				{ new Color(219, 9, 57), tile175},
				{ new Color(111, 167, 119), tile176},
				{ new Color(212, 40, 148), tile177},
				{ new Color(77, 10, 164), tile178},
				{ new Color(112, 104, 220), tile179},
				{ new Color(208, 142, 20), tile180},
				{ new Color(195, 196, 40), tile181},
				{ new Color(32, 152, 176), tile182},
				{ new Color(230, 47, 102), tile183},
				{ new Color(37, 81, 60), tile184},
				{ new Color(131, 136, 180), tile185},
				{ new Color(19, 181, 55), tile186},
				{ new Color(21, 238, 132), tile187},
				{ new Color(130, 58, 116), tile188},
				{ new Color(111, 8, 127), tile189},
				{ new Color(37, 209, 147), tile190},
				{ new Color(182, 195, 22), tile191},
				{ new Color(66, 133, 98), tile192},
				{ new Color(156, 186, 113), tile193},
				{ new Color(136, 137, 120), tile194},
				{ new Color(17, 174, 215), tile195},
				{ new Color(87, 201, 130), tile196},
				{ new Color(239, 93, 179), tile197},
				{ new Color(165, 187, 159), tile198},
				{ new Color(144, 64, 137), tile199},
				{ new Color(179, 176, 143), tile200},
				{ new Color(48, 192, 93), tile201},
				{ new Color(210, 111, 142), tile202},
				{ new Color(37, 65, 2), tile203},
				{ new Color(82, 118, 250), tile204},
				{ new Color(198, 140, 101), tile205},
				{ new Color(11, 112, 139), tile206},
				{ new Color(157, 23, 63), tile207},
				{ new Color(253, 54, 116), tile208},
				{ new Color(224, 17, 7), tile209},
				{ new Color(118, 178, 68), tile210},
				{ new Color(216, 232, 10), tile211},
				{ new Color(225, 88, 201), tile212},
				{ new Color(27, 63, 63), tile213},
				{ new Color(73, 50, 136), tile214},
				{ new Color(127, 157, 230), tile215},
				{ new Color(185, 222, 47), tile216},
				{ new Color(58, 132, 207), tile217},
				{ new Color(253, 21, 152), tile218},
				{ new Color(80, 51, 137), tile219},
				{ new Color(232, 241, 93), tile220},
				{ new Color(134, 174, 143), tile221},
				{ new Color(190, 121, 142), tile222},
				{ new Color(239, 228, 52), tile223},
				{ new Color(156, 240, 49), tile224},
				{ new Color(76, 84, 229), tile225},
				{ new Color(182, 125, 153), tile226},
				{ new Color(142, 39, 51), tile227},
				{ new Color(216, 60, 46), tile228},
				{ new Color(116, 218, 210), tile229},
				{ new Color(113, 145, 36), tile230},
				{ new Color(63, 51, 77), tile231},
				{ new Color(225, 194, 131), tile232},
				{ new Color(249, 193, 35), tile233},
				{ new Color(88, 201, 249), tile234},
				{ new Color(251, 158, 147), tile235},
				{ new Color(158, 177, 193), tile236},
				{ new Color(178, 153, 181), tile237},
				{ new Color(240, 90, 202), tile238},
				{ new Color(42, 174, 114), tile239},
				{ new Color(97, 73, 158), tile240},
				{ new Color(187, 125, 83), tile241},
				{ new Color(15, 92, 189), tile242},
				{ new Color(227, 106, 145), tile243},
				{ new Color(98, 188, 188), tile244},
				{ new Color(118, 54, 93), tile245},
				{ new Color(57, 221, 158), tile246},
				{ new Color(154, 214, 41), tile247},
				{ new Color(17, 191, 247), tile248},
				{ new Color(110, 79, 216), tile249},
				{ new Color(131, 183, 20), tile250},
				{ new Color(16, 152, 119), tile251},
				{ new Color(133, 156, 76), tile252},
				{ new Color(166, 235, 65), tile253},
				{ new Color(214, 186, 71), tile254},
				{ new Color(47, 80, 221), tile255},
				{ new Color(248, 122, 36), tile256},
				{ new Color(109, 241, 208), tile257},
				{ new Color(211, 198, 114), tile258},
				{ new Color(117, 170, 190), tile259},
				{ new Color(91, 161, 13), tile260},
				{ new Color(228, 96, 179), tile261},
				{ new Color(125, 81, 36), tile262},
				{ new Color(69, 240, 153), tile263},
				{ new Color(17, 147, 242), tile264},
				{ new Color(93, 195, 28), tile265},
				{ new Color(226, 225, 110), tile266},
				{ new Color(26, 117, 212), tile267},
				{ new Color(180, 22, 197), tile268},
				{ new Color(67, 60, 209), tile269},
				{ new Color(5, 15, 242), tile270},
				{ new Color(141, 74, 73), tile271},
				{ new Color(51, 242, 89), tile272},
				{ new Color(147, 178, 254), tile273},
				{ new Color(184, 179, 137), tile274},
				{ new Color(138, 92, 94), tile275},
				{ new Color(222, 118, 3), tile276},
				{ new Color(85, 146, 200), tile277},
				{ new Color(79, 65, 43), tile278},
				{ new Color(56, 47, 74), tile279},
				{ new Color(237, 57, 20), tile280},
				{ new Color(82, 63, 225), tile281},
				{ new Color(166, 131, 72), tile282},
				{ new Color(168, 42, 208), tile283},
				{ new Color(195, 78, 46), tile284},
				{ new Color(112, 97, 194), tile285},
				{ new Color(75, 41, 185), tile286},
				{ new Color(103, 101, 198), tile287},
				{ new Color(206, 175, 125), tile288},
				{ new Color(42, 62, 9), tile289},
				{ new Color(30, 250, 194), tile290},
				{ new Color(14, 166, 121), tile291},
				{ new Color(233, 102, 116), tile292},
				{ new Color(168, 228, 216), tile293},
				{ new Color(21, 54, 76), tile294},
				{ new Color(50, 146, 68), tile295},
				{ new Color(154, 223, 223), tile296},
				{ new Color(105, 237, 5), tile297},
				{ new Color(144, 134, 212), tile298},
				{ new Color(78, 132, 143), tile299},
				{ new Color(99, 124, 69), tile300},
				{ new Color(62, 137, 47), tile301},
				{ new Color(14, 180, 168), tile302},
				{ new Color(181, 134, 250), tile303},
				{ new Color(78, 163, 69), tile304},
			};
			return new ColorTileMap(colorTileMap);
		}
	}
}
