using CalamityMod.Tiles.FurniturePlaguedPlate;
using CalamityMod.Tiles.FurnitureStratus;
using CalamityMod.Tiles.Furniture.CraftingStations;
using CalamityMod.Walls;
using Microsoft.Xna.Framework;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Terraria.ID;
using Terraria.ModLoader;
using CalamityMod.Tiles;

namespace CalamityMod.Schematics.AutoGeneratedContent
{
    public class PlagueResearchFacilitySchematic
	{
		[GeneratedCode("ScreenCaptureToSchematic", "1.0.1")]
		public static ColorTileMap GetMap()
		{
			var tile1 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0);
			var tile2 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 54).UseSlope(2).UseHeaders(0, 0, 0, 8224);
			var tile3 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseHeaders(0, 0, 0, 32);
			var tile4 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 18).UseHeaders(0, 16, 0, 32);
			var tile5 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 72).UseSlope(4).UseHeaders(0, 32, 0, 16416);
			var tile6 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 36).UseHeaders(0, 32, 0, 32);
			var tile7 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 72).UseSlope(4).UseHeaders(0, 0, 0, 16416);
			var tile8 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 18).UseHeaders(0, 16, 0, 32);
			var tile9 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 0).UseHeaders(0, 0, 0, 32);
			var tile10 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 18).UseHeaders(0, 16, 0, 32);
			var tile11 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 72).UseHeaders(0, 16, 0, 32);
			var tile12 = new TileDefinitionStructure(TileID.OpenDoor).UseFrame(0, 1080).UseHeaders(0, 0, 0, 32);
			var tile13 = new TileDefinitionStructure(TileID.OpenDoor).UseFrame(0, 1098).UseHeaders(0, 0, 0, 32);
			var tile14 = new TileDefinitionStructure(TileID.OpenDoor).UseFrame(0, 1116).UseHeaders(0, 0, 0, 32);
			var tile15 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile16 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 36).UseHeaders(0, 0, 0, 32);
			var tile17 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 54).UseSlope(2).UseHeaders(0, 16, 0, 8224);
			var tile18 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile19 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(90, 72).UseSlope(3).UseHeaders(0, 32, 0, 12320);
			var tile20 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 72, 108).UseHeaders(0, 66, 3, 0);
			var tile21 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 0, 36).UseHeaders(0, 64, 1, 0);
			var tile22 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 72).UseHeaders(0, 128, 2, 0);
			var tile23 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 0).UseHeaders(0, 0, 0, 0);
			var tile24 = new TileDefinitionStructure(TileID.OpenDoor).UseWall(WallID.MartianConduit, 0, 36).UseFrame(18, 1080).UseHeaders(0, 64, 1, 32);
			var tile25 = new TileDefinitionStructure(TileID.OpenDoor).UseWall(WallID.MartianConduit, 0, 0).UseFrame(18, 1098).UseHeaders(0, 0, 0, 32);
			var tile26 = new TileDefinitionStructure(TileID.OpenDoor).UseWall(WallID.SapphireGemspark, 0, 0).UseFrame(18, 1116).UseHeaders(0, 0, 0, 32);
			var tile27 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 144, 144).UseFrame(36, 0).UseHeaders(0, 148, 4, 32);
			var tile28 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 36).UseHeaders(0, 32, 0, 32);
			var tile29 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 18).UseHeaders(0, 32, 0, 32);
			var tile30 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 72).UseSlope(3).UseHeaders(0, 0, 0, 12320);
			var tile31 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 0, 108).UseHeaders(0, 0, 3, 0);
			var tile32 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 252, 72).UseHeaders(0, 71, 2, 0);
			var tile33 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 108, 36).UseHeaders(0, 131, 1, 0);
			var tile34 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseHeaders(0, 1, 1, 0);
			var tile35 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 72).UseHeaders(0, 71, 2, 0);
			var tile36 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseHeaders(0, 66, 1, 0);
			var tile37 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 72, 36).UseHeaders(0, 66, 1, 0);
			var tile38 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 108, 36).UseHeaders(0, 131, 1, 0);
			var tile39 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(54, 0).UseHeaders(0, 98, 2, 32);
			var tile40 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 144, 108).UseHeaders(0, 132, 3, 0);
			var tile41 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 396, 72).UseHeaders(0, 139, 2, 0);
			var tile42 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 36, 36).UseHeaders(0, 1, 1, 0);
			var tile43 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 288, 36).UseHeaders(0, 136, 1, 0);
			var tile44 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 36).UseHeaders(0, 75, 1, 0);
			var tile45 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 36).UseHeaders(0, 136, 1, 0);
			var tile46 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 252, 36).UseHeaders(0, 71, 1, 0);
			var tile47 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(18, 0).UseHeaders(0, 66, 2, 32);
			var tile48 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 0).UseHeaders(0, 16, 0, 32);
			var tile49 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 36).UseHeaders(0, 16, 0, 32);
			var tile50 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 0, 108).UseHeaders(0, 0, 3, 32);
			var tile51 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 360, 36).UseFrame(0, 18).UseHeaders(0, 74, 1, 32);
			var tile52 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 360, 36).UseHeaders(0, 74, 1, 0);
			var tile53 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 36).UseHeaders(0, 74, 1, 0);
			var tile54 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 108, 36).UseHeaders(0, 131, 1, 32);
			var tile55 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 108, 36).UseFrame(0, 18).UseHeaders(0, 131, 1, 32);
			var tile56 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.SapphireGemspark, 360, 0).UseFrame(0, 36).UseHeaders(0, 10, 0, 32);
			var tile57 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 36).UseFrame(54, 0).UseHeaders(0, 98, 1, 32);
			var tile58 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 216, 108).UseFrame(18, 18).UseHeaders(0, 6, 3, 32);
			var tile59 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 54).UseSlope(2).UseHeaders(0, 32, 0, 8224);
			var tile60 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 108, 0).UseHeaders(0, 131, 0, 0);
			var tile61 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseHeaders(0, 131, 1, 0);
			var tile62 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 72).UseHeaders(0, 6, 2, 0);
			var tile63 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 108, 36).UseFrame(18, 0).UseHeaders(0, 131, 1, 32);
			var tile64 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 252, 72).UseFrame(18, 18).UseHeaders(0, 71, 2, 32);
			var tile65 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.SapphireGemspark, 36, 36).UseFrame(18, 36).UseHeaders(0, 1, 1, 32);
			var tile66 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(18, 0).UseHeaders(0, 131, 2, 32);
			var tile67 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 36).UseFrame(36, 252).UseHeaders(0, 75, 1, 32);
			var tile68 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 72).UseHeaders(0, 139, 2, 0);
			var tile69 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 36).UseHeaders(0, 71, 1, 0);
			var tile70 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 396, 72).UseFrame(36, 0).UseHeaders(0, 139, 2, 32);
			var tile71 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 36, 36).UseFrame(36, 18).UseHeaders(0, 1, 1, 32);
			var tile72 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.SapphireGemspark, 252, 36).UseFrame(36, 36).UseHeaders(0, 71, 1, 32);
			var tile73 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(36, 0).UseHeaders(0, 147, 2, 32);
			var tile74 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(0, 252).UseHeaders(0, 1, 1, 32);
			var tile75 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 360, 0).UseHeaders(0, 10, 0, 0);
			var tile76 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 72).UseHeaders(0, 138, 2, 0);
			var tile77 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 360, 72).UseHeaders(0, 138, 2, 0);
			var tile78 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(54, 54).UseHeaders(0, 17, 2, 32);
			var tile79 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 0).UseHeaders(0, 32, 0, 32);
			var tile80 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 252, 0).UseHeaders(0, 71, 0, 32);
			var tile81 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 108, 36).UseFrame(0, 18).UseHeaders(0, 131, 1, 32);
			var tile82 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 216, 72).UseHeaders(0, 6, 2, 0);
			var tile83 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(0, 252).UseHeaders(0, 131, 1, 32);
			var tile84 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 36, 36).UseHeaders(0, 1, 1, 0);
			var tile85 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(180, 252).UseSlope(1).UseHeaders(0, 131, 2, 4128);
			var tile86 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 0).UseFrame(54, 18).UseHeaders(0, 168, 0, 32);
			var tile87 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 144).UseFrame(90, 72).UseSlope(3).UseHeaders(0, 98, 4, 12320);
			var tile88 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseHeaders(0, 0, 0, 32);
			var tile89 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)WallID.MartianConduit, 72, 0).UseFrame(0, 18).UseHeaders(0, 66, 0, 32);
			var tile90 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(0, 36).UseHeaders(0, 66, 1, 32);
			var tile91 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 36).UseFrame(0, 54).UseHeaders(0, 136, 1, 32);
			var tile92 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 72).UseFrame(0, 252).UseHeaders(0, 139, 2, 32);
			var tile93 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 36).UseHeaders(0, 6, 1, 0);
			var tile94 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 216, 36).UseHeaders(0, 6, 1, 0);
			var tile95 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 396, 0).UseHeaders(0, 11, 0, 0);
			var tile96 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 0, 144).UseFrame(18, 0).UseHeaders(0, 0, 4, 32);
			var tile97 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 0).UseHeaders(0, 66, 0, 0);
			var tile98 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 36).UseFrame(18, 0).UseHeaders(0, 64, 1, 32);
			var tile99 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(18, 18).UseHeaders(0, 66, 1, 32);
			var tile100 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(18, 36).UseHeaders(0, 66, 1, 32);
			var tile101 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 0).UseFrame(18, 54).UseHeaders(0, 10, 0, 32);
			var tile102 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlate>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(180, 54).UseHeaders(0, 17, 1, 32);
			var tile103 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 72).UseHeaders(0, 138, 2, 32);
			var tile104 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 36, 36).UseFrame(0, 18).UseHeaders(0, 1, 1, 32);
			var tile105 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 0).UseHeaders(0, 131, 0, 0);
			var tile106 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(36, 0).UseHeaders(0, 1, 1, 32);
			var tile107 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(36, 18).UseHeaders(0, 1, 1, 32);
			var tile108 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 72).UseFrame(36, 36).UseHeaders(0, 136, 2, 32);
			var tile109 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(36, 54).UseHeaders(0, 131, 1, 32);
			var tile110 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 72).UseHeaders(0, 136, 2, 0);
			var tile111 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 72, 0).UseHeaders(0, 66, 0, 0);
			var tile112 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 396, 0).UseHeaders(0, 11, 0, 0);
			var tile113 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 0).UseFrame(0, 252).UseHeaders(0, 11, 0, 32);
			var tile114 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 396, 36).UseHeaders(0, 75, 1, 0);
			var tile115 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 252, 36).UseHeaders(0, 71, 1, 0);
			var tile116 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 396, 36).UseHeaders(0, 75, 1, 0);
			var tile117 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(18, 0).UseHeaders(0, 66, 2, 1056);
			var tile118 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 360, 72).UseHeaders(0, 138, 2, 0);
			var tile119 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 0).UseHeaders(0, 10, 0, 0);
			var tile120 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(54, 0).UseHeaders(0, 163, 2, 1056);
			var tile121 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 36, 0).UseHeaders(0, 1, 0, 0);
			var tile122 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 288, 72).UseHeaders(0, 136, 2, 0);
			var tile123 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(144, 252).UseSlope(2).UseHeaders(0, 131, 1, 8224);
			var tile124 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 72, 36).UseHeaders(0, 66, 1, 0);
			var tile125 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 144).UseFrame(54, 0).UseHeaders(0, 99, 4, 1056);
			var tile126 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 36, 0).UseHeaders(0, 1, 0, 32);
			var tile127 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.Glass, 36, 36).UseFrame(0, 18).UseHeaders(0, 1, 1, 32);
			var tile128 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 252, 36).UseHeaders(0, 71, 1, 0);
			var tile129 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 72, 36).UseFrame(144, 252).UseSlope(2).UseHeaders(0, 66, 1, 8224);
			var tile130 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 396, 0).UseHeaders(0, 11, 0, 0);
			var tile131 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 72, 36).UseHeaders(0, 66, 1, 0);
			var tile132 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 0).UseHeaders(0, 11, 0, 0);
			var tile133 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseHeaders(0, 131, 1, 32);
			var tile134 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 36).UseFrame(0, 18).UseHeaders(0, 136, 1, 32);
			var tile135 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 72).UseFrame(0, 36).UseHeaders(0, 66, 2, 32);
			var tile136 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 108, 36).UseHeaders(0, 131, 1, 0);
			var tile137 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 360, 72).UseHeaders(0, 138, 2, 0);
			var tile138 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 108, 36).UseFrame(216, 252).UseHeaders(0, 131, 1, 32);
			var tile139 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 360, 36).UseHeaders(0, 74, 1, 0);
			var tile140 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 36, 36).UseHeaders(0, 1, 1, 0);
			var tile141 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 360, 0).UseHeaders(0, 10, 0, 0);
			var tile142 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(18, 0).UseHeaders(0, 1, 1, 32);
			var tile143 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 36).UseFrame(18, 18).UseHeaders(0, 74, 1, 32);
			var tile144 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 72).UseFrame(18, 36).UseHeaders(0, 131, 2, 32);
			var tile145 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 252, 72).UseHeaders(0, 71, 2, 0);
			var tile146 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 288, 72).UseFrame(0, 252).UseHeaders(0, 136, 2, 32);
			var tile147 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 288, 72).UseHeaders(0, 136, 2, 0);
			var tile148 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 72).UseFrame(36, 0).UseHeaders(0, 71, 2, 32);
			var tile149 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(36, 18).UseHeaders(0, 1, 1, 32);
			var tile150 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 72).UseFrame(36, 36).UseHeaders(0, 66, 2, 32);
			var tile151 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 216, 36).UseHeaders(0, 6, 1, 0);
			var tile152 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 72, 36).UseFrame(0, 252).UseHeaders(0, 66, 1, 32);
			var tile153 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 288, 108).UseFrame(36, 0).UseHeaders(0, 152, 3, 1056);
			var tile154 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseWall(WallID.Glass, 360, 36).UseHeaders(0, 74, 1, 32);
			var tile155 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(0, 18).UseHeaders(0, 1, 1, 32);
			var tile156 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 108, 36).UseFrame(0, 252).UseHeaders(0, 131, 1, 32);
			var tile157 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseHeaders(0, 131, 1, 32);
			var tile158 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(0, 18).UseHeaders(0, 66, 1, 32);
			var tile159 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 144, 72).UseFrame(0, 36).UseHeaders(0, 132, 2, 32);
			var tile160 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 72).UseFrame(0, 54).UseHeaders(0, 66, 2, 32);
			var tile161 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 216, 72).UseHeaders(0, 6, 2, 0);
			var tile162 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseWall(WallID.Glass, 108, 36).UseFrame(18, 0).UseHeaders(0, 131, 1, 32);
			var tile163 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(18, 18).UseHeaders(0, 1, 1, 32);
			var tile164 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 252, 72).UseFrame(0, 252).UseHeaders(0, 71, 2, 32);
			var tile165 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(18, 0).UseHeaders(0, 66, 1, 32);
			var tile166 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 72).UseFrame(18, 18).UseHeaders(0, 66, 2, 32);
			var tile167 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseFrame(18, 36).UseHeaders(0, 0, 0, 32);
			var tile168 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 144).UseFrame(18, 54).UseHeaders(0, 71, 4, 32);
			var tile169 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseWall(WallID.Glass, 288, 36).UseFrame(36, 0).UseHeaders(0, 136, 1, 32);
			var tile170 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 0).UseFrame(36, 18).UseHeaders(0, 11, 0, 32);
			var tile171 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 288, 36).UseHeaders(0, 136, 1, 0);
			var tile172 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 0).UseFrame(36, 0).UseHeaders(0, 11, 0, 32);
			var tile173 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(36, 18).UseHeaders(0, 131, 1, 32);
			var tile174 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 36).UseFrame(36, 36).UseHeaders(0, 64, 1, 32);
			var tile175 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 72).UseFrame(36, 54).UseHeaders(0, 66, 2, 32);
			var tile176 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 216, 108).UseFrame(36, 0).UseHeaders(0, 22, 3, 1056);
			var tile177 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseHeaders(0, 66, 1, 32);
			var tile178 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 72).UseFrame(0, 18).UseHeaders(0, 6, 2, 32);
			var tile179 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(0, 36).UseHeaders(0, 1, 1, 32);
			var tile180 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 72).UseFrame(0, 54).UseHeaders(0, 1, 2, 32);
			var tile181 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 36, 108).UseHeaders(0, 1, 3, 0);
			var tile182 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 36, 36).UseFrame(0, 252).UseHeaders(0, 1, 1, 32);
			var tile183 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 396, 36).UseHeaders(0, 75, 1, 0);
			var tile184 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall(WallID.MartianConduit, 396, 36).UseFrame(18, 0).UseHeaders(0, 75, 1, 32);
			var tile185 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall(WallID.MartianConduit, 108, 36).UseFrame(18, 18).UseHeaders(0, 131, 1, 32);
			var tile186 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 36).UseFrame(18, 36).UseHeaders(0, 136, 1, 32);
			var tile187 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 72).UseFrame(18, 54).UseHeaders(0, 66, 2, 32);
			var tile188 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(90, 54).UseSlope(1).UseHeaders(0, 32, 0, 4128);
			var tile189 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 72).UseSlope(4).UseHeaders(0, 16, 0, 16416);
			var tile190 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 72, 36).UseFrame(234, 252).UseHeaders(0, 66, 1, 32);
			var tile191 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(36, 0).UseHeaders(0, 131, 1, 32);
			var tile192 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 72).UseFrame(36, 36).UseHeaders(0, 138, 2, 32);
			var tile193 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 108, 0).UseHeaders(0, 131, 0, 32);
			var tile194 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.Glass, 288, 72).UseFrame(0, 18).UseHeaders(0, 136, 2, 32);
			var tile195 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 216, 72).UseFrame(180, 252).UseSlope(1).UseHeaders(0, 6, 2, 4128);
			var tile196 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 144, 144).UseFrame(36, 0).UseHeaders(0, 148, 4, 1056);
			var tile197 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 36).UseFrame(180, 252).UseSlope(1).UseHeaders(0, 136, 1, 4128);
			var tile198 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 396, 72).UseHeaders(0, 139, 2, 0);
			var tile199 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(18, 0).UseHeaders(0, 131, 2, 1056);
			var tile200 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 108, 108).UseHeaders(0, 67, 3, 0);
			var tile201 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.MartianConduit, 72, 36).UseFrame(0, 252).UseHeaders(0, 66, 1, 32);
			var tile202 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(36, 0).UseHeaders(0, 82, 2, 1056);
			var tile203 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.MartianConduit, 36, 36).UseFrame(0, 252).UseHeaders(0, 1, 1, 32);
			var tile204 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 0).UseHeaders(0, 1, 0, 0);
			var tile205 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 72).UseHeaders(0, 139, 2, 32);
			var tile206 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(0, 18).UseHeaders(0, 1, 1, 32);
			var tile207 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 36).UseFrame(0, 36).UseHeaders(0, 6, 1, 32);
			var tile208 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(18, 0).UseHeaders(0, 131, 1, 32);
			var tile209 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(18, 18).UseHeaders(0, 66, 1, 32);
			var tile210 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 36).UseFrame(18, 36).UseHeaders(0, 74, 1, 32);
			var tile211 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(0, 252).UseHeaders(0, 66, 1, 32);
			var tile212 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlate>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(180, 54).UseHeaders(0, 82, 1, 32);
			var tile213 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 72, 36).UseFrame(0, 18).UseHeaders(0, 66, 1, 32);
			var tile214 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(54, 0).UseHeaders(0, 33, 2, 32);
			var tile215 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 54).UseSlope(1).UseHeaders(0, 16, 0, 4128);
			var tile216 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 108).UseFrame(0, 72).UseSlope(4).UseHeaders(0, 67, 3, 16416);
			var tile217 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(36, 0).UseHeaders(0, 131, 1, 32);
			var tile218 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 72).UseFrame(36, 18).UseHeaders(0, 6, 2, 32);
			var tile219 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(36, 36).UseHeaders(0, 66, 1, 32);
			var tile220 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(54, 0).UseHeaders(0, 163, 2, 32);
			var tile221 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 180, 108).UseHeaders(0, 133, 3, 32);
			var tile222 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 396, 72).UseFrame(0, 18).UseHeaders(0, 139, 2, 32);
			var tile223 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.MartianConduit, 396, 0).UseFrame(0, 252).UseHeaders(0, 11, 0, 32);
			var tile224 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.SapphireGemspark, 396, 0).UseFrame(144, 252).UseSlope(2).UseHeaders(0, 11, 0, 8224);
			var tile225 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 144).UseFrame(18, 0).UseHeaders(0, 67, 4, 32);
			var tile226 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 54).UseSlope(1).UseHeaders(0, 0, 0, 4128);
			var tile227 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.MartianConduit, 36, 36).UseFrame(18, 252).UseHeaders(0, 1, 1, 32);
			var tile228 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(0, 54).UseHeaders(0, 66, 2, 32);
			var tile229 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 180, 108).UseHeaders(0, 133, 3, 0);
			var tile230 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(36, 0).UseHeaders(0, 82, 2, 32);
			var tile231 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 288, 36).UseHeaders(0, 136, 1, 0);
			var tile232 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 36, 108).UseHeaders(0, 1, 3, 32);
			var tile233 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 360, 72).UseFrame(0, 18).UseHeaders(0, 138, 2, 32);
			var tile234 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 36).UseHeaders(0, 74, 1, 32);
			var tile235 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.MartianConduit, 36, 36).UseFrame(0, 18).UseHeaders(0, 1, 1, 32);
			var tile236 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.MartianConduit, 36, 36).UseFrame(0, 36).UseHeaders(0, 1, 1, 32);
			var tile237 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.SapphireGemspark, 360, 36).UseFrame(0, 54).UseHeaders(0, 74, 1, 32);
			var tile238 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(18, 0).UseHeaders(0, 1, 1, 32);
			var tile239 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.MartianConduit, 72, 36).UseFrame(18, 18).UseHeaders(0, 66, 1, 32);
			var tile240 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.MartianConduit, 216, 72).UseFrame(18, 36).UseHeaders(0, 6, 2, 32);
			var tile241 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.SapphireGemspark, 72, 36).UseFrame(18, 54).UseHeaders(0, 66, 1, 32);
			var tile242 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 216, 36).UseHeaders(0, 6, 1, 0);
			var tile243 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 144, 72).UseHeaders(0, 132, 2, 0);
			var tile244 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 144, 36).UseHeaders(0, 68, 1, 0);
			var tile245 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 144, 72).UseHeaders(0, 132, 2, 0);
			var tile246 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 144, 0).UseHeaders(0, 4, 0, 0);
			var tile247 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 144, 36).UseHeaders(0, 68, 1, 0);
			var tile248 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 144).UseFrame(36, 0).UseHeaders(0, 17, 4, 32);
			var tile249 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 432, 36).UseFrame(0, 18).UseHeaders(0, 92, 1, 32);
			var tile250 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 72).UseHeaders(0, 0, 0, 32);
			var tile251 = new TileDefinitionStructure(TileID.ClosedDoor).UseFrame(0, 1080).UseHeaders(0, 0, 0, 32);
			var tile252 = new TileDefinitionStructure(TileID.ClosedDoor).UseFrame(0, 1098).UseHeaders(0, 0, 0, 32);
			var tile253 = new TileDefinitionStructure(TileID.ClosedDoor).UseFrame(0, 1116).UseHeaders(0, 0, 0, 32);
			var tile254 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 36).UseHeaders(0, 32, 0, 32);
			var tile255 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 72).UseSlope(3).UseHeaders(0, 16, 0, 12320);
			Dictionary<Color, TileDefinitionStructure> colorTileMap = new Dictionary<Color, TileDefinitionStructure>()
			{
				{ new Color(255, 255, 255), tile1},
				{ new Color(136, 86, 26), tile2},
				{ new Color(162, 233, 185), tile3},
				{ new Color(129, 44, 6), tile4},
				{ new Color(165, 129, 211), tile5},
				{ new Color(154, 153, 14), tile6},
				{ new Color(242, 194, 147), tile7},
				{ new Color(243, 12, 88), tile8},
				{ new Color(102, 120, 243), tile9},
				{ new Color(73, 19, 77), tile10},
				{ new Color(217, 195, 141), tile11},
				{ new Color(149, 20, 125), tile12},
				{ new Color(158, 190, 55), tile13},
				{ new Color(45, 86, 218), tile14},
				{ new Color(191, 21, 23), tile15},
				{ new Color(172, 82, 177), tile16},
				{ new Color(96, 128, 185), tile17},
				{ new Color(89, 19, 117), tile18},
				{ new Color(28, 29, 104), tile19},
				{ new Color(172, 34, 222), tile20},
				{ new Color(39, 88, 213), tile21},
				{ new Color(108, 168, 104), tile22},
				{ new Color(121, 15, 108), tile23},
				{ new Color(86, 251, 218), tile24},
				{ new Color(214, 196, 108), tile25},
				{ new Color(185, 51, 246), tile26},
				{ new Color(64, 185, 37), tile27},
				{ new Color(65, 233, 147), tile28},
				{ new Color(147, 128, 175), tile29},
				{ new Color(23, 121, 246), tile30},
				{ new Color(21, 242, 156), tile31},
				{ new Color(88, 6, 253), tile32},
				{ new Color(4, 83, 109), tile33},
				{ new Color(174, 50, 67), tile34},
				{ new Color(69, 9, 132), tile35},
				{ new Color(223, 130, 78), tile36},
				{ new Color(8, 98, 233), tile37},
				{ new Color(113, 107, 104), tile38},
				{ new Color(184, 229, 110), tile39},
				{ new Color(66, 217, 39), tile40},
				{ new Color(184, 97, 150), tile41},
				{ new Color(117, 65, 9), tile42},
				{ new Color(62, 126, 189), tile43},
				{ new Color(111, 181, 224), tile44},
				{ new Color(137, 146, 134), tile45},
				{ new Color(226, 252, 224), tile46},
				{ new Color(14, 179, 254), tile47},
				{ new Color(97, 15, 22), tile48},
				{ new Color(12, 163, 134), tile49},
				{ new Color(51, 159, 33), tile50},
				{ new Color(142, 193, 122), tile51},
				{ new Color(69, 245, 209), tile52},
				{ new Color(173, 207, 200), tile53},
				{ new Color(123, 161, 3), tile54},
				{ new Color(145, 153, 173), tile55},
				{ new Color(9, 231, 217), tile56},
				{ new Color(225, 214, 232), tile57},
				{ new Color(142, 51, 37), tile58},
				{ new Color(41, 87, 82), tile59},
				{ new Color(127, 104, 157), tile60},
				{ new Color(130, 10, 222), tile61},
				{ new Color(156, 224, 243), tile62},
				{ new Color(102, 67, 156), tile63},
				{ new Color(181, 53, 45), tile64},
				{ new Color(24, 147, 18), tile65},
				{ new Color(250, 208, 117), tile66},
				{ new Color(105, 3, 188), tile67},
				{ new Color(173, 81, 201), tile68},
				{ new Color(56, 0, 142), tile69},
				{ new Color(84, 27, 158), tile70},
				{ new Color(126, 45, 102), tile71},
				{ new Color(42, 248, 150), tile72},
				{ new Color(37, 244, 185), tile73},
				{ new Color(186, 163, 163), tile74},
				{ new Color(60, 44, 160), tile75},
				{ new Color(187, 118, 160), tile76},
				{ new Color(18, 47, 135), tile77},
				{ new Color(220, 22, 101), tile78},
				{ new Color(225, 213, 184), tile79},
				{ new Color(21, 99, 223), tile80},
				{ new Color(101, 17, 40), tile81},
				{ new Color(254, 55, 8), tile82},
				{ new Color(198, 237, 155), tile83},
				{ new Color(123, 212, 219), tile84},
				{ new Color(188, 174, 95), tile85},
				{ new Color(24, 112, 37), tile86},
				{ new Color(41, 125, 138), tile87},
				{ new Color(238, 66, 236), tile88},
				{ new Color(22, 161, 23), tile89},
				{ new Color(1, 73, 34), tile90},
				{ new Color(221, 16, 144), tile91},
				{ new Color(217, 84, 146), tile92},
				{ new Color(123, 62, 244), tile93},
				{ new Color(152, 244, 137), tile94},
				{ new Color(4, 151, 90), tile95},
				{ new Color(172, 32, 103), tile96},
				{ new Color(5, 201, 101), tile97},
				{ new Color(146, 235, 230), tile98},
				{ new Color(85, 119, 206), tile99},
				{ new Color(60, 231, 150), tile100},
				{ new Color(240, 197, 163), tile101},
				{ new Color(120, 157, 196), tile102},
				{ new Color(74, 227, 89), tile103},
				{ new Color(205, 156, 49), tile104},
				{ new Color(49, 145, 136), tile105},
				{ new Color(1, 233, 171), tile106},
				{ new Color(145, 106, 129), tile107},
				{ new Color(175, 251, 128), tile108},
				{ new Color(189, 74, 36), tile109},
				{ new Color(170, 132, 221), tile110},
				{ new Color(195, 63, 87), tile111},
				{ new Color(94, 167, 47), tile112},
				{ new Color(229, 139, 249), tile113},
				{ new Color(149, 97, 61), tile114},
				{ new Color(13, 55, 44), tile115},
				{ new Color(51, 97, 90), tile116},
				{ new Color(94, 83, 141), tile117},
				{ new Color(35, 170, 124), tile118},
				{ new Color(21, 65, 201), tile119},
				{ new Color(34, 187, 82), tile120},
				{ new Color(160, 160, 94), tile121},
				{ new Color(124, 9, 93), tile122},
				{ new Color(218, 211, 233), tile123},
				{ new Color(89, 27, 94), tile124},
				{ new Color(177, 251, 9), tile125},
				{ new Color(67, 162, 195), tile126},
				{ new Color(83, 138, 233), tile127},
				{ new Color(201, 76, 48), tile128},
				{ new Color(80, 159, 148), tile129},
				{ new Color(218, 72, 102), tile130},
				{ new Color(101, 194, 208), tile131},
				{ new Color(166, 245, 193), tile132},
				{ new Color(222, 145, 45), tile133},
				{ new Color(207, 88, 142), tile134},
				{ new Color(112, 5, 56), tile135},
				{ new Color(47, 114, 175), tile136},
				{ new Color(115, 209, 159), tile137},
				{ new Color(5, 207, 49), tile138},
				{ new Color(105, 214, 84), tile139},
				{ new Color(46, 43, 106), tile140},
				{ new Color(200, 255, 138), tile141},
				{ new Color(131, 243, 88), tile142},
				{ new Color(141, 11, 5), tile143},
				{ new Color(71, 101, 16), tile144},
				{ new Color(150, 132, 49), tile145},
				{ new Color(90, 89, 70), tile146},
				{ new Color(247, 32, 45), tile147},
				{ new Color(228, 102, 119), tile148},
				{ new Color(198, 95, 243), tile149},
				{ new Color(158, 60, 31), tile150},
				{ new Color(109, 175, 101), tile151},
				{ new Color(195, 7, 89), tile152},
				{ new Color(4, 236, 17), tile153},
				{ new Color(223, 161, 102), tile154},
				{ new Color(170, 44, 107), tile155},
				{ new Color(142, 111, 74), tile156},
				{ new Color(0, 14, 125), tile157},
				{ new Color(13, 54, 10), tile158},
				{ new Color(60, 227, 152), tile159},
				{ new Color(18, 188, 148), tile160},
				{ new Color(100, 239, 206), tile161},
				{ new Color(230, 217, 181), tile162},
				{ new Color(170, 210, 125), tile163},
				{ new Color(215, 86, 108), tile164},
				{ new Color(53, 23, 127), tile165},
				{ new Color(199, 58, 58), tile166},
				{ new Color(12, 56, 239), tile167},
				{ new Color(168, 158, 46), tile168},
				{ new Color(161, 96, 121), tile169},
				{ new Color(90, 134, 35), tile170},
				{ new Color(192, 242, 48), tile171},
				{ new Color(125, 123, 178), tile172},
				{ new Color(152, 195, 82), tile173},
				{ new Color(181, 227, 157), tile174},
				{ new Color(205, 40, 184), tile175},
				{ new Color(17, 215, 30), tile176},
				{ new Color(139, 117, 169), tile177},
				{ new Color(94, 6, 132), tile178},
				{ new Color(164, 187, 81), tile179},
				{ new Color(160, 69, 121), tile180},
				{ new Color(60, 79, 75), tile181},
				{ new Color(89, 23, 100), tile182},
				{ new Color(60, 184, 156), tile183},
				{ new Color(205, 46, 119), tile184},
				{ new Color(232, 86, 84), tile185},
				{ new Color(82, 219, 117), tile186},
				{ new Color(117, 144, 136), tile187},
				{ new Color(90, 207, 17), tile188},
				{ new Color(122, 97, 235), tile189},
				{ new Color(171, 216, 191), tile190},
				{ new Color(97, 247, 126), tile191},
				{ new Color(217, 120, 147), tile192},
				{ new Color(81, 116, 16), tile193},
				{ new Color(83, 213, 31), tile194},
				{ new Color(130, 190, 70), tile195},
				{ new Color(49, 118, 175), tile196},
				{ new Color(47, 82, 224), tile197},
				{ new Color(219, 42, 181), tile198},
				{ new Color(240, 226, 128), tile199},
				{ new Color(58, 223, 182), tile200},
				{ new Color(120, 144, 223), tile201},
				{ new Color(221, 107, 55), tile202},
				{ new Color(248, 14, 221), tile203},
				{ new Color(193, 0, 103), tile204},
				{ new Color(100, 34, 186), tile205},
				{ new Color(105, 216, 17), tile206},
				{ new Color(202, 72, 235), tile207},
				{ new Color(60, 124, 134), tile208},
				{ new Color(222, 133, 205), tile209},
				{ new Color(201, 232, 150), tile210},
				{ new Color(19, 23, 148), tile211},
				{ new Color(90, 219, 69), tile212},
				{ new Color(63, 164, 82), tile213},
				{ new Color(15, 57, 103), tile214},
				{ new Color(210, 109, 81), tile215},
				{ new Color(121, 118, 8), tile216},
				{ new Color(250, 134, 9), tile217},
				{ new Color(110, 111, 150), tile218},
				{ new Color(202, 60, 20), tile219},
				{ new Color(88, 254, 230), tile220},
				{ new Color(105, 47, 38), tile221},
				{ new Color(70, 174, 233), tile222},
				{ new Color(210, 10, 70), tile223},
				{ new Color(117, 41, 51), tile224},
				{ new Color(191, 187, 15), tile225},
				{ new Color(131, 105, 14), tile226},
				{ new Color(53, 101, 15), tile227},
				{ new Color(197, 206, 97), tile228},
				{ new Color(141, 164, 168), tile229},
				{ new Color(253, 143, 158), tile230},
				{ new Color(48, 230, 166), tile231},
				{ new Color(108, 166, 9), tile232},
				{ new Color(65, 139, 191), tile233},
				{ new Color(104, 167, 108), tile234},
				{ new Color(193, 132, 93), tile235},
				{ new Color(214, 175, 180), tile236},
				{ new Color(135, 71, 210), tile237},
				{ new Color(5, 35, 153), tile238},
				{ new Color(215, 164, 96), tile239},
				{ new Color(196, 185, 9), tile240},
				{ new Color(64, 212, 122), tile241},
				{ new Color(167, 68, 66), tile242},
				{ new Color(141, 83, 20), tile243},
				{ new Color(5, 66, 222), tile244},
				{ new Color(78, 204, 189), tile245},
				{ new Color(162, 3, 74), tile246},
				{ new Color(4, 182, 244), tile247},
				{ new Color(243, 118, 72), tile248},
				{ new Color(204, 43, 195), tile249},
				{ new Color(13, 148, 2), tile250},
				{ new Color(168, 125, 210), tile251},
				{ new Color(182, 39, 211), tile252},
				{ new Color(241, 25, 64), tile253},
				{ new Color(26, 72, 92), tile254},
				{ new Color(159, 129, 5), tile255},
			};
			return new ColorTileMap(colorTileMap);
		}
	}
}
