using CalamityMod.Tiles;
using Microsoft.Xna.Framework;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Terraria.ID;
using Terraria.ModLoader;
using CalamityMod.Tiles.DraedonStructures;
using CalamityMod.Walls.DraedonStructures;

namespace CalamityMod.Schematics.AutoGeneratedContent
{
	public class ResearchFacilitySchematic
	{
		[GeneratedCode("ScreenCaptureToSchematic", "1.0.2")]
		public static ColorTileMap GetMap()
		{
			var tile1 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0);
			var tile2 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 8224).UseFrame(36, 54);
			var tile3 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(0, 18);
			var tile4 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32);
			var tile5 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 16416).UseFrame(0, 72);
			var tile6 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 16, 0, 8224).UseFrame(36, 54);
			var tile7 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 16, 0, 32).UseFrame(0, 18);
			var tile8 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 16, 0, 16416).UseFrame(36, 72);
			var tile9 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(306, 72);
			var tile10 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 82, 3, 32).UseFrame(72, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 108);
			var tile11 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 0, 0);
			var tile12 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 80, 1, 32).UseFrame(72, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 0, 36);
			var tile13 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 82, 4, 32).UseFrame(72, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 144);
			var tile14 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(54, 72);
			var tile15 = new TileDefinitionStructure(TileID.ClosedDoor).UseHeaders(0, 0, 0, 32).UseFrame(0, 756);
			var tile16 = new TileDefinitionStructure(TileID.ClosedDoor).UseHeaders(0, 0, 0, 32).UseFrame(0, 774);
			var tile17 = new TileDefinitionStructure(TileID.ClosedDoor).UseHeaders(0, 0, 0, 32).UseFrame(0, 792);
			var tile18 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile19 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 18);
			var tile20 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 36);
			var tile21 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 8224).UseFrame(0, 54);
			var tile22 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(306, 72);
			var tile23 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 148, 3, 12320).UseFrame(54, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 144, 108);
			var tile24 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 36, 36);
			var tile25 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 36);
			var tile26 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 74, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 360, 36);
			var tile27 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 36);
			var tile28 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 64, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 0, 36);
			var tile29 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 64, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 0, 36);
			var tile30 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0).UseWall((ushort)WallID.SapphireGemspark, 0, 0);
			var tile31 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 103, 3, 32).UseFrame(54, 0).UseWall((ushort)WallID.SapphireGemspark, 252, 108);
			var tile32 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 18);
			var tile33 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 36);
			var tile34 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(306, 72);
			var tile35 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 288, 72);
			var tile36 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 108, 36);
			var tile37 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 288, 72);
			var tile38 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)WallID.SapphireGemspark, 72, 72);
			var tile39 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 8224).UseFrame(72, 54);
			var tile40 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 82, 3, 12320).UseFrame(54, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 108);
			var tile41 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 108, 36);
			var tile42 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 252, 36);
			var tile43 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 139, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 396, 72);
			var tile44 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 216, 36);
			var tile45 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 139, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 396, 72);
			var tile46 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 288, 36);
			var tile47 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 75, 1, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 396, 36);
			var tile48 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 66, 2, 32).UseFrame(36, 18).UseWall((ushort)WallID.SapphireGemspark, 72, 72);
			var tile49 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 0);
			var tile50 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 36);
			var tile51 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(270, 72);
			var tile52 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 36);
			var tile53 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 1, 0, 32).UseFrame(0, 540).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 36, 0);
			var tile54 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 66, 1, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 36);
			var tile55 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 36, 36);
			var tile56 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 10, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 360, 0);
			var tile57 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 131, 1, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 108, 36);
			var tile58 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 131, 2, 32).UseFrame(54, 18).UseWall((ushort)WallID.SapphireGemspark, 108, 72);
			var tile59 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 0);
			var tile60 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 0);
			var tile61 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(252, 54);
			var tile62 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 66, 3, 12320).UseFrame(18, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 108);
			var tile63 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 216, 72);
			var tile64 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 252, 72);
			var tile65 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 66, 3, 12320).UseFrame(18, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 108);
			var tile66 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 288, 36);
			var tile67 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 139, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 396, 72);
			var tile68 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 36);
			var tile69 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 136, 1, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 288, 36);
			var tile70 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 11, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 396, 0);
			var tile71 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 108, 36);
			var tile72 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 252, 36);
			var tile73 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 36);
			var tile74 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 72);
			var tile75 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 36);
			var tile76 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 108, 0);
			var tile77 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 10, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 360, 0);
			var tile78 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 138, 2, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 360, 72);
			var tile79 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 74, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 360, 36);
			var tile80 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 138, 2, 32).UseFrame(0, 216).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 360, 72);
			var tile81 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 131, 1, 32).UseFrame(0, 234).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 108, 36);
			var tile82 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 1, 2, 32).UseFrame(0, 252).UseWall((ushort)WallID.SapphireGemspark, 36, 72);
			var tile83 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 54);
			var tile84 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 0);
			var tile85 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 0);
			var tile86 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 36);
			var tile87 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 216, 72);
			var tile88 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 2, 0).UseWall((ushort)WallID.SapphireGemspark, 252, 72);
			var tile89 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 64, 1, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile90 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 0, 4, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 144);
			var tile91 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 3, 12320).UseFrame(54, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 0, 108);
			var tile92 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 216, 36);
			var tile93 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 75, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 396, 36);
			var tile94 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 131, 1, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 108, 36);
			var tile95 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 136, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 288, 36);
			var tile96 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 252, 36);
			var tile97 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 11, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 396, 0);
			var tile98 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 252, 36);
			var tile99 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 17, 2, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72);
			var tile100 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 108, 0);
			var tile101 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 74, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 360, 36);
			var tile102 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 66, 1, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 36);
			var tile103 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 66, 1, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 36);
			var tile104 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 74, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 360, 36);
			var tile105 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 10, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 360, 0);
			var tile106 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 74, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 36);
			var tile107 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 98, 2, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile108 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(270, 72);
			var tile109 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 66, 1, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 36);
			var tile110 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 71, 2, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 252, 72);
			var tile111 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 36);
			var tile112 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 252, 72);
			var tile113 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile114 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 1, 2, 32).UseFrame(18, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72);
			var tile115 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile116 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 132, 3, 12320).UseFrame(18, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 144, 108);
			var tile117 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 75, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 396, 36);
			var tile118 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 71, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 252, 36);
			var tile119 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 11, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 396, 0);
			var tile120 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)WallID.SapphireGemspark, 36, 36);
			var tile121 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 36);
			var tile122 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 2, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 72);
			var tile123 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 72);
			var tile124 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 138, 2, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 360, 72);
			var tile125 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)WallID.SapphireGemspark, 108, 36);
			var tile126 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 10, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 0);
			var tile127 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72);
			var tile128 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 0, 0, 32).UseFrame(108, 72);
			var tile129 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 36, 0);
			var tile130 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 1, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 36, 36);
			var tile131 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile132 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile133 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 66, 0, 32).UseFrame(0, 540).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 0);
			var tile134 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 139, 2, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 396, 72);
			var tile135 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 1, 8224).UseFrame(144, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 36);
			var tile136 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 288, 36);
			var tile137 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 131, 1, 32).UseWall((ushort)WallID.SapphireGemspark, 108, 36);
			var tile138 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 136, 1, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 288, 36);
			var tile139 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 66, 2, 32).UseFrame(0, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile140 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 72);
			var tile141 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 132, 3, 12320).UseFrame(18, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 144, 108);
			var tile142 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 138, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 360, 72);
			var tile143 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 1, 8224).UseFrame(144, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 108, 36);
			var tile144 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 36);
			var tile145 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 138, 2, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 360, 72);
			var tile146 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 131, 1, 32).UseFrame(18, 0).UseWall((ushort)WallID.SapphireGemspark, 108, 36);
			var tile147 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 74, 1, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 36);
			var tile148 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 66, 2, 32).UseFrame(18, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile149 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 1, 1, 32).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 36, 36);
			var tile150 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 2, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 216, 72);
			var tile151 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 36);
			var tile152 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 6, 2, 32).UseFrame(36, 0).UseWall((ushort)WallID.SapphireGemspark, 216, 72);
			var tile153 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 131, 1, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile154 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 131, 2, 32).UseFrame(36, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 72);
			var tile155 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 108, 0);
			var tile156 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 75, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 396, 36);
			var tile157 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 138, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 360, 72);
			var tile158 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 138, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 360, 72);
			var tile159 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 138, 2, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 360, 72);
			var tile160 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 138, 2, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 72);
			var tile161 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 36);
			var tile162 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 136, 2, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 288, 72);
			var tile163 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 66, 1, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 36);
			var tile164 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 108, 36);
			var tile165 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 1, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 36);
			var tile166 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 136, 2, 32).UseFrame(36, 0).UseWall((ushort)WallID.SapphireGemspark, 288, 72);
			var tile167 = new TileDefinitionStructure(TileID.Extractinator).UseHeaders(0, 66, 1, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile168 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 66, 1, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 72, 36);
			var tile169 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 6, 1, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 216, 36);
			var tile170 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 71, 1, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 252, 36);
			var tile171 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 75, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 396, 36);
			var tile172 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)WallID.SapphireGemspark, 72, 36);
			var tile173 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 10, 0, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 360, 0);
			var tile174 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 1, 1, 32).UseWall((ushort)WallID.SapphireGemspark, 36, 36);
			var tile175 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 74, 1, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 36);
			var tile176 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 131, 2, 32).UseFrame(0, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 72);
			var tile177 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 2, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 252, 72);
			var tile178 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 136, 2, 32).UseFrame(18, 0).UseWall((ushort)WallID.SapphireGemspark, 288, 72);
			var tile179 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 66, 1, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile180 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 131, 2, 32).UseFrame(18, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 72);
			var tile181 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 139, 2, 32).UseFrame(234, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 396, 72);
			var tile182 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 252, 36);
			var tile183 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 66, 1, 32).UseFrame(36, 0).UseWall((ushort)WallID.SapphireGemspark, 72, 36);
			var tile184 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 6, 1, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 36);
			var tile185 = new TileDefinitionStructure(TileID.GlassKiln).UseHeaders(0, 66, 2, 32).UseFrame(36, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile186 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 4128).UseFrame(18, 54);
			var tile187 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(288, 72);
			var tile188 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 1, 3, 16416).UseFrame(0, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 108);
			var tile189 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 1, 1, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 36);
			var tile190 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 6, 2, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 216, 72);
			var tile191 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 36);
			var tile192 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 6, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 216, 36);
			var tile193 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 10, 0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 360, 0);
			var tile194 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 138, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 72);
			var tile195 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(270, 54);
			var tile196 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 1, 3, 16416).UseFrame(0, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 36, 108);
			var tile197 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 2, 0).UseWall((ushort)WallID.SapphireGemspark, 216, 72);
			var tile198 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 1, 2, 8224).UseFrame(144, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72);
			var tile199 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 4128).UseFrame(90, 54);
			var tile200 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(252, 72);
			var tile201 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 139, 2, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 396, 72);
			var tile202 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 1, 1, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 36, 36);
			var tile203 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 288, 36);
			var tile204 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 98, 2, 32).UseFrame(72, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile205 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 72, 0);
			var tile206 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 1, 1, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 36, 36);
			var tile207 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 163, 2, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 72);
			var tile208 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 67, 3, 16416).UseFrame(0, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 108, 108);
			var tile209 = new TileDefinitionStructure(ModContent.TileType<DraedonItemCharger>()).UseHeaders(0, 131, 1, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 108, 36);
			var tile210 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 66, 2, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile211 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 4, 0, 8224).UseFrame(144, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile212 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 165, 4, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 144);
			var tile213 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 0);
			var tile214 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 74, 1, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 360, 36);
			var tile215 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 74, 1, 32).UseFrame(0, 216).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 360, 36);
			var tile216 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 1, 2, 32).UseFrame(0, 252).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 72);
			var tile217 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 54);
			var tile218 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(288, 72);
			var tile219 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 133, 3, 16416).UseFrame(0, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 108);
			var tile220 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 288, 72);
			var tile221 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 216, 72);
			var tile222 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 72);
			var tile223 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 165, 3, 16416).UseFrame(72, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 180, 108);
			var tile224 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 18);
			var tile225 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 4128).UseFrame(54, 54);
			var tile226 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(252, 72);
			var tile227 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 131, 0, 32).UseFrame(0, 540).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 108, 0);
			var tile228 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 1, 1, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 36, 36);
			var tile229 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 131, 1, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 108, 36);
			var tile230 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 138, 2, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 360, 72);
			var tile231 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 131, 1, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 108, 36);
			var tile232 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 131, 2, 32).UseFrame(36, 18).UseWall((ushort)WallID.SapphireGemspark, 108, 72);
			var tile233 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 72);
			var tile234 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 33, 3, 16416).UseFrame(72, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 36, 108);
			var tile235 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 71, 2, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 252, 72);
			var tile236 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 131, 1, 32).UseFrame(54, 18).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 108, 36);
			var tile237 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 1, 2, 32).UseFrame(54, 18).UseWall((ushort)WallID.SapphireGemspark, 36, 72);
			var tile238 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 83, 3, 16416).UseFrame(36, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 108, 108);
			var tile239 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 2, 0).UseWall((ushort)WallID.SapphireGemspark, 36, 72);
			var tile240 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 68, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 144, 36);
			var tile241 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 132, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 144, 72);
			var tile242 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 4, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 144, 0);
			var tile243 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 132, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlateBeam>(), 144, 72);
			var tile244 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 4, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatingWall>(), 144, 0);
			var tile245 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 67, 4, 0).UseWall((ushort)WallID.SapphireGemspark, 108, 144);
			var tile246 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(0, 36);
			var tile247 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(72, 72);
			var tile248 = new TileDefinitionStructure(TileID.OpenDoor).UseHeaders(0, 0, 0, 32).UseFrame(0, 756);
			var tile249 = new TileDefinitionStructure(TileID.OpenDoor).UseHeaders(0, 0, 0, 32).UseFrame(0, 774);
			var tile250 = new TileDefinitionStructure(TileID.OpenDoor).UseHeaders(0, 0, 0, 32).UseFrame(0, 792);
			var tile251 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 0);
			var tile252 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(72, 18);
			var tile253 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 12320).UseFrame(18, 72);
			var tile254 = new TileDefinitionStructure(TileID.OpenDoor).UseHeaders(0, 0, 0, 32).UseFrame(18, 756);
			var tile255 = new TileDefinitionStructure(TileID.OpenDoor).UseHeaders(0, 0, 0, 32).UseFrame(18, 774);
			var tile256 = new TileDefinitionStructure(TileID.OpenDoor).UseHeaders(0, 0, 0, 32).UseFrame(18, 792);
			var tile257 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 4128).UseFrame(90, 54);
			var tile258 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 32).UseFrame(72, 36);
			var tile259 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 16, 0, 12320).UseFrame(54, 72);
			Dictionary<Color, TileDefinitionStructure> colorTileMap = new Dictionary<Color, TileDefinitionStructure>()
			{
				{ new Color(0, 0, 0), tile1 },
				{ new Color(35, 221, 125), tile2 },
				{ new Color(112, 142, 86), tile3 },
				{ new Color(23, 118, 69), tile4 },
				{ new Color(113, 15, 65), tile5 },
				{ new Color(158, 132, 110), tile6 },
				{ new Color(195, 110, 40), tile7 },
				{ new Color(217, 59, 120), tile8 },
				{ new Color(17, 189, 14), tile9 },
				{ new Color(24, 208, 83), tile10 },
				{ new Color(105, 118, 33), tile11 },
				{ new Color(179, 158, 172), tile12 },
				{ new Color(23, 154, 161), tile13 },
				{ new Color(4, 124, 200), tile14 },
				{ new Color(42, 151, 79), tile15 },
				{ new Color(13, 153, 244), tile16 },
				{ new Color(58, 91, 39), tile17 },
				{ new Color(69, 103, 174), tile18 },
				{ new Color(252, 239, 246), tile19 },
				{ new Color(155, 17, 31), tile20 },
				{ new Color(111, 88, 189), tile21 },
				{ new Color(2, 173, 0), tile22 },
				{ new Color(36, 189, 112), tile23 },
				{ new Color(148, 134, 233), tile24 },
				{ new Color(204, 191, 242), tile25 },
				{ new Color(95, 175, 163), tile26 },
				{ new Color(41, 3, 36), tile27 },
				{ new Color(25, 221, 117), tile28 },
				{ new Color(44, 36, 14), tile29 },
				{ new Color(114, 183, 174), tile30 },
				{ new Color(181, 124, 137), tile31 },
				{ new Color(130, 148, 36), tile32 },
				{ new Color(11, 39, 233), tile33 },
				{ new Color(79, 233, 220), tile34 },
				{ new Color(132, 166, 213), tile35 },
				{ new Color(62, 121, 168), tile36 },
				{ new Color(188, 156, 64), tile37 },
				{ new Color(83, 114, 13), tile38 },
				{ new Color(251, 86, 122), tile39 },
				{ new Color(72, 214, 137), tile40 },
				{ new Color(241, 177, 5), tile41 },
				{ new Color(194, 222, 9), tile42 },
				{ new Color(95, 73, 42), tile43 },
				{ new Color(205, 84, 136), tile44 },
				{ new Color(185, 217, 26), tile45 },
				{ new Color(71, 149, 55), tile46 },
				{ new Color(160, 238, 171), tile47 },
				{ new Color(102, 182, 27), tile48 },
				{ new Color(110, 98, 10), tile49 },
				{ new Color(123, 135, 62), tile50 },
				{ new Color(170, 195, 81), tile51 },
				{ new Color(96, 94, 55), tile52 },
				{ new Color(214, 193, 199), tile53 },
				{ new Color(203, 222, 47), tile54 },
				{ new Color(125, 238, 71), tile55 },
				{ new Color(183, 153, 152), tile56 },
				{ new Color(243, 179, 193), tile57 },
				{ new Color(66, 167, 232), tile58 },
				{ new Color(222, 138, 251), tile59 },
				{ new Color(234, 83, 123), tile60 },
				{ new Color(255, 228, 194), tile61 },
				{ new Color(236, 35, 145), tile62 },
				{ new Color(55, 89, 123), tile63 },
				{ new Color(226, 112, 211), tile64 },
				{ new Color(111, 212, 15), tile65 },
				{ new Color(123, 233, 199), tile66 },
				{ new Color(211, 182, 201), tile67 },
				{ new Color(113, 135, 212), tile68 },
				{ new Color(125, 103, 27), tile69 },
				{ new Color(105, 130, 211), tile70 },
				{ new Color(59, 236, 110), tile71 },
				{ new Color(76, 203, 249), tile72 },
				{ new Color(108, 145, 203), tile73 },
				{ new Color(182, 128, 63), tile74 },
				{ new Color(29, 16, 66), tile75 },
				{ new Color(237, 210, 211), tile76 },
				{ new Color(216, 98, 161), tile77 },
				{ new Color(52, 22, 156), tile78 },
				{ new Color(178, 142, 92), tile79 },
				{ new Color(237, 110, 187), tile80 },
				{ new Color(117, 206, 214), tile81 },
				{ new Color(168, 167, 131), tile82 },
				{ new Color(101, 35, 8), tile83 },
				{ new Color(22, 14, 87), tile84 },
				{ new Color(252, 29, 54), tile85 },
				{ new Color(137, 84, 119), tile86 },
				{ new Color(145, 143, 148), tile87 },
				{ new Color(72, 144, 32), tile88 },
				{ new Color(50, 6, 214), tile89 },
				{ new Color(209, 154, 61), tile90 },
				{ new Color(157, 127, 34), tile91 },
				{ new Color(15, 64, 178), tile92 },
				{ new Color(105, 116, 104), tile93 },
				{ new Color(190, 136, 175), tile94 },
				{ new Color(202, 193, 83), tile95 },
				{ new Color(73, 56, 249), tile96 },
				{ new Color(102, 40, 57), tile97 },
				{ new Color(229, 91, 223), tile98 },
				{ new Color(39, 45, 61), tile99 },
				{ new Color(182, 118, 160), tile100 },
				{ new Color(173, 147, 137), tile101 },
				{ new Color(202, 121, 143), tile102 },
				{ new Color(53, 236, 220), tile103 },
				{ new Color(131, 32, 223), tile104 },
				{ new Color(14, 210, 6), tile105 },
				{ new Color(229, 126, 207), tile106 },
				{ new Color(205, 232, 206), tile107 },
				{ new Color(221, 106, 113), tile108 },
				{ new Color(4, 183, 35), tile109 },
				{ new Color(67, 232, 18), tile110 },
				{ new Color(117, 179, 254), tile111 },
				{ new Color(200, 17, 244), tile112 },
				{ new Color(37, 255, 72), tile113 },
				{ new Color(195, 20, 75), tile114 },
				{ new Color(28, 227, 7), tile115 },
				{ new Color(89, 214, 137), tile116 },
				{ new Color(216, 65, 175), tile117 },
				{ new Color(110, 232, 141), tile118 },
				{ new Color(210, 208, 41), tile119 },
				{ new Color(23, 198, 193), tile120 },
				{ new Color(108, 241, 4), tile121 },
				{ new Color(201, 14, 109), tile122 },
				{ new Color(224, 70, 193), tile123 },
				{ new Color(17, 191, 126), tile124 },
				{ new Color(134, 10, 212), tile125 },
				{ new Color(130, 192, 134), tile126 },
				{ new Color(106, 170, 225), tile127 },
				{ new Color(154, 107, 166), tile128 },
				{ new Color(99, 7, 202), tile129 },
				{ new Color(113, 245, 65), tile130 },
				{ new Color(203, 14, 56), tile131 },
				{ new Color(135, 86, 34), tile132 },
				{ new Color(70, 83, 213), tile133 },
				{ new Color(154, 120, 144), tile134 },
				{ new Color(199, 198, 129), tile135 },
				{ new Color(48, 231, 222), tile136 },
				{ new Color(185, 79, 16), tile137 },
				{ new Color(162, 173, 28), tile138 },
				{ new Color(224, 210, 133), tile139 },
				{ new Color(94, 102, 6), tile140 },
				{ new Color(163, 111, 80), tile141 },
				{ new Color(128, 70, 177), tile142 },
				{ new Color(70, 255, 179), tile143 },
				{ new Color(177, 59, 109), tile144 },
				{ new Color(177, 208, 49), tile145 },
				{ new Color(80, 210, 165), tile146 },
				{ new Color(36, 50, 31), tile147 },
				{ new Color(235, 183, 165), tile148 },
				{ new Color(48, 40, 97), tile149 },
				{ new Color(28, 167, 132), tile150 },
				{ new Color(156, 232, 236), tile151 },
				{ new Color(206, 247, 9), tile152 },
				{ new Color(64, 71, 127), tile153 },
				{ new Color(208, 234, 232), tile154 },
				{ new Color(43, 8, 20), tile155 },
				{ new Color(163, 240, 221), tile156 },
				{ new Color(235, 143, 255), tile157 },
				{ new Color(224, 57, 52), tile158 },
				{ new Color(230, 183, 184), tile159 },
				{ new Color(170, 79, 29), tile160 },
				{ new Color(79, 41, 88), tile161 },
				{ new Color(47, 20, 82), tile162 },
				{ new Color(128, 227, 216), tile163 },
				{ new Color(40, 15, 139), tile164 },
				{ new Color(37, 84, 71), tile165 },
				{ new Color(55, 192, 175), tile166 },
				{ new Color(145, 141, 56), tile167 },
				{ new Color(132, 49, 23), tile168 },
				{ new Color(132, 188, 175), tile169 },
				{ new Color(184, 231, 63), tile170 },
				{ new Color(80, 149, 247), tile171 },
				{ new Color(98, 128, 192), tile172 },
				{ new Color(144, 252, 243), tile173 },
				{ new Color(193, 34, 13), tile174 },
				{ new Color(4, 194, 127), tile175 },
				{ new Color(116, 187, 228), tile176 },
				{ new Color(236, 175, 246), tile177 },
				{ new Color(8, 24, 193), tile178 },
				{ new Color(229, 203, 248), tile179 },
				{ new Color(65, 170, 88), tile180 },
				{ new Color(162, 199, 251), tile181 },
				{ new Color(153, 215, 122), tile182 },
				{ new Color(148, 195, 211), tile183 },
				{ new Color(134, 166, 196), tile184 },
				{ new Color(187, 208, 106), tile185 },
				{ new Color(42, 128, 110), tile186 },
				{ new Color(151, 16, 1), tile187 },
				{ new Color(203, 203, 55), tile188 },
				{ new Color(73, 72, 124), tile189 },
				{ new Color(53, 124, 181), tile190 },
				{ new Color(199, 79, 81), tile191 },
				{ new Color(155, 30, 90), tile192 },
				{ new Color(18, 107, 235), tile193 },
				{ new Color(5, 223, 247), tile194 },
				{ new Color(17, 101, 9), tile195 },
				{ new Color(49, 76, 72), tile196 },
				{ new Color(86, 187, 75), tile197 },
				{ new Color(138, 169, 154), tile198 },
				{ new Color(86, 215, 251), tile199 },
				{ new Color(195, 79, 143), tile200 },
				{ new Color(253, 94, 70), tile201 },
				{ new Color(30, 191, 87), tile202 },
				{ new Color(115, 32, 177), tile203 },
				{ new Color(16, 24, 21), tile204 },
				{ new Color(131, 145, 48), tile205 },
				{ new Color(9, 186, 102), tile206 },
				{ new Color(46, 23, 251), tile207 },
				{ new Color(52, 222, 193), tile208 },
				{ new Color(106, 61, 165), tile209 },
				{ new Color(183, 68, 70), tile210 },
				{ new Color(94, 78, 27), tile211 },
				{ new Color(91, 8, 129), tile212 },
				{ new Color(177, 242, 166), tile213 },
				{ new Color(177, 190, 44), tile214 },
				{ new Color(151, 70, 162), tile215 },
				{ new Color(53, 7, 24), tile216 },
				{ new Color(105, 77, 29), tile217 },
				{ new Color(149, 149, 56), tile218 },
				{ new Color(148, 201, 128), tile219 },
				{ new Color(132, 180, 129), tile220 },
				{ new Color(177, 188, 219), tile221 },
				{ new Color(106, 177, 201), tile222 },
				{ new Color(249, 39, 136), tile223 },
				{ new Color(175, 88, 199), tile224 },
				{ new Color(192, 124, 88), tile225 },
				{ new Color(207, 156, 151), tile226 },
				{ new Color(30, 52, 54), tile227 },
				{ new Color(140, 77, 247), tile228 },
				{ new Color(41, 201, 185), tile229 },
				{ new Color(227, 199, 63), tile230 },
				{ new Color(1, 44, 62), tile231 },
				{ new Color(36, 0, 2), tile232 },
				{ new Color(80, 45, 149), tile233 },
				{ new Color(217, 60, 224), tile234 },
				{ new Color(144, 186, 245), tile235 },
				{ new Color(86, 213, 24), tile236 },
				{ new Color(223, 196, 44), tile237 },
				{ new Color(232, 102, 127), tile238 },
				{ new Color(75, 36, 110), tile239 },
				{ new Color(228, 65, 232), tile240 },
				{ new Color(16, 22, 95), tile241 },
				{ new Color(72, 173, 43), tile242 },
				{ new Color(136, 155, 124), tile243 },
				{ new Color(85, 126, 111), tile244 },
				{ new Color(2, 69, 248), tile245 },
				{ new Color(86, 252, 146), tile246 },
				{ new Color(2, 210, 243), tile247 },
				{ new Color(160, 3, 2), tile248 },
				{ new Color(19, 25, 198), tile249 },
				{ new Color(191, 217, 219), tile250 },
				{ new Color(147, 107, 235), tile251 },
				{ new Color(173, 200, 37), tile252 },
				{ new Color(128, 71, 13), tile253 },
				{ new Color(201, 206, 58), tile254 },
				{ new Color(155, 137, 70), tile255 },
				{ new Color(188, 229, 32), tile256 },
				{ new Color(135, 245, 40), tile257 },
				{ new Color(220, 226, 110), tile258 },
				{ new Color(244, 111, 18), tile259 },
			};
			return new ColorTileMap(colorTileMap);
		}
	}
}
