using CalamityMod.Tiles;
using CalamityMod.Tiles.FurniturePlaguedPlate;
using CalamityMod.Tiles.FurnitureStratus;
using CalamityMod.Tiles.Furniture.CraftingStations;
using CalamityMod.Walls;
using Microsoft.Xna.Framework;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Terraria.ID;
using Terraria.ModLoader;

namespace CalamityMod.Schematics.AutoGeneratedContent
{
    public class ResearchFacilitySchematic
	{
		[GeneratedCode("ScreenCaptureToSchematic", "1.0.1")]
		public static ColorTileMap GetMap()
		{
			var tile1 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0);
			var tile2 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 54).UseSlope(2).UseHeaders(0, 16, 0, 8224);
			var tile3 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 18).UseHeaders(0, 16, 0, 32);
			var tile4 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseHeaders(0, 0, 0, 32);
			var tile5 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 72).UseSlope(4).UseHeaders(0, 0, 0, 16416);
			var tile6 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 72).UseSlope(4).UseHeaders(0, 32, 0, 16416);
			var tile7 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 54).UseSlope(2).UseHeaders(0, 32, 0, 8224);
			var tile8 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 18).UseHeaders(0, 32, 0, 32);
			var tile9 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 0).UseHeaders(0, 0, 0, 32);
			var tile10 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 18).UseHeaders(0, 16, 0, 32);
			var tile11 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(72, 36).UseHeaders(0, 32, 0, 32);
			var tile12 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 72).UseHeaders(0, 16, 0, 32);
			var tile13 = new TileDefinitionStructure(TileID.OpenDoor).UseFrame(0, 1080).UseHeaders(0, 0, 0, 32);
			var tile14 = new TileDefinitionStructure(TileID.OpenDoor).UseFrame(0, 1098).UseHeaders(0, 0, 0, 32);
			var tile15 = new TileDefinitionStructure(TileID.OpenDoor).UseFrame(0, 1116).UseHeaders(0, 0, 0, 32);
			var tile16 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 0).UseHeaders(0, 16, 0, 32);
			var tile17 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 18).UseHeaders(0, 16, 0, 32);
			var tile18 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 36).UseHeaders(0, 0, 0, 32);
			var tile19 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile20 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(90, 72).UseSlope(3).UseHeaders(0, 32, 0, 12320);
			var tile21 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 0, 108).UseHeaders(0, 0, 3, 0);
			var tile22 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 0, 36).UseHeaders(0, 64, 1, 0);
			var tile23 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 36).UseHeaders(0, 64, 1, 0);
			var tile24 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 0).UseHeaders(0, 0, 0, 0);
			var tile25 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 72).UseHeaders(0, 128, 2, 0);
			var tile26 = new TileDefinitionStructure(TileID.OpenDoor).UseWall(WallID.MartianConduit, 0, 36).UseFrame(18, 1080).UseHeaders(0, 64, 1, 32);
			var tile27 = new TileDefinitionStructure(TileID.OpenDoor).UseWall(WallID.MartianConduit, 0, 0).UseFrame(18, 1098).UseHeaders(0, 0, 0, 32);
			var tile28 = new TileDefinitionStructure(TileID.OpenDoor).UseWall(WallID.SapphireGemspark, 0, 72).UseFrame(18, 1116).UseHeaders(0, 128, 2, 32);
			var tile29 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 144, 144).UseFrame(36, 0).UseHeaders(0, 148, 4, 32);
			var tile30 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 36).UseHeaders(0, 16, 0, 32);
			var tile31 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 72).UseSlope(3).UseHeaders(0, 0, 0, 12320);
			var tile32 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 72, 108).UseHeaders(0, 66, 3, 0);
			var tile33 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 216, 72).UseHeaders(0, 6, 2, 0);
			var tile34 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 72, 36).UseHeaders(0, 66, 1, 0);
			var tile35 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseHeaders(0, 131, 1, 0);
			var tile36 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 72).UseHeaders(0, 6, 2, 0);
			var tile37 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 36, 36).UseHeaders(0, 1, 1, 0);
			var tile38 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 108, 36).UseHeaders(0, 131, 1, 0);
			var tile39 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(36, 0).UseHeaders(0, 17, 2, 32);
			var tile40 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 54).UseSlope(2).UseHeaders(0, 0, 0, 8224);
			var tile41 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 396, 36).UseHeaders(0, 75, 1, 0);
			var tile42 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 252, 36).UseHeaders(0, 71, 1, 0);
			var tile43 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 0).UseHeaders(0, 11, 0, 0);
			var tile44 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseHeaders(0, 1, 1, 0);
			var tile45 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 36).UseHeaders(0, 71, 1, 0);
			var tile46 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 396, 72).UseHeaders(0, 139, 2, 0);
			var tile47 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 108, 36).UseHeaders(0, 131, 1, 0);
			var tile48 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 216, 36).UseHeaders(0, 6, 1, 0);
			var tile49 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(18, 0).UseHeaders(0, 66, 2, 32);
			var tile50 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 0).UseHeaders(0, 32, 0, 32);
			var tile51 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 0, 108).UseHeaders(0, 0, 3, 32);
			var tile52 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 360, 36).UseFrame(0, 18).UseHeaders(0, 74, 1, 32);
			var tile53 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 360, 36).UseHeaders(0, 74, 1, 0);
			var tile54 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseHeaders(0, 66, 1, 0);
			var tile55 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 36).UseHeaders(0, 74, 1, 0);
			var tile56 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 108, 36).UseHeaders(0, 131, 1, 32);
			var tile57 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 72, 36).UseFrame(0, 18).UseHeaders(0, 66, 1, 32);
			var tile58 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.SapphireGemspark, 360, 0).UseFrame(0, 36).UseHeaders(0, 10, 0, 32);
			var tile59 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 36).UseFrame(54, 0).UseHeaders(0, 98, 1, 32);
			var tile60 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 288, 108).UseFrame(18, 18).UseHeaders(0, 136, 3, 32);
			var tile61 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 36).UseHeaders(0, 32, 0, 32);
			var tile62 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 36, 0).UseHeaders(0, 1, 0, 0);
			var tile63 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 72).UseHeaders(0, 136, 2, 0);
			var tile64 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 108, 36).UseFrame(18, 0).UseHeaders(0, 131, 1, 32);
			var tile65 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 216, 72).UseFrame(18, 18).UseHeaders(0, 6, 2, 32);
			var tile66 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.SapphireGemspark, 72, 36).UseFrame(18, 36).UseHeaders(0, 66, 1, 32);
			var tile67 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(18, 0).UseHeaders(0, 1, 2, 32);
			var tile68 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile69 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 144, 108).UseHeaders(0, 132, 3, 0);
			var tile70 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 72).UseFrame(36, 252).UseHeaders(0, 139, 2, 32);
			var tile71 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 288, 36).UseHeaders(0, 136, 1, 0);
			var tile72 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 36).UseHeaders(0, 136, 1, 0);
			var tile73 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 396, 36).UseFrame(36, 0).UseHeaders(0, 75, 1, 32);
			var tile74 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.MartianConduit, 72, 36).UseFrame(36, 18).UseHeaders(0, 66, 1, 32);
			var tile75 = new TileDefinitionStructure(ModContent.TileType<VoidCondenser>()).UseWall(WallID.SapphireGemspark, 216, 36).UseFrame(36, 36).UseHeaders(0, 6, 1, 32);
			var tile76 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(36, 0).UseHeaders(0, 82, 2, 32);
			var tile77 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 72).UseSlope(3).UseHeaders(0, 16, 0, 12320);
			var tile78 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 72).UseHeaders(0, 138, 2, 0);
			var tile79 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(0, 252).UseHeaders(0, 1, 1, 32);
			var tile80 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 360, 72).UseHeaders(0, 138, 2, 0);
			var tile81 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(18, 54).UseHeaders(0, 1, 2, 32);
			var tile82 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 216, 0).UseHeaders(0, 6, 0, 32);
			var tile83 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 36, 36).UseFrame(0, 18).UseHeaders(0, 1, 1, 32);
			var tile84 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(0, 252).UseHeaders(0, 66, 1, 32);
			var tile85 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 288, 72).UseHeaders(0, 136, 2, 0);
			var tile86 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 72).UseHeaders(0, 71, 2, 0);
			var tile87 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(180, 252).UseSlope(1).UseHeaders(0, 1, 2, 4128);
			var tile88 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 0).UseFrame(18, 18).UseHeaders(0, 136, 0, 32);
			var tile89 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 144, 144).UseFrame(18, 72).UseSlope(3).UseHeaders(0, 132, 4, 12320);
			var tile90 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseHeaders(0, 0, 0, 32);
			var tile91 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall(WallID.MartianConduit, 108, 0).UseFrame(0, 18).UseHeaders(0, 131, 0, 32);
			var tile92 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(0, 36).UseHeaders(0, 1, 1, 32);
			var tile93 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 36).UseFrame(0, 54).UseHeaders(0, 136, 1, 32);
			var tile94 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 0).UseFrame(0, 252).UseHeaders(0, 11, 0, 32);
			var tile95 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 36).UseHeaders(0, 6, 1, 0);
			var tile96 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 396, 0).UseHeaders(0, 11, 0, 0);
			var tile97 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 0, 144).UseFrame(36, 0).UseHeaders(0, 16, 4, 32);
			var tile98 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 0).UseHeaders(0, 1, 0, 0);
			var tile99 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 72).UseFrame(18, 0).UseHeaders(0, 128, 2, 32);
			var tile100 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(18, 18).UseHeaders(0, 1, 1, 32);
			var tile101 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(18, 36).UseHeaders(0, 66, 1, 32);
			var tile102 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 36).UseFrame(18, 54).UseHeaders(0, 74, 1, 32);
			var tile103 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(0, 252).UseHeaders(0, 131, 1, 32);
			var tile104 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlate>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(180, 54).UseHeaders(0, 82, 1, 32);
			var tile105 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 36).UseHeaders(0, 74, 1, 32);
			var tile106 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 108, 36).UseFrame(0, 18).UseHeaders(0, 131, 1, 32);
			var tile107 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 360, 0).UseHeaders(0, 10, 0, 0);
			var tile108 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 0).UseHeaders(0, 66, 0, 0);
			var tile109 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(36, 0).UseHeaders(0, 1, 1, 32);
			var tile110 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(36, 18).UseHeaders(0, 131, 1, 32);
			var tile111 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 72).UseFrame(36, 36).UseHeaders(0, 71, 2, 32);
			var tile112 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(36, 54).UseHeaders(0, 131, 1, 32);
			var tile113 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 72, 36).UseHeaders(0, 66, 1, 0);
			var tile114 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(54, 0).UseHeaders(0, 163, 2, 32);
			var tile115 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 72).UseFrame(0, 252).UseHeaders(0, 139, 2, 32);
			var tile116 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 216, 36).UseHeaders(0, 6, 1, 0);
			var tile117 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(54, 0).UseHeaders(0, 163, 2, 1056);
			var tile118 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 0).UseHeaders(0, 10, 0, 0);
			var tile119 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 360, 72).UseHeaders(0, 138, 2, 0);
			var tile120 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 252, 72).UseHeaders(0, 71, 2, 0);
			var tile121 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(144, 252).UseSlope(2).UseHeaders(0, 131, 1, 8224);
			var tile122 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 180, 144).UseFrame(54, 0).UseHeaders(0, 165, 4, 1056);
			var tile123 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 72, 0).UseHeaders(0, 66, 0, 32);
			var tile124 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.Glass, 36, 36).UseFrame(0, 18).UseHeaders(0, 1, 1, 32);
			var tile125 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 252, 36).UseHeaders(0, 71, 1, 0);
			var tile126 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 36).UseHeaders(0, 75, 1, 0);
			var tile127 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 36, 36).UseFrame(144, 252).UseSlope(2).UseHeaders(0, 1, 1, 8224);
			var tile128 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 288, 36).UseHeaders(0, 136, 1, 0);
			var tile129 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 396, 0).UseHeaders(0, 11, 0, 0);
			var tile130 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 108, 36).UseHeaders(0, 131, 1, 0);
			var tile131 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseHeaders(0, 66, 1, 32);
			var tile132 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 36).UseFrame(0, 18).UseHeaders(0, 6, 1, 32);
			var tile133 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 72).UseFrame(0, 36).UseHeaders(0, 131, 2, 32);
			var tile134 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 36, 36).UseHeaders(0, 1, 1, 0);
			var tile135 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall(WallID.Glass, 360, 72).UseHeaders(0, 138, 2, 32);
			var tile136 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(0, 18).UseHeaders(0, 66, 1, 32);
			var tile137 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 108, 36).UseFrame(216, 252).UseHeaders(0, 131, 1, 32);
			var tile138 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 360, 72).UseHeaders(0, 138, 2, 0);
			var tile139 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 360, 36).UseHeaders(0, 74, 1, 0);
			var tile140 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(18, 0).UseHeaders(0, 131, 1, 32);
			var tile141 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 0).UseFrame(18, 18).UseHeaders(0, 10, 0, 32);
			var tile142 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 72).UseFrame(18, 36).UseHeaders(0, 131, 2, 32);
			var tile143 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 216, 72).UseHeaders(0, 6, 2, 0);
			var tile144 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall(WallID.Glass, 108, 36).UseFrame(18, 0).UseHeaders(0, 131, 1, 32);
			var tile145 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(18, 18).UseHeaders(0, 131, 1, 32);
			var tile146 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 216, 72).UseFrame(0, 252).UseHeaders(0, 6, 2, 32);
			var tile147 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 72, 36).UseHeaders(0, 66, 1, 0);
			var tile148 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 288, 72).UseHeaders(0, 136, 2, 0);
			var tile149 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 72).UseFrame(36, 0).UseHeaders(0, 136, 2, 32);
			var tile150 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(36, 18).UseHeaders(0, 131, 1, 32);
			var tile151 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 72).UseFrame(36, 36).UseHeaders(0, 131, 2, 32);
			var tile152 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 72, 0).UseHeaders(0, 66, 0, 0);
			var tile153 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall(WallID.Glass, 288, 36).UseFrame(36, 0).UseHeaders(0, 136, 1, 32);
			var tile154 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 36).UseFrame(36, 18).UseHeaders(0, 75, 1, 32);
			var tile155 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 36, 36).UseFrame(0, 252).UseHeaders(0, 1, 1, 32);
			var tile156 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 216, 36).UseHeaders(0, 6, 1, 0);
			var tile157 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 396, 0).UseHeaders(0, 11, 0, 0);
			var tile158 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 288, 108).UseFrame(18, 0).UseHeaders(0, 136, 3, 1056);
			var tile159 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 360, 0).UseHeaders(0, 10, 0, 0);
			var tile160 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 108, 36).UseFrame(36, 252).UseHeaders(0, 131, 1, 32);
			var tile161 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseHeaders(0, 131, 1, 32);
			var tile162 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(0, 18).UseHeaders(0, 131, 1, 32);
			var tile163 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 144, 0).UseFrame(0, 36).UseHeaders(0, 4, 0, 32);
			var tile164 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 72).UseFrame(0, 54).UseHeaders(0, 131, 2, 32);
			var tile165 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 252, 72).UseHeaders(0, 71, 2, 0);
			var tile166 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseWall(WallID.Glass, 108, 36).UseHeaders(0, 131, 1, 32);
			var tile167 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(0, 18).UseHeaders(0, 131, 1, 32);
			var tile168 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 288, 72).UseFrame(0, 252).UseHeaders(0, 136, 2, 32);
			var tile169 = new TileDefinitionStructure(ModContent.TileType<DraedonFactoryFieldGenerator>()).UseWall(WallID.Glass, 72, 36).UseHeaders(0, 66, 1, 32);
			var tile170 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(18, 0).UseHeaders(0, 66, 1, 32);
			var tile171 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 72).UseFrame(18, 18).UseHeaders(0, 1, 2, 32);
			var tile172 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseFrame(18, 36).UseHeaders(0, 0, 0, 32);
			var tile173 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 144).UseFrame(18, 54).UseHeaders(0, 136, 4, 32);
			var tile174 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseWall(WallID.Glass, 216, 36).UseFrame(18, 0).UseHeaders(0, 6, 1, 32);
			var tile175 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 72).UseFrame(18, 18).UseHeaders(0, 139, 2, 32);
			var tile176 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 396, 36).UseFrame(0, 252).UseHeaders(0, 75, 1, 32);
			var tile177 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 72).UseHeaders(0, 139, 2, 0);
			var tile178 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 36).UseFrame(36, 0).UseHeaders(0, 75, 1, 32);
			var tile179 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(36, 18).UseHeaders(0, 66, 1, 32);
			var tile180 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 0, 36).UseFrame(36, 36).UseHeaders(0, 64, 1, 32);
			var tile181 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 72).UseFrame(36, 54).UseHeaders(0, 131, 2, 32);
			var tile182 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 108, 0).UseHeaders(0, 131, 0, 0);
			var tile183 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(-1, -1).UseHeaders(0, 1, 1, 0);
			var tile184 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 72, 36).UseFrame(0, 252).UseHeaders(0, 66, 1, 32);
			var tile185 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 72, 36).UseFrame(18, 252).UseHeaders(0, 66, 1, 32);
			var tile186 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 216, 108).UseFrame(18, 0).UseHeaders(0, 6, 3, 1056);
			var tile187 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall(WallID.Glass, 72, 36).UseHeaders(0, 66, 1, 32);
			var tile188 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(0, 18).UseHeaders(0, 131, 1, 32);
			var tile189 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 72).UseFrame(0, 18).UseHeaders(0, 6, 2, 32);
			var tile190 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 72).UseFrame(0, 54).UseHeaders(0, 66, 2, 32);
			var tile191 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 36, 108).UseHeaders(0, 1, 3, 0);
			var tile192 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall(WallID.Glass, 288, 36).UseFrame(18, 0).UseHeaders(0, 136, 1, 32);
			var tile193 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 36).UseFrame(18, 18).UseHeaders(0, 75, 1, 32);
			var tile194 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 108, 36).UseFrame(0, 252).UseHeaders(0, 131, 1, 32);
			var tile195 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.Glass, 396, 36).UseHeaders(0, 75, 1, 0);
			var tile196 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall(WallID.MartianConduit, 396, 0).UseFrame(18, 0).UseHeaders(0, 11, 0, 32);
			var tile197 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall(WallID.MartianConduit, 72, 36).UseFrame(18, 18).UseHeaders(0, 66, 1, 32);
			var tile198 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 36).UseFrame(18, 36).UseHeaders(0, 71, 1, 32);
			var tile199 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 72).UseFrame(18, 54).UseHeaders(0, 66, 2, 32);
			var tile200 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(90, 54).UseSlope(1).UseHeaders(0, 32, 0, 4128);
			var tile201 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall(WallID.Glass, 360, 72).UseFrame(36, 0).UseHeaders(0, 138, 2, 32);
			var tile202 = new TileDefinitionStructure(ModContent.TileType<DraedonTurretTile>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(36, 18).UseHeaders(0, 1, 1, 32);
			var tile203 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 36, 36).UseFrame(234, 252).UseHeaders(0, 1, 1, 32);
			var tile204 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(36, 0).UseHeaders(0, 66, 1, 32);
			var tile205 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBed>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 72).UseFrame(36, 36).UseHeaders(0, 138, 2, 32);
			var tile206 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 36, 0).UseHeaders(0, 1, 0, 32);
			var tile207 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.Glass, 216, 72).UseFrame(0, 18).UseHeaders(0, 6, 2, 32);
			var tile208 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.Glass, 252, 72).UseFrame(180, 252).UseSlope(1).UseHeaders(0, 71, 2, 4128);
			var tile209 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 0, 144).UseFrame(36, 0).UseHeaders(0, 16, 4, 1056);
			var tile210 = new TileDefinitionStructure(TileID.Platforms).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 288, 36).UseFrame(180, 252).UseSlope(1).UseHeaders(0, 136, 1, 4128);
			var tile211 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.MartianConduit, 72, 36).UseFrame(0, 252).UseHeaders(0, 66, 1, 32);
			var tile212 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(54, 0).UseHeaders(0, 33, 2, 1056);
			var tile213 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(54, 54).UseSlope(1).UseHeaders(0, 16, 0, 4128);
			var tile214 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(36, 72).UseSlope(4).UseHeaders(0, 16, 0, 16416);
			var tile215 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.MartianConduit, 36, 36).UseFrame(0, 252).UseHeaders(0, 1, 1, 32);
			var tile216 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 36, 36).UseHeaders(0, 1, 1, 0);
			var tile217 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 72, 72).UseFrame(54, 0).UseHeaders(0, 98, 2, 1056);
			var tile218 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 396, 36).UseHeaders(0, 75, 1, 32);
			var tile219 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(0, 18).UseHeaders(0, 1, 1, 32);
			var tile220 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 252, 36).UseFrame(0, 36).UseHeaders(0, 71, 1, 32);
			var tile221 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 0).UseHeaders(0, 131, 0, 0);
			var tile222 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(18, 0).UseHeaders(0, 1, 1, 32);
			var tile223 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(18, 18).UseHeaders(0, 1, 1, 32);
			var tile224 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 0).UseFrame(18, 36).UseHeaders(0, 10, 0, 32);
			var tile225 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlate>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(162, 54).UseHeaders(0, 131, 1, 32);
			var tile226 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 72, 36).UseFrame(0, 18).UseHeaders(0, 66, 1, 32);
			var tile227 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(18, 54).UseSlope(1).UseHeaders(0, 0, 0, 4128);
			var tile228 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 108).UseFrame(0, 72).UseSlope(4).UseHeaders(0, 67, 3, 16416);
			var tile229 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 72, 36).UseFrame(36, 0).UseHeaders(0, 66, 1, 32);
			var tile230 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 216, 72).UseFrame(36, 18).UseHeaders(0, 6, 2, 32);
			var tile231 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateBasin>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 108, 36).UseFrame(36, 36).UseHeaders(0, 131, 1, 32);
			var tile232 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(54, 0).UseHeaders(0, 33, 2, 32);
			var tile233 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 36, 108).UseHeaders(0, 1, 3, 32);
			var tile234 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 396, 72).UseFrame(0, 18).UseHeaders(0, 139, 2, 32);
			var tile235 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.MartianConduit, 396, 72).UseFrame(0, 252).UseHeaders(0, 139, 2, 32);
			var tile236 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 252, 36).UseHeaders(0, 71, 1, 0);
			var tile237 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.SapphireGemspark, 396, 36).UseFrame(144, 252).UseSlope(2).UseHeaders(0, 75, 1, 8224);
			var tile238 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 180, 144).UseFrame(54, 0).UseHeaders(0, 165, 4, 32);
			var tile239 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.MartianConduit, 72, 36).UseFrame(18, 252).UseHeaders(0, 66, 1, 32);
			var tile240 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 36, 72).UseFrame(0, 54).UseHeaders(0, 1, 2, 32);
			var tile241 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 180, 108).UseHeaders(0, 133, 3, 0);
			var tile242 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(18, 0).UseHeaders(0, 131, 2, 32);
			var tile243 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 108, 108).UseHeaders(0, 67, 3, 32);
			var tile244 = new TileDefinitionStructure(ModContent.TileType<StratusLantern>()).UseWall(WallID.MartianConduit, 360, 0).UseFrame(0, 18).UseHeaders(0, 10, 0, 32);
			var tile245 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 360, 72).UseHeaders(0, 138, 2, 32);
			var tile246 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.MartianConduit, 72, 36).UseFrame(0, 18).UseHeaders(0, 66, 1, 32);
			var tile247 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.MartianConduit, 72, 36).UseFrame(0, 36).UseHeaders(0, 66, 1, 32);
			var tile248 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.SapphireGemspark, 360, 0).UseFrame(0, 54).UseHeaders(0, 10, 0, 32);
			var tile249 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 36, 36).UseFrame(18, 0).UseHeaders(0, 1, 1, 32);
			var tile250 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.MartianConduit, 36, 36).UseFrame(18, 18).UseHeaders(0, 1, 1, 32);
			var tile251 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.MartianConduit, 252, 72).UseFrame(18, 36).UseHeaders(0, 71, 2, 32);
			var tile252 = new TileDefinitionStructure(ModContent.TileType<PlagueInfuser>()).UseWall(WallID.SapphireGemspark, 108, 36).UseFrame(18, 54).UseHeaders(0, 131, 1, 32);
			var tile253 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 108, 108).UseHeaders(0, 67, 3, 0);
			var tile254 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 72).UseFrame(36, 0).UseHeaders(0, 147, 2, 32);
			var tile255 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 144, 36).UseHeaders(0, 68, 1, 0);
			var tile256 = new TileDefinitionStructure(TileID.Dirt, false).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 144, 0).UseHeaders(0, 4, 0, 0);
			var tile257 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.MartianConduit, 144, 0).UseHeaders(0, 4, 0, 0);
			var tile258 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.SapphireGemspark, 144, 36).UseHeaders(0, 68, 1, 0);
			var tile259 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall(WallID.SapphireGemspark, 108, 144).UseFrame(36, 0).UseHeaders(0, 83, 4, 32);
			var tile260 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseWall((ushort)ModContent.WallType<PlaguedPlateWall>(), 432, 0).UseFrame(0, 18).UseHeaders(0, 28, 0, 32);
			var tile261 = new TileDefinitionStructure(TileID.MartianConduitPlating).UseFrame(0, 72).UseHeaders(0, 0, 0, 32);
			var tile262 = new TileDefinitionStructure(TileID.ClosedDoor).UseFrame(0, 1080).UseHeaders(0, 0, 0, 32);
			var tile263 = new TileDefinitionStructure(TileID.ClosedDoor).UseFrame(0, 1098).UseHeaders(0, 0, 0, 32);
			var tile264 = new TileDefinitionStructure(TileID.ClosedDoor).UseFrame(0, 1116).UseHeaders(0, 0, 0, 32);
			Dictionary<Color, TileDefinitionStructure> colorTileMap = new Dictionary<Color, TileDefinitionStructure>()
			{
				{ new Color(255, 255, 255), tile1},
				{ new Color(24, 40, 82), tile2},
				{ new Color(112, 140, 156), tile3},
				{ new Color(51, 229, 115), tile4},
				{ new Color(141, 92, 219), tile5},
				{ new Color(238, 156, 189), tile6},
				{ new Color(179, 209, 228), tile7},
				{ new Color(126, 39, 38), tile8},
				{ new Color(252, 25, 91), tile9},
				{ new Color(174, 219, 216), tile10},
				{ new Color(18, 49, 36), tile11},
				{ new Color(173, 117, 15), tile12},
				{ new Color(104, 112, 202), tile13},
				{ new Color(231, 196, 199), tile14},
				{ new Color(152, 43, 19), tile15},
				{ new Color(251, 181, 100), tile16},
				{ new Color(172, 109, 6), tile17},
				{ new Color(176, 41, 244), tile18},
				{ new Color(189, 53, 218), tile19},
				{ new Color(216, 28, 15), tile20},
				{ new Color(247, 194, 177), tile21},
				{ new Color(196, 32, 179), tile22},
				{ new Color(78, 224, 230), tile23},
				{ new Color(204, 134, 44), tile24},
				{ new Color(242, 203, 12), tile25},
				{ new Color(29, 230, 252), tile26},
				{ new Color(18, 1, 99), tile27},
				{ new Color(247, 1, 109), tile28},
				{ new Color(209, 97, 8), tile29},
				{ new Color(47, 239, 63), tile30},
				{ new Color(52, 143, 83), tile31},
				{ new Color(187, 240, 2), tile32},
				{ new Color(22, 212, 10), tile33},
				{ new Color(96, 172, 212), tile34},
				{ new Color(125, 223, 230), tile35},
				{ new Color(218, 190, 93), tile36},
				{ new Color(231, 160, 79), tile37},
				{ new Color(221, 198, 27), tile38},
				{ new Color(171, 0, 192), tile39},
				{ new Color(67, 242, 190), tile40},
				{ new Color(170, 31, 240), tile41},
				{ new Color(166, 151, 246), tile42},
				{ new Color(217, 54, 218), tile43},
				{ new Color(10, 7, 17), tile44},
				{ new Color(241, 178, 85), tile45},
				{ new Color(143, 121, 34), tile46},
				{ new Color(134, 247, 163), tile47},
				{ new Color(171, 71, 79), tile48},
				{ new Color(240, 87, 201), tile49},
				{ new Color(56, 16, 240), tile50},
				{ new Color(65, 211, 225), tile51},
				{ new Color(76, 181, 140), tile52},
				{ new Color(228, 214, 72), tile53},
				{ new Color(240, 1, 135), tile54},
				{ new Color(130, 221, 153), tile55},
				{ new Color(61, 235, 20), tile56},
				{ new Color(198, 28, 134), tile57},
				{ new Color(158, 188, 251), tile58},
				{ new Color(26, 255, 215), tile59},
				{ new Color(161, 182, 64), tile60},
				{ new Color(45, 160, 38), tile61},
				{ new Color(234, 201, 52), tile62},
				{ new Color(48, 165, 252), tile63},
				{ new Color(200, 170, 162), tile64},
				{ new Color(217, 150, 246), tile65},
				{ new Color(28, 40, 106), tile66},
				{ new Color(182, 178, 107), tile67},
				{ new Color(181, 114, 243), tile68},
				{ new Color(105, 162, 22), tile69},
				{ new Color(229, 49, 181), tile70},
				{ new Color(180, 67, 32), tile71},
				{ new Color(7, 194, 96), tile72},
				{ new Color(96, 152, 19), tile73},
				{ new Color(101, 13, 69), tile74},
				{ new Color(23, 253, 113), tile75},
				{ new Color(228, 196, 37), tile76},
				{ new Color(5, 254, 214), tile77},
				{ new Color(109, 235, 4), tile78},
				{ new Color(212, 120, 46), tile79},
				{ new Color(50, 128, 38), tile80},
				{ new Color(29, 75, 116), tile81},
				{ new Color(70, 19, 103), tile82},
				{ new Color(130, 210, 211), tile83},
				{ new Color(149, 187, 144), tile84},
				{ new Color(86, 80, 165), tile85},
				{ new Color(38, 157, 116), tile86},
				{ new Color(130, 133, 222), tile87},
				{ new Color(240, 224, 50), tile88},
				{ new Color(223, 71, 87), tile89},
				{ new Color(27, 51, 74), tile90},
				{ new Color(49, 46, 23), tile91},
				{ new Color(237, 71, 194), tile92},
				{ new Color(208, 208, 234), tile93},
				{ new Color(10, 97, 242), tile94},
				{ new Color(82, 111, 67), tile95},
				{ new Color(70, 23, 154), tile96},
				{ new Color(94, 174, 218), tile97},
				{ new Color(186, 176, 250), tile98},
				{ new Color(72, 44, 107), tile99},
				{ new Color(66, 103, 204), tile100},
				{ new Color(15, 102, 158), tile101},
				{ new Color(136, 100, 141), tile102},
				{ new Color(120, 105, 9), tile103},
				{ new Color(227, 85, 205), tile104},
				{ new Color(137, 119, 35), tile105},
				{ new Color(235, 158, 112), tile106},
				{ new Color(239, 152, 47), tile107},
				{ new Color(189, 188, 132), tile108},
				{ new Color(112, 118, 125), tile109},
				{ new Color(29, 164, 27), tile110},
				{ new Color(86, 142, 104), tile111},
				{ new Color(29, 250, 251), tile112},
				{ new Color(83, 201, 11), tile113},
				{ new Color(182, 205, 174), tile114},
				{ new Color(145, 123, 89), tile115},
				{ new Color(12, 48, 57), tile116},
				{ new Color(215, 92, 141), tile117},
				{ new Color(250, 83, 207), tile118},
				{ new Color(156, 82, 169), tile119},
				{ new Color(26, 24, 237), tile120},
				{ new Color(15, 91, 196), tile121},
				{ new Color(237, 140, 198), tile122},
				{ new Color(101, 107, 125), tile123},
				{ new Color(40, 152, 213), tile124},
				{ new Color(101, 57, 202), tile125},
				{ new Color(129, 44, 65), tile126},
				{ new Color(43, 99, 70), tile127},
				{ new Color(68, 69, 72), tile128},
				{ new Color(141, 92, 59), tile129},
				{ new Color(153, 129, 168), tile130},
				{ new Color(81, 57, 176), tile131},
				{ new Color(29, 166, 114), tile132},
				{ new Color(234, 163, 239), tile133},
				{ new Color(146, 167, 196), tile134},
				{ new Color(187, 174, 196), tile135},
				{ new Color(183, 149, 25), tile136},
				{ new Color(4, 27, 37), tile137},
				{ new Color(104, 239, 180), tile138},
				{ new Color(167, 203, 21), tile139},
				{ new Color(124, 95, 48), tile140},
				{ new Color(139, 204, 234), tile141},
				{ new Color(212, 215, 94), tile142},
				{ new Color(37, 71, 147), tile143},
				{ new Color(88, 151, 136), tile144},
				{ new Color(82, 152, 188), tile145},
				{ new Color(129, 136, 151), tile146},
				{ new Color(131, 214, 198), tile147},
				{ new Color(33, 148, 101), tile148},
				{ new Color(130, 233, 73), tile149},
				{ new Color(252, 118, 218), tile150},
				{ new Color(92, 109, 67), tile151},
				{ new Color(191, 7, 219), tile152},
				{ new Color(218, 231, 215), tile153},
				{ new Color(101, 146, 77), tile154},
				{ new Color(134, 172, 132), tile155},
				{ new Color(156, 21, 86), tile156},
				{ new Color(248, 37, 67), tile157},
				{ new Color(126, 248, 137), tile158},
				{ new Color(105, 105, 55), tile159},
				{ new Color(132, 81, 237), tile160},
				{ new Color(20, 40, 209), tile161},
				{ new Color(184, 251, 41), tile162},
				{ new Color(69, 147, 144), tile163},
				{ new Color(225, 167, 161), tile164},
				{ new Color(191, 29, 67), tile165},
				{ new Color(121, 155, 231), tile166},
				{ new Color(225, 230, 211), tile167},
				{ new Color(242, 4, 80), tile168},
				{ new Color(151, 222, 116), tile169},
				{ new Color(186, 85, 157), tile170},
				{ new Color(163, 85, 149), tile171},
				{ new Color(233, 81, 105), tile172},
				{ new Color(123, 206, 177), tile173},
				{ new Color(90, 87, 130), tile174},
				{ new Color(198, 22, 126), tile175},
				{ new Color(161, 190, 219), tile176},
				{ new Color(70, 239, 206), tile177},
				{ new Color(80, 163, 107), tile178},
				{ new Color(26, 33, 36), tile179},
				{ new Color(129, 33, 28), tile180},
				{ new Color(180, 139, 61), tile181},
				{ new Color(242, 62, 82), tile182},
				{ new Color(11, 214, 204), tile183},
				{ new Color(217, 253, 204), tile184},
				{ new Color(54, 135, 142), tile185},
				{ new Color(80, 44, 237), tile186},
				{ new Color(210, 245, 31), tile187},
				{ new Color(153, 115, 102), tile188},
				{ new Color(207, 83, 178), tile189},
				{ new Color(42, 206, 47), tile190},
				{ new Color(68, 250, 172), tile191},
				{ new Color(148, 165, 204), tile192},
				{ new Color(69, 211, 216), tile193},
				{ new Color(43, 150, 232), tile194},
				{ new Color(15, 108, 242), tile195},
				{ new Color(1, 25, 27), tile196},
				{ new Color(221, 202, 245), tile197},
				{ new Color(55, 175, 43), tile198},
				{ new Color(253, 27, 23), tile199},
				{ new Color(214, 35, 235), tile200},
				{ new Color(160, 225, 7), tile201},
				{ new Color(157, 148, 2), tile202},
				{ new Color(32, 162, 225), tile203},
				{ new Color(193, 11, 89), tile204},
				{ new Color(21, 166, 95), tile205},
				{ new Color(55, 137, 7), tile206},
				{ new Color(116, 205, 57), tile207},
				{ new Color(150, 76, 4), tile208},
				{ new Color(58, 13, 75), tile209},
				{ new Color(129, 150, 138), tile210},
				{ new Color(181, 110, 175), tile211},
				{ new Color(237, 139, 180), tile212},
				{ new Color(225, 114, 215), tile213},
				{ new Color(239, 225, 118), tile214},
				{ new Color(58, 27, 191), tile215},
				{ new Color(155, 34, 8), tile216},
				{ new Color(204, 198, 145), tile217},
				{ new Color(16, 98, 85), tile218},
				{ new Color(177, 10, 148), tile219},
				{ new Color(2, 99, 135), tile220},
				{ new Color(183, 158, 11), tile221},
				{ new Color(87, 12, 156), tile222},
				{ new Color(169, 39, 26), tile223},
				{ new Color(170, 85, 23), tile224},
				{ new Color(47, 132, 236), tile225},
				{ new Color(195, 91, 49), tile226},
				{ new Color(69, 158, 235), tile227},
				{ new Color(66, 180, 208), tile228},
				{ new Color(248, 165, 11), tile229},
				{ new Color(90, 60, 129), tile230},
				{ new Color(31, 222, 15), tile231},
				{ new Color(80, 56, 66), tile232},
				{ new Color(107, 227, 15), tile233},
				{ new Color(34, 241, 250), tile234},
				{ new Color(238, 33, 112), tile235},
				{ new Color(122, 224, 221), tile236},
				{ new Color(104, 238, 174), tile237},
				{ new Color(99, 189, 196), tile238},
				{ new Color(156, 116, 234), tile239},
				{ new Color(58, 94, 102), tile240},
				{ new Color(144, 79, 235), tile241},
				{ new Color(153, 138, 119), tile242},
				{ new Color(8, 222, 76), tile243},
				{ new Color(170, 87, 120), tile244},
				{ new Color(34, 34, 173), tile245},
				{ new Color(240, 84, 146), tile246},
				{ new Color(96, 125, 196), tile247},
				{ new Color(45, 241, 77), tile248},
				{ new Color(211, 188, 33), tile249},
				{ new Color(75, 180, 195), tile250},
				{ new Color(88, 48, 132), tile251},
				{ new Color(168, 145, 162), tile252},
				{ new Color(15, 85, 150), tile253},
				{ new Color(249, 114, 2), tile254},
				{ new Color(145, 190, 150), tile255},
				{ new Color(53, 65, 154), tile256},
				{ new Color(23, 171, 32), tile257},
				{ new Color(87, 218, 225), tile258},
				{ new Color(162, 99, 93), tile259},
				{ new Color(157, 198, 206), tile260},
				{ new Color(86, 189, 42), tile261},
				{ new Color(137, 81, 39), tile262},
				{ new Color(244, 121, 144), tile263},
				{ new Color(11, 225, 255), tile264},
			};
			return new ColorTileMap(colorTileMap);
		}
	}
}
