using CalamityMod.Tiles;
using CalamityMod.Tiles.DraedonStructures;
using CalamityMod.Walls.DraedonStructures;
using Microsoft.Xna.Framework;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Terraria.ID;
using Terraria.ModLoader;

namespace CalamityMod.Schematics.AutoGeneratedContent
{
    public class Workshop2Schematic
	{
		[GeneratedCode("ScreenCaptureToSchematic", "1.0.2")]
		public static ColorTileMap GetMap()
		{
			var tile1 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0);
			var tile2 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 8224).UseFrame(72, 54);
			var tile3 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(288, 0);
			var tile4 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(90, 18);
			var tile5 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(90, 0);
			var tile6 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 36);
			var tile7 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 18);
			var tile8 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32);
			var tile9 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 16416).UseFrame(36, 72);
			var tile10 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(54, 54);
			var tile11 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 72);
			var tile12 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 132, 3, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 144, 108);
			var tile13 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 128, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 0, 72);
			var tile14 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile15 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 101, 1, 2144).UseFrame(162, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 36).MakeActuated();
			var tile16 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 72);
			var tile17 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 96, 1, 4128).UseFrame(90, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 0, 36);
			var tile18 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 148, 4, 32).UseFrame(72, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 144, 144);
			var tile19 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 8224).UseFrame(72, 54);
			var tile20 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 0);
			var tile21 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 164, 3, 12320).UseFrame(144, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 108);
			var tile22 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 288, 72);
			var tile23 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 36);
			var tile24 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 144);
			var tile25 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 0, 0, 2144).UseFrame(108, 72).MakeActuated();
			var tile26 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 0, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 0);
			var tile27 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 1, 2, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile28 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(162, 0);
			var tile29 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 0);
			var tile30 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 36);
			var tile31 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 108);
			var tile32 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 72);
			var tile33 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 98, 3, 2144).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 108).MakeActuated();
			var tile34 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 133, 2, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 72);
			var tile35 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 75, 1, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 396, 36);
			var tile36 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 66, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile37 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(108, 72);
			var tile38 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 0);
			var tile39 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 36);
			var tile40 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 0, 0, 32).UseFrame(0, 540);
			var tile41 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 1, 0, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 0);
			var tile42 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 136, 4, 2144).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 288, 144).MakeActuated();
			var tile43 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile44 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 1, 0, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 0);
			var tile45 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 1, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile46 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 72);
			var tile47 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(288, 36);
			var tile48 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 148, 3, 12320).UseFrame(54, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 108);
			var tile49 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 64, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile50 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 252, 72);
			var tile51 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 36);
			var tile52 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 5, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 0);
			var tile53 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 147, 2, 2144).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 72).MakeActuated();
			var tile54 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 1, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile55 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 72);
			var tile56 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 0);
			var tile57 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 66, 0, 2144).UseFrame(108, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 0).MakeActuated();
			var tile58 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 43, 0, 2144).UseFrame(90, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 396, 0).MakeActuated();
			var tile59 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 131, 1, 2144).UseFrame(90, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36).MakeActuated();
			var tile60 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 163, 2, 2144).UseFrame(90, 36).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 72).MakeActuated();
			var tile61 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 32, 0, 2144).UseFrame(90, 36).MakeActuated();
			var tile62 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 140, 2, 2144).UseFrame(18, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 432, 72).MakeActuated();
			var tile63 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 0);
			var tile64 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 0);
			var tile65 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile66 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 3, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 180, 108);
			var tile67 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 2, 32).UseFrame(234, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile68 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(306, 36);
			var tile69 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 16416).UseFrame(36, 72);
			var tile70 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 0, 0, 32).UseFrame(0, 216);
			var tile71 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 0, 0, 32).UseFrame(0, 234);
			var tile72 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 0, 0, 32).UseFrame(0, 252);
			var tile73 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 54);
			var tile74 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(0, 18);
			var tile75 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 16416).UseFrame(72, 72);
			var tile76 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(72, 54);
			var tile77 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile78 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 216, 72);
			var tile79 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 8224).UseFrame(144, 0);
			var tile80 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 76, 1, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 432, 36);
			var tile81 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 4128).UseFrame(18, 54);
			var tile82 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 72);
			var tile83 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 16416).UseFrame(0, 72);
			var tile84 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 8224).UseFrame(0, 54);
			var tile85 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(270, 72);
			var tile86 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 18);
			var tile87 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 18);
			var tile88 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 36);
			var tile89 = new TileDefinitionStructure(TileID.TallGateOpen).UseHeaders(0, 0, 0, 32);
			var tile90 = new TileDefinitionStructure(TileID.TallGateOpen).UseHeaders(0, 0, 0, 32).UseFrame(0, 20);
			var tile91 = new TileDefinitionStructure(TileID.TallGateOpen).UseHeaders(0, 0, 0, 32).UseFrame(0, 38);
			var tile92 = new TileDefinitionStructure(TileID.TallGateOpen).UseHeaders(0, 0, 0, 32).UseFrame(0, 56);
			var tile93 = new TileDefinitionStructure(TileID.TallGateOpen).UseHeaders(0, 0, 0, 32).UseFrame(0, 74);
			var tile94 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile95 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(270, 54);
			var tile96 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 0);
			var tile97 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 68, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 36);
			var tile98 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 72);
			var tile99 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 8224).UseFrame(144, 0);
			var tile100 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 73, 1, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 324, 36);
			var tile101 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 4128).UseFrame(54, 54);
			var tile102 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 54);
			var tile103 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(270, 72);
			var tile104 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 18);
			var tile105 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(252, 54);
			var tile106 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 66, 3, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 108);
			var tile107 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 12320).UseFrame(90, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 0, 0);
			var tile108 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 128, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 72);
			var tile109 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 128, 2, 4128).UseFrame(18, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 0, 72);
			var tile110 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 82, 4, 32).UseFrame(72, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 144);
			var tile111 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(288, 54);
			var tile112 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 140, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 432, 72);
			var tile113 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 0);
			var tile114 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 0);
			var tile115 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 64, 1, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile116 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 4128).UseFrame(90, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile117 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 96, 1, 32).UseFrame(72, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile118 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 4, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 144);
			var tile119 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(72, 36);
			var tile120 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 98, 3, 12320).UseFrame(90, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 108);
			var tile121 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36);
			var tile122 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 10, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 0);
			var tile123 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 132, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 72);
			var tile124 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 4, 0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile125 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 138, 2, 32).UseFrame(0, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 72);
			var tile126 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile127 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 131, 1, 32).UseFrame(0, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 36);
			var tile128 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 131, 2, 32).UseFrame(162, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile129 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 0);
			var tile130 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 64, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 0, 36);
			var tile131 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 5, 0, 32).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 0);
			var tile132 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 71, 2, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 252, 72);
			var tile133 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile134 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 4, 0, 32).UseFrame(0, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile135 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 64, 1, 12320).UseFrame(108, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile136 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72);
			var tile137 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(16, 0);
			var tile138 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 1, 0, 32).UseFrame(16, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 0);
			var tile139 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 66, 1, 32).UseFrame(16, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile140 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 136, 2, 32).UseFrame(16, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 288, 72);
			var tile141 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 82, 2, 32).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile142 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 108);
			var tile143 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 0, 0);
			var tile144 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 36, 36);
			var tile145 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 288, 36);
			var tile146 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 72);
			var tile147 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 32);
			var tile148 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 0);
			var tile149 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 139, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 396, 72);
			var tile150 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 68, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 144, 36);
			var tile151 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 132, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 144, 72);
			var tile152 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 36);
			var tile153 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 66, 2, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 72);
			var tile154 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 72);
			var tile155 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 67, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 108, 108);
			var tile156 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 11, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 396, 0);
			var tile157 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 72, 36);
			var tile158 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 4, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 144, 0);
			var tile159 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 180, 72);
			var tile160 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 133, 2, 32).UseFrame(32, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 72);
			var tile161 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 6, 1, 32).UseFrame(32, 16).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 216, 36);
			var tile162 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 139, 2, 32).UseFrame(32, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 396, 72);
			var tile163 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(32, 48).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 36);
			var tile164 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 33, 2, 32).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile165 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 138, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 72);
			var tile166 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 36);
			var tile167 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 69, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 36);
			var tile168 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile169 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 67, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 108);
			var tile170 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 87, 3, 32).UseFrame(216, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 252, 108);
			var tile171 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 0, 0, 32).UseFrame(0, 558);
			var tile172 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(48, 0);
			var tile173 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 1, 3, 32).UseFrame(48, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 108);
			var tile174 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 132, 2, 32).UseFrame(48, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 72);
			var tile175 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 66, 1, 32).UseFrame(48, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 36);
			var tile176 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 98, 2, 32).UseFrame(216, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile177 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile178 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32);
			var tile179 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 288, 144);
			var tile180 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 0);
			var tile181 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 0);
			var tile182 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 33, 2, 32).UseFrame(72, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile183 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(306, 54);
			var tile184 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 0);
			var tile185 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 288, 36);
			var tile186 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 2, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile187 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 144);
			var tile188 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 0);
			var tile189 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 82, 2, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile190 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 74, 1, 32).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 36);
			var tile191 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 131, 2, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile192 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 252, 144);
			var tile193 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 0, 0, 32);
			var tile194 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 0, 0, 32).UseFrame(0, 18);
			var tile195 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 131, 1, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36);
			var tile196 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 66, 1, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 36);
			var tile197 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 64, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile198 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 72);
			var tile199 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 6, 0, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 0);
			var tile200 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 132, 4, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 144);
			var tile201 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 0, 0, 32).UseFrame(36, 0);
			var tile202 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 66, 0, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 0);
			var tile203 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 33, 2, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile204 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 137, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 324, 72);
			var tile205 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 216, 36);
			var tile206 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 139, 2, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 396, 72);
			var tile207 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile208 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 288, 36);
			var tile209 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 0, 0, 32).UseFrame(18, 18);
			var tile210 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 1, 0, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 0);
			var tile211 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 4, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 144);
			var tile212 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 108);
			var tile213 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 11, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 396, 0);
			var tile214 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 252, 0);
			var tile215 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 69, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 36);
			var tile216 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 69, 1, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 36);
			var tile217 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 66, 1, 32).UseFrame(54, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 36);
			var tile218 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 147, 2, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile219 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 36);
			var tile220 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 1, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile221 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 67, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 144);
			var tile222 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 0);
			var tile223 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 0, 0, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile224 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 138, 2, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 72);
			var tile225 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 132, 2, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 72);
			var tile226 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 138, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 72);
			var tile227 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 33, 1, 2144).UseFrame(72, 54).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 36).MakeActuated();
			var tile228 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 16, 0, 2144).UseFrame(90, 18).MakeActuated();
			var tile229 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 0, 0, 2144).UseFrame(90, 0).MakeActuated();
			var tile230 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 1, 0, 2144).UseFrame(108, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 0).MakeActuated();
			var tile231 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 66, 2, 32).UseFrame(18, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile232 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 36);
			var tile233 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 66, 2, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile234 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 0, 0, 32).UseFrame(162, 0);
			var tile235 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 1, 0, 32).UseFrame(0, 540).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 0);
			var tile236 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 66, 1, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile237 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 17, 1, 2144).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 36).MakeActuated();
			var tile238 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 0, 0, 32);
			var tile239 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 132, 3, 32).UseFrame(0, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 108);
			var tile240 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile241 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 136, 2, 32).UseFrame(0, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 288, 72);
			var tile242 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 66, 2, 32).UseFrame(162, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile243 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 75, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 396, 36);
			var tile244 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 132, 2, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 144, 72);
			var tile245 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 64, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 0, 36);
			var tile246 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 72);
			var tile247 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 69, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 36);
			var tile248 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 69, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 180, 36);
			var tile249 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 68, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 144, 36);
			var tile250 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 6, 1, 8224).UseFrame(144, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 216, 36);
			var tile251 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 64, 1, 32).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 0, 36);
			var tile252 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 108, 36);
			var tile253 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 43, 0, 2144).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 396, 0).MakeActuated();
			var tile254 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 108, 36);
			var tile255 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 5, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 0);
			var tile256 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 133, 2, 32).UseFrame(16, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 72);
			var tile257 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 6, 1, 32).UseFrame(16, 16).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 216, 36);
			var tile258 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 11, 0, 32).UseFrame(16, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 396, 0);
			var tile259 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(16, 48).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 36);
			var tile260 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 147, 2, 32).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile261 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 108);
			var tile262 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 4, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile263 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 10, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 0);
			var tile264 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 4, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 144);
			var tile265 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(234, 0);
			var tile266 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 82, 1, 32).UseFrame(54, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile267 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 98, 1, 16416).UseFrame(144, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile268 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 74, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 36);
			var tile269 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 147, 1, 2144).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36).MakeActuated();
			var tile270 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 72);
			var tile271 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(32, 0);
			var tile272 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 66, 0, 32).UseFrame(32, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 0);
			var tile273 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 66, 1, 32).UseFrame(32, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile274 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 66, 1, 32).UseFrame(32, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 36);
			var tile275 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 17, 2, 32).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile276 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 66, 3, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 108);
			var tile277 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 144);
			var tile278 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 8224).UseFrame(0, 54);
			var tile279 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 83, 3, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 108);
			var tile280 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 68, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 36);
			var tile281 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 148, 2, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 72);
			var tile282 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 17, 1, 16416).UseFrame(36, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile283 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 66, 1, 2144).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 36).MakeActuated();
			var tile284 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(48, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile285 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(48, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile286 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 66, 1, 32).UseFrame(48, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile287 = new TileDefinitionStructure(ModContent.TileType<InactiveDraedonFuelFactory>()).UseHeaders(0, 6, 2, 32).UseFrame(48, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 216, 72);
			var tile288 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 163, 2, 32).UseFrame(216, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile289 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 68, 1, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 36);
			var tile290 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(306, 54);
			var tile291 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 54);
			var tile292 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(252, 72);
			var tile293 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 99, 3, 32).UseFrame(270, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 108);
			var tile294 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 20, 0, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 144, 0);
			var tile295 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 132, 2, 16416).UseFrame(0, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 144, 72);
			var tile296 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 100, 1, 8224).UseFrame(72, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 144, 36);
			var tile297 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 17, 4, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 144);
			var tile298 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(306, 54);
			var tile299 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 1, 0, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 0);
			var tile300 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 132, 4, 8224).UseFrame(144, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 144);
			var tile301 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(306, 72);
			var tile302 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 12320).UseFrame(54, 72);
			var tile303 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 4128).UseFrame(18, 54);
			var tile304 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(252, 72);
			var tile305 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 36);
			var tile306 = new TileDefinitionStructure(TileID.TallGateClosed).UseHeaders(0, 0, 0, 32);
			var tile307 = new TileDefinitionStructure(TileID.TallGateClosed).UseHeaders(0, 0, 0, 32).UseFrame(0, 20);
			var tile308 = new TileDefinitionStructure(TileID.TallGateClosed).UseHeaders(0, 0, 0, 32).UseFrame(0, 38);
			var tile309 = new TileDefinitionStructure(TileID.TallGateClosed).UseHeaders(0, 0, 0, 32).UseFrame(0, 56);
			var tile310 = new TileDefinitionStructure(TileID.TallGateClosed).UseHeaders(0, 0, 0, 32).UseFrame(0, 74);
			var tile311 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(252, 54);
			var tile312 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 12320).UseFrame(90, 72);
			var tile313 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 0);
			var tile314 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 36);
			var tile315 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 82, 0, 32).UseFrame(90, 18).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 0);
			var tile316 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 33, 2, 32).UseFrame(72, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 72);
			var tile317 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 2, 32).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile318 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 36);
			var tile319 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 12320).UseFrame(18, 72);
			var tile320 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(72, 18);
			var tile321 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 12320).UseFrame(90, 72);
			var tile322 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 54);
			var tile323 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 132, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 108);
			var tile324 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 66, 2, 32).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 72);
			var tile325 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 0);
			var tile326 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 17, 3, 16416).UseFrame(36, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 108);
			var tile327 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 10, 0, 32).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 0);
			var tile328 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 132, 4, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 144);
			var tile329 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 0, 0, 32).UseFrame(0, 18);
			var tile330 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 131, 0, 32).UseFrame(0, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 0);
			var tile331 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 131, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile332 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile333 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 36);
			var tile334 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 131, 0, 32).UseFrame(0, 540).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 0);
			var tile335 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 6, 2, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 216, 72);
			var tile336 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 131, 1, 32).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36);
			var tile337 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 71, 2, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 252, 72);
			var tile338 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 0, 0, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile339 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 131, 1, 32).UseFrame(18, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 36);
			var tile340 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 6, 1, 32).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 216, 36);
			var tile341 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 75, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 396, 36);
			var tile342 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 131, 1, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile343 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 6, 1, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 36);
			var tile344 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseHeaders(0, 75, 1, 32).UseFrame(36, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 396, 36);
			var tile345 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(306, 0);
			var tile346 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 17, 3, 16416).UseFrame(126, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 108);
			var tile347 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 42, 0, 32).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 0);
			var tile348 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 2, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile349 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(216, 0);
			var tile350 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 54);
			var tile351 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(72, 72);
			var tile352 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 3, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 180, 108);
			var tile353 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 164, 2, 32).UseFrame(216, 36).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 144, 72);
			var tile354 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 164, 2, 8224).UseFrame(72, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 144, 72);
			var tile355 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 165, 4, 32).UseFrame(0, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 180, 144);
			var tile356 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 4128).UseFrame(90, 54);
			var tile357 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(306, 0);
			var tile358 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(306, 18);
			var tile359 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 12320).UseFrame(18, 72);
			Dictionary<Color, TileDefinitionStructure> colorTileMap = new Dictionary<Color, TileDefinitionStructure>()
			{
				{ new Color(0, 0, 0), tile1 },
				{ new Color(114, 195, 225), tile2 },
				{ new Color(226, 74, 12), tile3 },
				{ new Color(228, 243, 191), tile4 },
				{ new Color(144, 205, 196), tile5 },
				{ new Color(39, 4, 64), tile6 },
				{ new Color(112, 181, 57), tile7 },
				{ new Color(106, 30, 171), tile8 },
				{ new Color(8, 54, 212), tile9 },
				{ new Color(26, 140, 167), tile10 },
				{ new Color(233, 4, 18), tile11 },
				{ new Color(173, 222, 58), tile12 },
				{ new Color(173, 194, 45), tile13 },
				{ new Color(67, 215, 12), tile14 },
				{ new Color(71, 99, 37), tile15 },
				{ new Color(6, 22, 237), tile16 },
				{ new Color(28, 144, 14), tile17 },
				{ new Color(209, 119, 142), tile18 },
				{ new Color(75, 230, 38), tile19 },
				{ new Color(191, 106, 140), tile20 },
				{ new Color(13, 199, 189), tile21 },
				{ new Color(100, 250, 238), tile22 },
				{ new Color(172, 226, 239), tile23 },
				{ new Color(138, 121, 66), tile24 },
				{ new Color(19, 44, 222), tile25 },
				{ new Color(44, 34, 187), tile26 },
				{ new Color(133, 1, 31), tile27 },
				{ new Color(230, 253, 252), tile28 },
				{ new Color(153, 23, 141), tile29 },
				{ new Color(132, 98, 248), tile30 },
				{ new Color(20, 238, 88), tile31 },
				{ new Color(161, 54, 15), tile32 },
				{ new Color(79, 226, 104), tile33 },
				{ new Color(55, 89, 52), tile34 },
				{ new Color(254, 146, 22), tile35 },
				{ new Color(203, 190, 74), tile36 },
				{ new Color(176, 31, 195), tile37 },
				{ new Color(106, 57, 104), tile38 },
				{ new Color(109, 38, 202), tile39 },
				{ new Color(193, 203, 227), tile40 },
				{ new Color(96, 40, 127), tile41 },
				{ new Color(246, 117, 139), tile42 },
				{ new Color(233, 113, 246), tile43 },
				{ new Color(206, 221, 63), tile44 },
				{ new Color(82, 77, 167), tile45 },
				{ new Color(234, 232, 106), tile46 },
				{ new Color(230, 205, 88), tile47 },
				{ new Color(67, 212, 67), tile48 },
				{ new Color(53, 169, 180), tile49 },
				{ new Color(239, 51, 15), tile50 },
				{ new Color(69, 141, 23), tile51 },
				{ new Color(133, 215, 49), tile52 },
				{ new Color(180, 7, 28), tile53 },
				{ new Color(138, 226, 77), tile54 },
				{ new Color(83, 225, 65), tile55 },
				{ new Color(131, 24, 235), tile56 },
				{ new Color(192, 130, 61), tile57 },
				{ new Color(95, 218, 253), tile58 },
				{ new Color(139, 29, 84), tile59 },
				{ new Color(60, 193, 204), tile60 },
				{ new Color(215, 250, 62), tile61 },
				{ new Color(230, 137, 79), tile62 },
				{ new Color(39, 205, 118), tile63 },
				{ new Color(118, 54, 225), tile64 },
				{ new Color(78, 92, 235), tile65 },
				{ new Color(11, 239, 242), tile66 },
				{ new Color(1, 177, 145), tile67 },
				{ new Color(200, 47, 177), tile68 },
				{ new Color(210, 230, 179), tile69 },
				{ new Color(26, 250, 186), tile70 },
				{ new Color(220, 119, 69), tile71 },
				{ new Color(80, 179, 232), tile72 },
				{ new Color(14, 109, 88), tile73 },
				{ new Color(241, 91, 74), tile74 },
				{ new Color(116, 74, 76), tile75 },
				{ new Color(92, 17, 125), tile76 },
				{ new Color(17, 127, 45), tile77 },
				{ new Color(97, 58, 16), tile78 },
				{ new Color(58, 14, 203), tile79 },
				{ new Color(140, 20, 162), tile80 },
				{ new Color(155, 13, 211), tile81 },
				{ new Color(188, 153, 190), tile82 },
				{ new Color(155, 253, 169), tile83 },
				{ new Color(3, 252, 130), tile84 },
				{ new Color(154, 15, 85), tile85 },
				{ new Color(70, 84, 229), tile86 },
				{ new Color(100, 117, 213), tile87 },
				{ new Color(53, 8, 122), tile88 },
				{ new Color(140, 123, 61), tile89 },
				{ new Color(53, 22, 164), tile90 },
				{ new Color(28, 129, 88), tile91 },
				{ new Color(181, 86, 78), tile92 },
				{ new Color(119, 184, 176), tile93 },
				{ new Color(142, 193, 19), tile94 },
				{ new Color(212, 14, 131), tile95 },
				{ new Color(170, 199, 43), tile96 },
				{ new Color(186, 243, 186), tile97 },
				{ new Color(230, 40, 158), tile98 },
				{ new Color(205, 102, 4), tile99 },
				{ new Color(88, 47, 30), tile100 },
				{ new Color(129, 101, 231), tile101 },
				{ new Color(4, 230, 122), tile102 },
				{ new Color(41, 229, 185), tile103 },
				{ new Color(7, 207, 155), tile104 },
				{ new Color(52, 214, 180), tile105 },
				{ new Color(193, 97, 250), tile106 },
				{ new Color(247, 225, 179), tile107 },
				{ new Color(17, 122, 34), tile108 },
				{ new Color(234, 54, 89), tile109 },
				{ new Color(186, 231, 239), tile110 },
				{ new Color(73, 31, 136), tile111 },
				{ new Color(145, 13, 91), tile112 },
				{ new Color(44, 207, 39), tile113 },
				{ new Color(9, 129, 225), tile114 },
				{ new Color(113, 179, 36), tile115 },
				{ new Color(30, 177, 81), tile116 },
				{ new Color(234, 12, 5), tile117 },
				{ new Color(10, 97, 77), tile118 },
				{ new Color(106, 111, 235), tile119 },
				{ new Color(196, 26, 175), tile120 },
				{ new Color(32, 111, 253), tile121 },
				{ new Color(202, 189, 175), tile122 },
				{ new Color(19, 163, 201), tile123 },
				{ new Color(89, 148, 145), tile124 },
				{ new Color(210, 238, 96), tile125 },
				{ new Color(210, 160, 198), tile126 },
				{ new Color(253, 203, 133), tile127 },
				{ new Color(7, 208, 218), tile128 },
				{ new Color(234, 63, 190), tile129 },
				{ new Color(58, 38, 158), tile130 },
				{ new Color(111, 104, 181), tile131 },
				{ new Color(119, 232, 18), tile132 },
				{ new Color(227, 167, 245), tile133 },
				{ new Color(116, 11, 13), tile134 },
				{ new Color(136, 144, 120), tile135 },
				{ new Color(115, 55, 115), tile136 },
				{ new Color(237, 152, 206), tile137 },
				{ new Color(36, 199, 78), tile138 },
				{ new Color(41, 24, 158), tile139 },
				{ new Color(34, 223, 126), tile140 },
				{ new Color(241, 217, 125), tile141 },
				{ new Color(43, 233, 44), tile142 },
				{ new Color(219, 91, 5), tile143 },
				{ new Color(78, 238, 249), tile144 },
				{ new Color(209, 136, 192), tile145 },
				{ new Color(120, 127, 63), tile146 },
				{ new Color(98, 119, 7), tile147 },
				{ new Color(74, 76, 141), tile148 },
				{ new Color(207, 75, 161), tile149 },
				{ new Color(103, 78, 207), tile150 },
				{ new Color(115, 192, 200), tile151 },
				{ new Color(118, 131, 49), tile152 },
				{ new Color(144, 93, 167), tile153 },
				{ new Color(76, 151, 220), tile154 },
				{ new Color(109, 158, 170), tile155 },
				{ new Color(213, 83, 62), tile156 },
				{ new Color(141, 177, 153), tile157 },
				{ new Color(95, 192, 104), tile158 },
				{ new Color(119, 166, 140), tile159 },
				{ new Color(239, 91, 158), tile160 },
				{ new Color(139, 116, 12), tile161 },
				{ new Color(53, 219, 45), tile162 },
				{ new Color(49, 90, 5), tile163 },
				{ new Color(143, 231, 34), tile164 },
				{ new Color(152, 22, 223), tile165 },
				{ new Color(43, 221, 174), tile166 },
				{ new Color(227, 250, 247), tile167 },
				{ new Color(98, 217, 156), tile168 },
				{ new Color(54, 19, 0), tile169 },
				{ new Color(95, 255, 220), tile170 },
				{ new Color(165, 160, 1), tile171 },
				{ new Color(8, 193, 34), tile172 },
				{ new Color(207, 55, 195), tile173 },
				{ new Color(124, 163, 249), tile174 },
				{ new Color(57, 254, 201), tile175 },
				{ new Color(118, 198, 169), tile176 },
				{ new Color(136, 75, 201), tile177 },
				{ new Color(222, 12, 97), tile178 },
				{ new Color(166, 40, 155), tile179 },
				{ new Color(112, 255, 199), tile180 },
				{ new Color(45, 209, 90), tile181 },
				{ new Color(41, 233, 71), tile182 },
				{ new Color(32, 143, 85), tile183 },
				{ new Color(188, 91, 165), tile184 },
				{ new Color(234, 103, 86), tile185 },
				{ new Color(254, 41, 219), tile186 },
				{ new Color(210, 191, 77), tile187 },
				{ new Color(86, 215, 180), tile188 },
				{ new Color(18, 199, 148), tile189 },
				{ new Color(160, 98, 152), tile190 },
				{ new Color(135, 94, 56), tile191 },
				{ new Color(251, 79, 210), tile192 },
				{ new Color(159, 16, 21), tile193 },
				{ new Color(130, 85, 54), tile194 },
				{ new Color(84, 203, 239), tile195 },
				{ new Color(36, 243, 165), tile196 },
				{ new Color(10, 167, 255), tile197 },
				{ new Color(191, 157, 63), tile198 },
				{ new Color(122, 214, 250), tile199 },
				{ new Color(166, 22, 33), tile200 },
				{ new Color(178, 128, 45), tile201 },
				{ new Color(189, 53, 252), tile202 },
				{ new Color(108, 238, 23), tile203 },
				{ new Color(132, 95, 25), tile204 },
				{ new Color(198, 79, 105), tile205 },
				{ new Color(22, 2, 11), tile206 },
				{ new Color(196, 237, 212), tile207 },
				{ new Color(239, 149, 186), tile208 },
				{ new Color(153, 199, 193), tile209 },
				{ new Color(249, 129, 121), tile210 },
				{ new Color(216, 248, 249), tile211 },
				{ new Color(243, 208, 213), tile212 },
				{ new Color(9, 150, 150), tile213 },
				{ new Color(243, 184, 4), tile214 },
				{ new Color(141, 133, 72), tile215 },
				{ new Color(230, 249, 77), tile216 },
				{ new Color(213, 100, 211), tile217 },
				{ new Color(238, 226, 40), tile218 },
				{ new Color(77, 195, 234), tile219 },
				{ new Color(115, 35, 109), tile220 },
				{ new Color(59, 114, 109), tile221 },
				{ new Color(158, 172, 102), tile222 },
				{ new Color(31, 210, 127), tile223 },
				{ new Color(148, 12, 107), tile224 },
				{ new Color(117, 208, 53), tile225 },
				{ new Color(207, 98, 16), tile226 },
				{ new Color(114, 178, 205), tile227 },
				{ new Color(115, 36, 28), tile228 },
				{ new Color(165, 233, 22), tile229 },
				{ new Color(208, 166, 13), tile230 },
				{ new Color(234, 150, 115), tile231 },
				{ new Color(40, 183, 69), tile232 },
				{ new Color(151, 238, 217), tile233 },
				{ new Color(225, 198, 39), tile234 },
				{ new Color(206, 64, 87), tile235 },
				{ new Color(103, 121, 17), tile236 },
				{ new Color(243, 126, 96), tile237 },
				{ new Color(218, 0, 112), tile238 },
				{ new Color(159, 200, 78), tile239 },
				{ new Color(80, 249, 194), tile240 },
				{ new Color(80, 79, 43), tile241 },
				{ new Color(114, 170, 118), tile242 },
				{ new Color(248, 76, 25), tile243 },
				{ new Color(239, 55, 116), tile244 },
				{ new Color(55, 145, 236), tile245 },
				{ new Color(166, 165, 227), tile246 },
				{ new Color(197, 62, 112), tile247 },
				{ new Color(5, 220, 40), tile248 },
				{ new Color(172, 15, 149), tile249 },
				{ new Color(2, 137, 238), tile250 },
				{ new Color(247, 71, 245), tile251 },
				{ new Color(22, 145, 119), tile252 },
				{ new Color(251, 91, 150), tile253 },
				{ new Color(224, 110, 44), tile254 },
				{ new Color(247, 3, 70), tile255 },
				{ new Color(236, 163, 111), tile256 },
				{ new Color(132, 249, 35), tile257 },
				{ new Color(107, 138, 186), tile258 },
				{ new Color(82, 74, 114), tile259 },
				{ new Color(3, 198, 155), tile260 },
				{ new Color(225, 246, 195), tile261 },
				{ new Color(42, 248, 240), tile262 },
				{ new Color(126, 32, 0), tile263 },
				{ new Color(117, 170, 73), tile264 },
				{ new Color(77, 228, 207), tile265 },
				{ new Color(68, 13, 217), tile266 },
				{ new Color(225, 192, 107), tile267 },
				{ new Color(38, 125, 143), tile268 },
				{ new Color(203, 140, 188), tile269 },
				{ new Color(58, 195, 70), tile270 },
				{ new Color(4, 248, 148), tile271 },
				{ new Color(251, 255, 119), tile272 },
				{ new Color(104, 204, 11), tile273 },
				{ new Color(86, 109, 130), tile274 },
				{ new Color(111, 15, 78), tile275 },
				{ new Color(217, 29, 166), tile276 },
				{ new Color(234, 14, 60), tile277 },
				{ new Color(153, 33, 6), tile278 },
				{ new Color(47, 186, 121), tile279 },
				{ new Color(51, 95, 108), tile280 },
				{ new Color(51, 68, 93), tile281 },
				{ new Color(185, 112, 178), tile282 },
				{ new Color(180, 82, 229), tile283 },
				{ new Color(88, 219, 65), tile284 },
				{ new Color(206, 139, 82), tile285 },
				{ new Color(233, 183, 110), tile286 },
				{ new Color(65, 241, 110), tile287 },
				{ new Color(22, 79, 181), tile288 },
				{ new Color(9, 106, 214), tile289 },
				{ new Color(142, 203, 69), tile290 },
				{ new Color(254, 52, 109), tile291 },
				{ new Color(158, 34, 41), tile292 },
				{ new Color(37, 181, 158), tile293 },
				{ new Color(155, 36, 203), tile294 },
				{ new Color(193, 146, 50), tile295 },
				{ new Color(251, 203, 150), tile296 },
				{ new Color(179, 70, 3), tile297 },
				{ new Color(10, 242, 109), tile298 },
				{ new Color(254, 29, 244), tile299 },
				{ new Color(167, 175, 5), tile300 },
				{ new Color(220, 38, 134), tile301 },
				{ new Color(159, 89, 166), tile302 },
				{ new Color(211, 47, 104), tile303 },
				{ new Color(41, 195, 1), tile304 },
				{ new Color(208, 165, 204), tile305 },
				{ new Color(163, 85, 189), tile306 },
				{ new Color(130, 14, 159), tile307 },
				{ new Color(64, 218, 133), tile308 },
				{ new Color(65, 244, 66), tile309 },
				{ new Color(255, 160, 5), tile310 },
				{ new Color(52, 126, 6), tile311 },
				{ new Color(152, 191, 254), tile312 },
				{ new Color(68, 33, 56), tile313 },
				{ new Color(140, 39, 155), tile314 },
				{ new Color(45, 138, 130), tile315 },
				{ new Color(2, 58, 77), tile316 },
				{ new Color(161, 90, 199), tile317 },
				{ new Color(55, 36, 161), tile318 },
				{ new Color(102, 155, 75), tile319 },
				{ new Color(0, 94, 101), tile320 },
				{ new Color(100, 212, 143), tile321 },
				{ new Color(98, 245, 69), tile322 },
				{ new Color(251, 55, 229), tile323 },
				{ new Color(205, 94, 52), tile324 },
				{ new Color(132, 246, 230), tile325 },
				{ new Color(3, 19, 80), tile326 },
				{ new Color(2, 63, 185), tile327 },
				{ new Color(245, 93, 69), tile328 },
				{ new Color(62, 253, 89), tile329 },
				{ new Color(100, 50, 36), tile330 },
				{ new Color(179, 67, 194), tile331 },
				{ new Color(211, 40, 83), tile332 },
				{ new Color(12, 202, 149), tile333 },
				{ new Color(61, 6, 2), tile334 },
				{ new Color(103, 211, 252), tile335 },
				{ new Color(147, 178, 45), tile336 },
				{ new Color(186, 98, 136), tile337 },
				{ new Color(250, 254, 31), tile338 },
				{ new Color(171, 110, 118), tile339 },
				{ new Color(74, 36, 247), tile340 },
				{ new Color(235, 150, 5), tile341 },
				{ new Color(193, 26, 26), tile342 },
				{ new Color(113, 176, 206), tile343 },
				{ new Color(147, 247, 72), tile344 },
				{ new Color(187, 197, 56), tile345 },
				{ new Color(183, 142, 138), tile346 },
				{ new Color(72, 171, 74), tile347 },
				{ new Color(43, 170, 207), tile348 },
				{ new Color(156, 184, 69), tile349 },
				{ new Color(163, 39, 185), tile350 },
				{ new Color(221, 194, 165), tile351 },
				{ new Color(157, 81, 112), tile352 },
				{ new Color(252, 165, 185), tile353 },
				{ new Color(225, 33, 1), tile354 },
				{ new Color(95, 39, 107), tile355 },
				{ new Color(63, 63, 56), tile356 },
				{ new Color(230, 244, 224), tile357 },
				{ new Color(236, 1, 121), tile358 },
				{ new Color(173, 191, 236), tile359 },
			};
			return new ColorTileMap(colorTileMap);
		}
	}
}
