using CalamityMod.Tiles;
using CalamityMod.Tiles.DraedonStructures;
using CalamityMod.Walls.DraedonStructures;
using Microsoft.Xna.Framework;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Terraria.ID;
using Terraria.ModLoader;

namespace CalamityMod.Schematics.AutoGeneratedContent
{
    public class WorkshopSchematic
	{
		[GeneratedCode("ScreenCaptureToSchematic", "1.0.2")]
		public static ColorTileMap GetMap()
		{
			var tile1 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0);
			var tile2 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 8224).UseFrame(0, 54);
			var tile3 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 0);
			var tile4 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(90, 0);
			var tile5 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(90, 18);
			var tile6 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(288, 18);
			var tile7 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(0, 36);
			var tile8 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 16416).UseFrame(72, 72);
			var tile9 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 54);
			var tile10 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 72);
			var tile11 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 3, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 108);
			var tile12 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 0, 0);
			var tile13 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 64, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile14 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 149, 2, 2144).UseFrame(162, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 72).MakeActuated();
			var tile15 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 72);
			var tile16 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 128, 2, 4128).UseFrame(18, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 0, 72);
			var tile17 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 4, 32).UseFrame(72, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 0, 144);
			var tile18 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 8224).UseFrame(36, 54);
			var tile19 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(288, 0);
			var tile20 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 3, 12320).UseFrame(108, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 108);
			var tile21 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 216, 72);
			var tile22 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36);
			var tile23 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 144);
			var tile24 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 0, 0, 2144).UseFrame(108, 72).MakeActuated();
			var tile25 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 0, 0, 32);
			var tile26 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 131, 0, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 0);
			var tile27 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 131, 2, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile28 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(162, 0);
			var tile29 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 0);
			var tile30 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 36);
			var tile31 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 108);
			var tile32 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 72);
			var tile33 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 132, 3, 2144).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 108).MakeActuated();
			var tile34 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 69, 1, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 36);
			var tile35 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 75, 1, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 396, 36);
			var tile36 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 66, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile37 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 72);
			var tile38 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile39 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 36);
			var tile40 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 0, 0, 32).UseFrame(0, 540);
			var tile41 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 131, 0, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 0);
			var tile42 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 6, 4, 2144).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 144).MakeActuated();
			var tile43 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 1, 0, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 0);
			var tile44 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(108, 72);
			var tile45 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(288, 36);
			var tile46 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 3, 12320).UseFrame(18, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 108);
			var tile47 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 128, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 72);
			var tile48 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 17, 2, 2144).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72).MakeActuated();
			var tile49 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile50 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 1, 0, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 0);
			var tile51 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile52 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 72);
			var tile53 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 0);
			var tile54 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 17, 0, 2144).UseFrame(126, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 0).MakeActuated();
			var tile55 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 91, 1, 2144).UseFrame(90, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 396, 36).MakeActuated();
			var tile56 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 163, 1, 2144).UseFrame(90, 36).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36).MakeActuated();
			var tile57 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 98, 2, 2144).UseFrame(90, 36).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 72).MakeActuated();
			var tile58 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 32, 0, 2144).UseFrame(90, 36).MakeActuated();
			var tile59 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 140, 2, 2144).UseFrame(18, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 432, 72).MakeActuated();
			var tile60 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 0);
			var tile61 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 0);
			var tile62 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 0);
			var tile63 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile64 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 36);
			var tile65 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 72);
			var tile66 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 3, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 180, 108);
			var tile67 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 2, 32).UseFrame(234, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile68 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(306, 36);
			var tile69 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 16416).UseFrame(36, 72);
			var tile70 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 0, 0, 32).UseFrame(0, 216);
			var tile71 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 0, 0, 32).UseFrame(0, 234);
			var tile72 = new TileDefinitionStructure(TileID.Lamps).UseHeaders(0, 0, 0, 32).UseFrame(0, 252);
			var tile73 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(72, 54);
			var tile74 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(0, 18);
			var tile75 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 16416).UseFrame(36, 72);
			var tile76 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(72, 54);
			var tile77 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile78 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 252, 72);
			var tile79 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 8224).UseFrame(144, 0);
			var tile80 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 12, 0, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 432, 0);
			var tile81 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 4128).UseFrame(90, 54);
			var tile82 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(288, 72);
			var tile83 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 16416).UseFrame(0, 72);
			var tile84 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(270, 72);
			var tile85 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 18);
			var tile86 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 18);
			var tile87 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(108, 36);
			var tile88 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 54);
			var tile89 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDoorClosed>()).UseHeaders(0, 0, 0, 32);
			var tile90 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDoorClosed>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 18);
			var tile91 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDoorClosed>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 36);
			var tile92 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDoorClosed>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 54);
			var tile93 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(270, 54);
			var tile94 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 0);
			var tile95 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 4, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile96 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 36);
			var tile97 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 72);
			var tile98 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 8224).UseFrame(144, 0);
			var tile99 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 73, 1, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 324, 36);
			var tile100 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 4128).UseFrame(54, 54);
			var tile101 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(288, 54);
			var tile102 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 54);
			var tile103 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 18);
			var tile104 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(252, 54);
			var tile105 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 66, 3, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 108);
			var tile106 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 80, 1, 12320).UseFrame(54, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 0, 36);
			var tile107 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile108 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 4128).UseFrame(90, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 0, 0);
			var tile109 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 4, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 0, 144);
			var tile110 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 54);
			var tile111 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 76, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 432, 36);
			var tile112 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 0);
			var tile113 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 64, 1, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile114 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 4128).UseFrame(18, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile115 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(72, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile116 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 4, 32).UseFrame(72, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 144);
			var tile117 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(72, 0);
			var tile118 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 3, 12320).UseFrame(54, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 108);
			var tile119 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 10, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 0);
			var tile120 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 68, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 36);
			var tile121 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 4, 0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile122 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 10, 0, 32).UseFrame(0, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 0);
			var tile123 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 131, 1, 32).UseFrame(0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile124 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 131, 1, 32).UseFrame(0, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 36);
			var tile125 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 33, 2, 32).UseFrame(162, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile126 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 0);
			var tile127 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 64, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 0, 36);
			var tile128 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 69, 1, 32).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 36);
			var tile129 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 6, 2, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 72);
			var tile130 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 132, 2, 32).UseFrame(0, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 72);
			var tile131 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 144, 2, 12320).UseFrame(126, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 72);
			var tile132 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72);
			var tile133 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(16, 0);
			var tile134 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 66, 0, 32).UseFrame(16, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 0);
			var tile135 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(16, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile136 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 71, 2, 32).UseFrame(16, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 252, 72);
			var tile137 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 1, 2, 32).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile138 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 0, 108);
			var tile139 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 0, 0);
			var tile140 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 108, 36);
			var tile141 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 252, 36);
			var tile142 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 72);
			var tile143 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 32);
			var tile144 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 0);
			var tile145 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 75, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 396, 36);
			var tile146 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 68, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 144, 36);
			var tile147 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 36);
			var tile148 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 66, 2, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 72);
			var tile149 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 0, 0, 32).UseFrame(108, 72);
			var tile150 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 67, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 108, 108);
			var tile151 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 4, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 144, 0);
			var tile152 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 139, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 396, 72);
			var tile153 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 36, 36);
			var tile154 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 5, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 180, 0);
			var tile155 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 69, 1, 32).UseFrame(32, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 36);
			var tile156 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 71, 1, 32).UseFrame(32, 16).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 252, 36);
			var tile157 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 11, 0, 32).UseFrame(32, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 396, 0);
			var tile158 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 131, 1, 32).UseFrame(32, 48).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 108, 36);
			var tile159 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 163, 2, 32).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile160 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 0);
			var tile161 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 132, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 72);
			var tile162 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 10, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 0);
			var tile163 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 36);
			var tile164 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 5, 0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 0);
			var tile165 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 72);
			var tile166 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 67, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 108);
			var tile167 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 136, 3, 32).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 288, 108);
			var tile168 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 0, 0, 32).UseFrame(0, 558);
			var tile169 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(48, 0);
			var tile170 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 133, 3, 32).UseFrame(48, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 108);
			var tile171 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 4, 0, 32).UseFrame(48, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile172 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(48, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 36);
			var tile173 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 98, 2, 32).UseFrame(216, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile174 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 140, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 432, 72);
			var tile175 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 0);
			var tile176 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile177 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32);
			var tile178 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 71, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 252, 144);
			var tile179 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 0);
			var tile180 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 0, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 0);
			var tile181 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 131, 2, 32).UseFrame(0, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile182 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(306, 54);
			var tile183 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 216, 36);
			var tile184 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 144);
			var tile185 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 163, 2, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile186 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 36);
			var tile187 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 138, 2, 32).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 72);
			var tile188 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 1, 2, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile189 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryElectricPanel>()).UseHeaders(0, 1, 0, 32).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 0);
			var tile190 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryElectricPanel>()).UseHeaders(0, 66, 2, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 72);
			var tile191 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryContainmentBox>()).UseHeaders(0, 0, 0, 32);
			var tile192 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryContainmentBox>()).UseHeaders(0, 66, 0, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 0);
			var tile193 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 147, 2, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile194 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 1, 1, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 36);
			var tile195 = new TileDefinitionStructure(ModContent.TileType<AgedSecurityChestTile>()).UseHeaders(0, 1, 1, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 36);
			var tile196 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile197 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 71, 0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 252, 0);
			var tile198 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 132, 4, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 144);
			var tile199 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryElectricPanel>()).UseHeaders(0, 131, 0, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 0);
			var tile200 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryElectricPanel>()).UseHeaders(0, 131, 2, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 72);
			var tile201 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryContainmentBox>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile202 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryContainmentBox>()).UseHeaders(0, 66, 0, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 0);
			var tile203 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 98, 2, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile204 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 137, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 324, 72);
			var tile205 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 288, 36);
			var tile206 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 11, 0, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 396, 0);
			var tile207 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile208 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 288, 36);
			var tile209 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 144);
			var tile210 = new TileDefinitionStructure(ModContent.TileType<AgedReinforcedCrate>()).UseHeaders(0, 66, 0, 32).UseFrame(18, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 0);
			var tile211 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 4, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 144);
			var tile212 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 132, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 108);
			var tile213 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 75, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 396, 36);
			var tile214 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 6, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 216, 0);
			var tile215 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 5, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 0);
			var tile216 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryContainmentBox>()).UseHeaders(0, 69, 1, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 36);
			var tile217 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryContainmentBox>()).UseHeaders(0, 131, 1, 32).UseFrame(36, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 36);
			var tile218 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 82, 2, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile219 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 74, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 36);
			var tile220 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 288, 0);
			var tile221 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 138, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 360, 72);
			var tile222 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 68, 1, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 36);
			var tile223 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 82, 1, 2144).UseFrame(36, 54).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 36).MakeActuated();
			var tile224 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 66, 2, 2144).UseFrame(90, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 72).MakeActuated();
			var tile225 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 16, 0, 2144).UseFrame(90, 18).MakeActuated();
			var tile226 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 147, 0, 2144).UseFrame(126, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 0).MakeActuated();
			var tile227 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 131, 2, 32).UseFrame(18, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile228 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(288, 54);
			var tile229 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 1, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 36);
			var tile230 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 1, 2, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72);
			var tile231 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 32, 0, 32).UseFrame(162, 36);
			var tile232 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 131, 0, 32).UseFrame(0, 540).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 0);
			var tile233 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 66, 1, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile234 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 98, 1, 2144).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 36).MakeActuated();
			var tile235 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 0, 0, 32);
			var tile236 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 66, 3, 32).UseFrame(0, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 108);
			var tile237 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 0);
			var tile238 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 6, 2, 32).UseFrame(0, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 216, 72);
			var tile239 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 1, 2, 32).UseFrame(162, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile240 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 72, 0);
			var tile241 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 11, 0, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 396, 0);
			var tile242 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 72, 36);
			var tile243 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 136, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 288, 36);
			var tile244 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 139, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 396, 72);
			var tile245 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 68, 1, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 144, 36);
			var tile246 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 128, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 0, 72);
			var tile247 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 5, 0, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 0);
			var tile248 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 69, 1, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 180, 36);
			var tile249 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 2, 0).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 180, 72);
			var tile250 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 68, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 144, 36);
			var tile251 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 71, 1, 8224).UseFrame(144, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 252, 36);
			var tile252 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 80, 1, 32).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 0, 36);
			var tile253 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 11, 0, 2144).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<RustedPlatePillar>(), 396, 0).MakeActuated();
			var tile254 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 72);
			var tile255 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 133, 2, 32).UseFrame(16, 0).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 180, 72);
			var tile256 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 136, 1, 32).UseFrame(16, 16).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 288, 36);
			var tile257 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 11, 0, 32).UseFrame(16, 32).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 396, 0);
			var tile258 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(16, 48).UseWall((ushort)ModContent.WallType<LaboratoryPlatePillar>(), 36, 36);
			var tile259 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 147, 2, 32).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile260 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 4, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 180, 144);
			var tile261 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(234, 0);
			var tile262 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 98, 1, 32).UseFrame(90, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile263 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPanels>()).UseHeaders(0, 33, 1, 16416).UseFrame(144, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile264 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 131, 1, 2144).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36).MakeActuated();
			var tile265 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 0, 0, 32).UseFrame(32, 0);
			var tile266 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 66, 0, 32).UseFrame(32, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 0);
			var tile267 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 66, 1, 32).UseFrame(32, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 36);
			var tile268 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 66, 1, 32).UseFrame(32, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 36);
			var tile269 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 33, 2, 32).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile270 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 66, 3, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 108);
			var tile271 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 4, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 144);
			var tile272 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 133, 3, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 108);
			var tile273 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 36, 0, 32).UseFrame(0, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile274 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 164, 2, 32).UseFrame(0, 36).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 72);
			var tile275 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 163, 1, 16416).UseFrame(72, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile276 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 163, 1, 2144).UseFrame(216, 36).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 36).MakeActuated();
			var tile277 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 128, 2, 32).UseFrame(48, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 72);
			var tile278 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(48, 16).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile279 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 1, 1, 32).UseFrame(48, 32).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 36);
			var tile280 = new TileDefinitionStructure(ModContent.TileType<InactivePowerCellFactory>()).UseHeaders(0, 136, 2, 32).UseFrame(48, 48).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 288, 72);
			var tile281 = new TileDefinitionStructure(ModContent.TileType<HazardChevronPanels>()).UseHeaders(0, 1, 2, 32).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile282 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 108);
			var tile283 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 4, 0, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 144, 0);
			var tile284 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 66, 2, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 72);
			var tile285 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 8224).UseFrame(72, 54);
			var tile286 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(306, 54);
			var tile287 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 54);
			var tile288 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(252, 72);
			var tile289 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 1, 3, 32).UseFrame(270, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 108);
			var tile290 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 148, 2, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 144, 72);
			var tile291 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 100, 1, 16416).UseFrame(72, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 144, 36);
			var tile292 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 164, 2, 8224).UseFrame(72, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 144, 72);
			var tile293 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 83, 4, 32).UseFrame(0, 18).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 144);
			var tile294 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 131, 0, 4128).UseFrame(180, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 0);
			var tile295 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 4, 8224).UseFrame(144, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 72, 144);
			var tile296 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(306, 72);
			var tile297 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 12320).UseFrame(18, 72);
			var tile298 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 4128).UseFrame(90, 54);
			var tile299 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(126, 36);
			var tile300 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(144, 54);
			var tile301 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(252, 54);
			var tile302 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 0, 0, 32).UseFrame(108, 0);
			var tile303 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 0, 0, 32).UseFrame(90, 0);
			var tile304 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 82, 0, 32).UseFrame(90, 18).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 0);
			var tile305 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 147, 2, 32).UseFrame(36, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 108, 72);
			var tile306 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 131, 2, 32).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile307 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(288, 36);
			var tile308 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 12320).UseFrame(90, 72);
			var tile309 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(72, 18);
			var tile310 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 12320).UseFrame(18, 72);
			var tile311 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 54);
			var tile312 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 3, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 108);
			var tile313 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 98, 2, 32).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 72, 72);
			var tile314 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 0, 0, 32);
			var tile315 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 0, 0, 32).UseFrame(0, 18);
			var tile316 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 131, 0, 32).UseFrame(0, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 0);
			var tile317 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile318 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(54, 0);
			var tile319 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(306, 36);
			var tile320 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 133, 3, 16416).UseFrame(0, 72).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 180, 108);
			var tile321 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 154, 2, 32).UseFrame(126, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 72);
			var tile322 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 0, 4, 32).UseFrame(18, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 144);
			var tile323 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 18);
			var tile324 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 66, 0, 32).UseFrame(18, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 0);
			var tile325 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 131, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 72);
			var tile326 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 0, 0, 32).UseFrame(18, 0);
			var tile327 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(54, 0);
			var tile328 = new TileDefinitionStructure(TileID.HangingLanterns).UseHeaders(0, 136, 2, 32).UseFrame(0, 558).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 288, 72);
			var tile329 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 33, 1, 32).UseFrame(144, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 36, 36);
			var tile330 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 1, 2, 32).UseFrame(36, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 72);
			var tile331 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 0, 0, 32).UseFrame(36, 18);
			var tile332 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 1, 0, 32).UseFrame(36, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 0);
			var tile333 = new TileDefinitionStructure(ModContent.TileType<RustedShelf>()).UseHeaders(0, 1, 2, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 72);
			var tile334 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 136, 1, 32).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 288, 36);
			var tile335 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 75, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 396, 36);
			var tile336 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 131, 1, 32).UseFrame(54, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile337 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 64, 1, 32).UseFrame(54, 18).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 0, 36);
			var tile338 = new TileDefinitionStructure(ModContent.TileType<AgedLaboratoryDisplay>()).UseHeaders(0, 75, 1, 32).UseFrame(54, 36).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 396, 36);
			var tile339 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(306, 0);
			var tile340 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 1, 3, 16416).UseFrame(108, 54).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 36, 108);
			var tile341 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 10, 0, 32).UseFrame(108, 72).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 360, 0);
			var tile342 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<LaboratoryPanelWall>(), 108, 36);
			var tile343 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 131, 1, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 108, 36);
			var tile344 = new TileDefinitionStructure(ModContent.TileType<LaboratoryShelf>()).UseHeaders(0, 66, 2, 32).UseFrame(72, 0).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 72, 72);
			var tile345 = new TileDefinitionStructure(ModContent.TileType<RustedPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(216, 18);
			var tile346 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 16, 0, 32).UseFrame(36, 72);
			var tile347 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 133, 3, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 180, 108);
			var tile348 = new TileDefinitionStructure(ModContent.TileType<RustedPipes>()).UseHeaders(0, 4, 0, 32).UseFrame(216, 0).UseWall((ushort)ModContent.WallType<RustedPlatingWall>(), 144, 0);
			var tile349 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 68, 1, 8224).UseFrame(0, 54).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 144, 36);
			var tile350 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 1, 4, 32).UseWall((ushort)ModContent.WallType<HazardChevronWall>(), 36, 144);
			var tile351 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(72, 72);
			var tile352 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(306, 0);
			var tile353 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 32).UseFrame(90, 36);
			var tile354 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 0, 0, 32).UseFrame(306, 18);
			var tile355 = new TileDefinitionStructure(ModContent.TileType<LaboratoryPlating>()).UseHeaders(0, 32, 0, 12320).UseFrame(90, 72);
			Dictionary<Color, TileDefinitionStructure> colorTileMap = new Dictionary<Color, TileDefinitionStructure>()
			{
				{ new Color(0, 0, 0), tile1 },
				{ new Color(157, 140, 172), tile2 },
				{ new Color(50, 95, 63), tile3 },
				{ new Color(140, 9, 160), tile4 },
				{ new Color(8, 152, 177), tile5 },
				{ new Color(102, 12, 199), tile6 },
				{ new Color(218, 61, 146), tile7 },
				{ new Color(64, 185, 3), tile8 },
				{ new Color(219, 54, 168), tile9 },
				{ new Color(24, 155, 241), tile10 },
				{ new Color(42, 209, 210), tile11 },
				{ new Color(176, 205, 249), tile12 },
				{ new Color(224, 96, 74), tile13 },
				{ new Color(79, 209, 38), tile14 },
				{ new Color(168, 164, 143), tile15 },
				{ new Color(126, 250, 89), tile16 },
				{ new Color(138, 139, 47), tile17 },
				{ new Color(203, 79, 21), tile18 },
				{ new Color(143, 241, 164), tile19 },
				{ new Color(211, 193, 86), tile20 },
				{ new Color(4, 26, 195), tile21 },
				{ new Color(77, 97, 55), tile22 },
				{ new Color(206, 88, 203), tile23 },
				{ new Color(184, 133, 171), tile24 },
				{ new Color(124, 138, 108), tile25 },
				{ new Color(107, 152, 21), tile26 },
				{ new Color(116, 92, 59), tile27 },
				{ new Color(79, 142, 15), tile28 },
				{ new Color(194, 95, 130), tile29 },
				{ new Color(189, 33, 219), tile30 },
				{ new Color(85, 13, 158), tile31 },
				{ new Color(244, 75, 182), tile32 },
				{ new Color(98, 90, 66), tile33 },
				{ new Color(87, 176, 162), tile34 },
				{ new Color(141, 209, 6), tile35 },
				{ new Color(132, 78, 196), tile36 },
				{ new Color(168, 35, 89), tile37 },
				{ new Color(143, 94, 101), tile38 },
				{ new Color(26, 180, 140), tile39 },
				{ new Color(179, 139, 2), tile40 },
				{ new Color(181, 17, 54), tile41 },
				{ new Color(239, 99, 119), tile42 },
				{ new Color(12, 135, 63), tile43 },
				{ new Color(182, 9, 61), tile44 },
				{ new Color(210, 28, 172), tile45 },
				{ new Color(152, 193, 188), tile46 },
				{ new Color(9, 62, 16), tile47 },
				{ new Color(189, 20, 253), tile48 },
				{ new Color(130, 198, 174), tile49 },
				{ new Color(57, 218, 151), tile50 },
				{ new Color(41, 174, 207), tile51 },
				{ new Color(64, 162, 158), tile52 },
				{ new Color(108, 157, 110), tile53 },
				{ new Color(142, 119, 199), tile54 },
				{ new Color(133, 242, 26), tile55 },
				{ new Color(27, 188, 66), tile56 },
				{ new Color(184, 129, 242), tile57 },
				{ new Color(208, 170, 77), tile58 },
				{ new Color(242, 247, 253), tile59 },
				{ new Color(56, 109, 157), tile60 },
				{ new Color(200, 210, 173), tile61 },
				{ new Color(167, 140, 90), tile62 },
				{ new Color(109, 146, 122), tile63 },
				{ new Color(14, 44, 35), tile64 },
				{ new Color(77, 123, 198), tile65 },
				{ new Color(73, 56, 34), tile66 },
				{ new Color(227, 102, 9), tile67 },
				{ new Color(108, 129, 88), tile68 },
				{ new Color(164, 89, 4), tile69 },
				{ new Color(130, 78, 170), tile70 },
				{ new Color(161, 51, 48), tile71 },
				{ new Color(209, 197, 165), tile72 },
				{ new Color(25, 221, 102), tile73 },
				{ new Color(191, 173, 42), tile74 },
				{ new Color(200, 170, 84), tile75 },
				{ new Color(206, 130, 46), tile76 },
				{ new Color(134, 168, 191), tile77 },
				{ new Color(218, 85, 6), tile78 },
				{ new Color(147, 92, 81), tile79 },
				{ new Color(84, 3, 50), tile80 },
				{ new Color(86, 235, 68), tile81 },
				{ new Color(207, 108, 249), tile82 },
				{ new Color(243, 124, 181), tile83 },
				{ new Color(33, 47, 90), tile84 },
				{ new Color(188, 36, 184), tile85 },
				{ new Color(222, 164, 215), tile86 },
				{ new Color(4, 213, 215), tile87 },
				{ new Color(213, 251, 165), tile88 },
				{ new Color(235, 198, 221), tile89 },
				{ new Color(41, 61, 104), tile90 },
				{ new Color(83, 196, 218), tile91 },
				{ new Color(51, 105, 194), tile92 },
				{ new Color(230, 248, 61), tile93 },
				{ new Color(90, 219, 5), tile94 },
				{ new Color(120, 101, 120), tile95 },
				{ new Color(100, 30, 49), tile96 },
				{ new Color(78, 180, 184), tile97 },
				{ new Color(122, 80, 45), tile98 },
				{ new Color(91, 128, 240), tile99 },
				{ new Color(158, 228, 166), tile100 },
				{ new Color(27, 201, 63), tile101 },
				{ new Color(77, 205, 107), tile102 },
				{ new Color(128, 136, 186), tile103 },
				{ new Color(246, 248, 171), tile104 },
				{ new Color(153, 169, 250), tile105 },
				{ new Color(209, 93, 149), tile106 },
				{ new Color(44, 135, 167), tile107 },
				{ new Color(172, 219, 136), tile108 },
				{ new Color(176, 217, 115), tile109 },
				{ new Color(172, 216, 233), tile110 },
				{ new Color(209, 71, 20), tile111 },
				{ new Color(151, 63, 17), tile112 },
				{ new Color(198, 43, 152), tile113 },
				{ new Color(13, 228, 150), tile114 },
				{ new Color(118, 88, 188), tile115 },
				{ new Color(12, 224, 167), tile116 },
				{ new Color(51, 137, 34), tile117 },
				{ new Color(90, 113, 93), tile118 },
				{ new Color(254, 111, 238), tile119 },
				{ new Color(182, 156, 243), tile120 },
				{ new Color(248, 211, 176), tile121 },
				{ new Color(209, 36, 176), tile122 },
				{ new Color(151, 2, 105), tile123 },
				{ new Color(232, 11, 49), tile124 },
				{ new Color(253, 31, 162), tile125 },
				{ new Color(17, 54, 131), tile126 },
				{ new Color(204, 164, 248), tile127 },
				{ new Color(203, 121, 78), tile128 },
				{ new Color(198, 119, 213), tile129 },
				{ new Color(183, 152, 208), tile130 },
				{ new Color(35, 15, 143), tile131 },
				{ new Color(164, 21, 16), tile132 },
				{ new Color(229, 165, 51), tile133 },
				{ new Color(11, 116, 222), tile134 },
				{ new Color(61, 74, 125), tile135 },
				{ new Color(241, 93, 82), tile136 },
				{ new Color(186, 237, 56), tile137 },
				{ new Color(106, 234, 248), tile138 },
				{ new Color(250, 44, 90), tile139 },
				{ new Color(97, 10, 173), tile140 },
				{ new Color(218, 224, 105), tile141 },
				{ new Color(153, 196, 251), tile142 },
				{ new Color(162, 88, 10), tile143 },
				{ new Color(146, 43, 144), tile144 },
				{ new Color(79, 192, 47), tile145 },
				{ new Color(26, 141, 46), tile146 },
				{ new Color(208, 213, 25), tile147 },
				{ new Color(131, 252, 171), tile148 },
				{ new Color(151, 184, 37), tile149 },
				{ new Color(150, 169, 232), tile150 },
				{ new Color(182, 131, 154), tile151 },
				{ new Color(134, 49, 147), tile152 },
				{ new Color(116, 164, 133), tile153 },
				{ new Color(130, 78, 4), tile154 },
				{ new Color(72, 39, 193), tile155 },
				{ new Color(168, 27, 42), tile156 },
				{ new Color(201, 224, 158), tile157 },
				{ new Color(43, 144, 53), tile158 },
				{ new Color(147, 87, 227), tile159 },
				{ new Color(189, 2, 11), tile160 },
				{ new Color(214, 11, 174), tile161 },
				{ new Color(33, 220, 167), tile162 },
				{ new Color(245, 201, 143), tile163 },
				{ new Color(155, 165, 233), tile164 },
				{ new Color(169, 78, 134), tile165 },
				{ new Color(21, 59, 213), tile166 },
				{ new Color(233, 238, 157), tile167 },
				{ new Color(251, 205, 201), tile168 },
				{ new Color(74, 139, 243), tile169 },
				{ new Color(101, 243, 217), tile170 },
				{ new Color(175, 182, 161), tile171 },
				{ new Color(121, 172, 66), tile172 },
				{ new Color(85, 38, 75), tile173 },
				{ new Color(25, 178, 81), tile174 },
				{ new Color(155, 45, 58), tile175 },
				{ new Color(180, 130, 66), tile176 },
				{ new Color(175, 125, 28), tile177 },
				{ new Color(14, 212, 19), tile178 },
				{ new Color(110, 219, 62), tile179 },
				{ new Color(229, 215, 80), tile180 },
				{ new Color(180, 144, 214), tile181 },
				{ new Color(181, 235, 239), tile182 },
				{ new Color(72, 47, 162), tile183 },
				{ new Color(67, 192, 20), tile184 },
				{ new Color(137, 207, 59), tile185 },
				{ new Color(76, 95, 159), tile186 },
				{ new Color(143, 150, 9), tile187 },
				{ new Color(176, 181, 117), tile188 },
				{ new Color(189, 161, 226), tile189 },
				{ new Color(141, 11, 208), tile190 },
				{ new Color(4, 112, 79), tile191 },
				{ new Color(250, 101, 34), tile192 },
				{ new Color(123, 229, 65), tile193 },
				{ new Color(75, 107, 82), tile194 },
				{ new Color(159, 108, 189), tile195 },
				{ new Color(7, 133, 4), tile196 },
				{ new Color(216, 34, 123), tile197 },
				{ new Color(158, 85, 64), tile198 },
				{ new Color(71, 3, 218), tile199 },
				{ new Color(96, 247, 74), tile200 },
				{ new Color(12, 186, 35), tile201 },
				{ new Color(209, 62, 79), tile202 },
				{ new Color(197, 142, 106), tile203 },
				{ new Color(25, 208, 122), tile204 },
				{ new Color(94, 68, 42), tile205 },
				{ new Color(182, 17, 73), tile206 },
				{ new Color(183, 182, 27), tile207 },
				{ new Color(222, 181, 233), tile208 },
				{ new Color(85, 101, 27), tile209 },
				{ new Color(14, 179, 98), tile210 },
				{ new Color(72, 26, 237), tile211 },
				{ new Color(246, 62, 177), tile212 },
				{ new Color(47, 205, 45), tile213 },
				{ new Color(110, 66, 246), tile214 },
				{ new Color(153, 190, 81), tile215 },
				{ new Color(0, 64, 16), tile216 },
				{ new Color(22, 145, 242), tile217 },
				{ new Color(144, 169, 65), tile218 },
				{ new Color(46, 45, 5), tile219 },
				{ new Color(58, 124, 217), tile220 },
				{ new Color(52, 182, 219), tile221 },
				{ new Color(8, 209, 182), tile222 },
				{ new Color(140, 103, 5), tile223 },
				{ new Color(121, 135, 67), tile224 },
				{ new Color(28, 73, 115), tile225 },
				{ new Color(37, 69, 246), tile226 },
				{ new Color(151, 84, 37), tile227 },
				{ new Color(10, 248, 34), tile228 },
				{ new Color(111, 183, 113), tile229 },
				{ new Color(172, 200, 17), tile230 },
				{ new Color(171, 245, 81), tile231 },
				{ new Color(84, 57, 139), tile232 },
				{ new Color(26, 145, 237), tile233 },
				{ new Color(155, 116, 216), tile234 },
				{ new Color(10, 157, 10), tile235 },
				{ new Color(174, 116, 95), tile236 },
				{ new Color(205, 9, 232), tile237 },
				{ new Color(14, 162, 39), tile238 },
				{ new Color(179, 41, 190), tile239 },
				{ new Color(185, 152, 25), tile240 },
				{ new Color(69, 224, 159), tile241 },
				{ new Color(244, 205, 145), tile242 },
				{ new Color(242, 199, 16), tile243 },
				{ new Color(232, 10, 179), tile244 },
				{ new Color(8, 252, 224), tile245 },
				{ new Color(76, 255, 90), tile246 },
				{ new Color(24, 193, 66), tile247 },
				{ new Color(17, 222, 190), tile248 },
				{ new Color(40, 156, 83), tile249 },
				{ new Color(42, 160, 15), tile250 },
				{ new Color(205, 97, 248), tile251 },
				{ new Color(212, 86, 148), tile252 },
				{ new Color(57, 21, 207), tile253 },
				{ new Color(120, 188, 172), tile254 },
				{ new Color(79, 229, 255), tile255 },
				{ new Color(52, 5, 165), tile256 },
				{ new Color(71, 102, 42), tile257 },
				{ new Color(99, 160, 214), tile258 },
				{ new Color(215, 51, 1), tile259 },
				{ new Color(224, 204, 48), tile260 },
				{ new Color(62, 200, 38), tile261 },
				{ new Color(0, 26, 168), tile262 },
				{ new Color(187, 52, 166), tile263 },
				{ new Color(75, 18, 234), tile264 },
				{ new Color(139, 159, 5), tile265 },
				{ new Color(149, 193, 248), tile266 },
				{ new Color(191, 243, 150), tile267 },
				{ new Color(174, 226, 57), tile268 },
				{ new Color(229, 106, 192), tile269 },
				{ new Color(34, 252, 34), tile270 },
				{ new Color(147, 89, 73), tile271 },
				{ new Color(159, 58, 243), tile272 },
				{ new Color(134, 79, 203), tile273 },
				{ new Color(86, 121, 209), tile274 },
				{ new Color(254, 251, 84), tile275 },
				{ new Color(64, 216, 1), tile276 },
				{ new Color(208, 65, 113), tile277 },
				{ new Color(8, 32, 217), tile278 },
				{ new Color(153, 144, 229), tile279 },
				{ new Color(236, 26, 176), tile280 },
				{ new Color(231, 152, 55), tile281 },
				{ new Color(132, 184, 185), tile282 },
				{ new Color(160, 236, 101), tile283 },
				{ new Color(17, 15, 114), tile284 },
				{ new Color(45, 105, 121), tile285 },
				{ new Color(197, 175, 230), tile286 },
				{ new Color(229, 165, 145), tile287 },
				{ new Color(191, 81, 187), tile288 },
				{ new Color(176, 138, 56), tile289 },
				{ new Color(111, 5, 169), tile290 },
				{ new Color(14, 153, 52), tile291 },
				{ new Color(26, 110, 224), tile292 },
				{ new Color(153, 122, 67), tile293 },
				{ new Color(154, 159, 236), tile294 },
				{ new Color(155, 191, 49), tile295 },
				{ new Color(254, 219, 183), tile296 },
				{ new Color(95, 211, 224), tile297 },
				{ new Color(254, 7, 117), tile298 },
				{ new Color(30, 39, 71), tile299 },
				{ new Color(124, 211, 46), tile300 },
				{ new Color(128, 48, 230), tile301 },
				{ new Color(187, 3, 118), tile302 },
				{ new Color(62, 19, 250), tile303 },
				{ new Color(152, 44, 53), tile304 },
				{ new Color(163, 74, 6), tile305 },
				{ new Color(165, 36, 145), tile306 },
				{ new Color(137, 178, 175), tile307 },
				{ new Color(129, 16, 49), tile308 },
				{ new Color(200, 15, 146), tile309 },
				{ new Color(190, 251, 70), tile310 },
				{ new Color(153, 28, 167), tile311 },
				{ new Color(21, 26, 110), tile312 },
				{ new Color(5, 223, 187), tile313 },
				{ new Color(187, 192, 200), tile314 },
				{ new Color(189, 198, 167), tile315 },
				{ new Color(171, 91, 188), tile316 },
				{ new Color(111, 121, 3), tile317 },
				{ new Color(181, 242, 33), tile318 },
				{ new Color(126, 255, 32), tile319 },
				{ new Color(181, 243, 243), tile320 },
				{ new Color(228, 127, 23), tile321 },
				{ new Color(179, 255, 15), tile322 },
				{ new Color(141, 141, 48), tile323 },
				{ new Color(151, 160, 69), tile324 },
				{ new Color(214, 206, 241), tile325 },
				{ new Color(231, 195, 73), tile326 },
				{ new Color(138, 29, 180), tile327 },
				{ new Color(214, 79, 130), tile328 },
				{ new Color(67, 227, 42), tile329 },
				{ new Color(133, 150, 26), tile330 },
				{ new Color(77, 80, 236), tile331 },
				{ new Color(200, 215, 64), tile332 },
				{ new Color(176, 9, 199), tile333 },
				{ new Color(151, 29, 205), tile334 },
				{ new Color(139, 215, 216), tile335 },
				{ new Color(189, 223, 36), tile336 },
				{ new Color(47, 151, 59), tile337 },
				{ new Color(214, 42, 214), tile338 },
				{ new Color(63, 13, 48), tile339 },
				{ new Color(148, 111, 28), tile340 },
				{ new Color(229, 8, 247), tile341 },
				{ new Color(22, 74, 80), tile342 },
				{ new Color(88, 13, 246), tile343 },
				{ new Color(176, 54, 186), tile344 },
				{ new Color(130, 242, 255), tile345 },
				{ new Color(230, 74, 119), tile346 },
				{ new Color(170, 133, 3), tile347 },
				{ new Color(6, 86, 254), tile348 },
				{ new Color(222, 118, 37), tile349 },
				{ new Color(22, 136, 201), tile350 },
				{ new Color(16, 28, 153), tile351 },
				{ new Color(170, 178, 21), tile352 },
				{ new Color(214, 116, 141), tile353 },
				{ new Color(136, 101, 209), tile354 },
				{ new Color(45, 126, 97), tile355 },
			};
			return new ColorTileMap(colorTileMap);
		}
	}
}
