using CalamityMod.Tiles.FurniturePlaguedPlate;
using CalamityMod.Tiles.FurnitureVoid;
using Microsoft.Xna.Framework;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Terraria.ID;
using Terraria.ModLoader;

namespace CalamityMod.Schematics.AutoGeneratedContent
{
    public class WorkshopSchematic
	{
		[GeneratedCode("ScreenCaptureToSchematic", "1.0.1")]
		public static ColorTileMap GetMap()
		{
			var tile1 = new TileDefinitionStructure(TileID.Dirt, false).UseHeaders(0, 0, 0, 0);
			var tile2 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 54).UseSlope(2).UseHeaders(0, 32, 0, 8224);
			var tile3 = new TileDefinitionStructure(TileID.TinPlating).UseHeaders(0, 16, 0, 32);
			var tile4 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(90, 126).UseHeaders(0, 16, 0, 32);
			var tile5 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(90, 36).UseHeaders(0, 16, 0, 32);
			var tile6 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(90, 18).UseHeaders(0, 32, 0, 32);
			var tile7 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(90, 0).UseHeaders(0, 0, 0, 32);
			var tile8 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(90, 126).UseHeaders(0, 0, 0, 32);
			var tile9 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 36).UseHeaders(0, 0, 0, 32);
			var tile10 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 18).UseHeaders(0, 16, 0, 32);
			var tile11 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 72).UseSlope(4).UseHeaders(0, 0, 0, 16416);
			var tile12 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 0).UseHeaders(0, 0, 0, 32);
			var tile13 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 36).UseHeaders(0, 0, 0, 32);
			var tile14 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 0, 108).UseHeaders(0, 0, 3, 0);
			var tile15 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 0, 36).UseHeaders(0, 64, 1, 0);
			var tile16 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 0, 144).UseFrame(18, 54).UseSlope(1).UseHeaders(0, 16, 4, 4128);
			var tile17 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 18).UseHeaders(0, 0, 0, 32);
			var tile18 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 36).UseHeaders(0, 32, 0, 32);
			var tile19 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 54).UseSlope(2).UseHeaders(0, 32, 0, 8224);
			var tile20 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 108).UseHeaders(0, 16, 0, 32);
			var tile21 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 144, 108).UseFrame(90, 72).UseSlope(3).UseHeaders(0, 132, 3, 12320);
			var tile22 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 0, 0).UseHeaders(0, 0, 0, 0);
			var tile23 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 0, 180).UseHeaders(0, 192, 5, 0);
			var tile24 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 396, 72).UseHeaders(0, 139, 2, 0);
			var tile25 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 72, 36).UseFrame(36, 0).UseHeaders(0, 66, 1, 32);
			var tile26 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 216, 36).UseFrame(36, 18).UseHeaders(0, 6, 1, 32);
			var tile27 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 72, 216).UseFrame(54, 162).UseHeaders(0, 194, 6, 32);
			var tile28 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(144, 72).UseHeaders(0, 0, 0, 32);
			var tile29 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 0).UseHeaders(0, 32, 0, 32);
			var tile30 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 36).UseHeaders(0, 16, 0, 32);
			var tile31 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 36, 108).UseHeaders(0, 1, 3, 0);
			var tile32 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 72, 180).UseHeaders(0, 194, 5, 0);
			var tile33 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 144, 72).UseHeaders(0, 132, 2, 0);
			var tile34 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 144, 36).UseHeaders(0, 68, 1, 0);
			var tile35 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 36, 36).UseHeaders(0, 1, 1, 0);
			var tile36 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 144, 180).UseFrame(54, 0).UseHeaders(0, 196, 5, 32);
			var tile37 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 360, 72).UseFrame(54, 18).UseHeaders(0, 138, 2, 32);
			var tile38 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 72, 72).UseFrame(0, 162).UseHeaders(0, 66, 2, 32);
			var tile39 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(108, 72).UseHeaders(0, 16, 0, 32);
			var tile40 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 0).UseHeaders(0, 32, 0, 32);
			var tile41 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 36).UseHeaders(0, 32, 0, 32);
			var tile42 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLantern>()).UseHeaders(0, 0, 0, 32);
			var tile43 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLantern>()).UseWall(WallID.TinPlating, 432, 36).UseFrame(0, 18).UseHeaders(0, 76, 1, 32);
			var tile44 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseWall(WallID.TinPlating, 216, 144).UseHeaders(0, 6, 4, 32);
			var tile45 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseFrame(0, 18).UseHeaders(0, 0, 0, 32);
			var tile46 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseWall(WallID.TinPlating, 36, 0).UseFrame(0, 36).UseHeaders(0, 1, 0, 32);
			var tile47 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(108, 72).UseHeaders(0, 0, 0, 32);
			var tile48 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 324, 180).UseFrame(90, 162).UseSlope(3).UseHeaders(0, 217, 5, 12320);
			var tile49 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseWall(WallID.TinPlating, 180, 108).UseFrame(18, 0).UseHeaders(0, 133, 3, 32);
			var tile50 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseWall(WallID.TinPlating, 180, 36).UseFrame(18, 18).UseHeaders(0, 69, 1, 32);
			var tile51 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseWall(WallID.TinPlating, 216, 36).UseFrame(18, 36).UseHeaders(0, 6, 1, 32);
			var tile52 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 108, 180).UseFrame(0, 162).UseHeaders(0, 195, 5, 32);
			var tile53 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(144, 72).UseHeaders(0, 16, 0, 32);
			var tile54 = new TileDefinitionStructure(TileID.Platforms).UseFrame(36, 162).UseHeaders(0, 0, 0, 32);
			var tile55 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 72, 0).UseHeaders(0, 66, 0, 0);
			var tile56 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 216, 108).UseHeaders(0, 6, 3, 0);
			var tile57 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseFrame(36, 0).UseHeaders(0, 0, 0, 32);
			var tile58 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseFrame(36, 18).UseHeaders(0, 0, 0, 32);
			var tile59 = new TileDefinitionStructure(TileID.SteampunkBoiler).UseWall(WallID.TinPlating, 108, 0).UseFrame(36, 36).UseHeaders(0, 131, 0, 32);
			var tile60 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 108, 144).UseFrame(0, 162).UseHeaders(0, 67, 4, 32);
			var tile61 = new TileDefinitionStructure(TileID.Platforms).UseFrame(72, 162).UseHeaders(0, 0, 0, 32);
			var tile62 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 252, 144).UseHeaders(0, 71, 4, 0);
			var tile63 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 216, 144).UseFrame(144, 162).UseSlope(2).UseHeaders(0, 6, 4, 8224);
			var tile64 = new TileDefinitionStructure(TileID.Platforms).UseFrame(234, 162).UseHeaders(0, 0, 0, 32);
			var tile65 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 0).UseHeaders(0, 16, 0, 32);
			var tile66 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 72).UseSlope(4).UseHeaders(0, 16, 0, 16416);
			var tile67 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLamp>()).UseHeaders(0, 0, 0, 32);
			var tile68 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLamp>()).UseFrame(0, 18).UseHeaders(0, 0, 0, 32);
			var tile69 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLamp>()).UseFrame(0, 36).UseHeaders(0, 0, 0, 32);
			var tile70 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 54).UseHeaders(0, 16, 0, 32);
			var tile71 = new TileDefinitionStructure(TileID.TinPlating).UseHeaders(0, 32, 0, 32);
			var tile72 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 72).UseSlope(4).UseHeaders(0, 32, 0, 16416);
			var tile73 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 54).UseHeaders(0, 32, 0, 32);
			var tile74 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 180, 216).UseHeaders(0, 197, 6, 0);
			var tile75 = new TileDefinitionStructure(TileID.Platforms).UseFrame(144, 162).UseSlope(2).UseHeaders(0, 0, 0, 8224);
			var tile76 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 432, 0).UseHeaders(0, 12, 0, 0);
			var tile77 = new TileDefinitionStructure(TileID.Platforms).UseFrame(180, 162).UseSlope(1).UseHeaders(0, 0, 0, 4128);
			var tile78 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 324, 72).UseFrame(90, 54).UseSlope(1).UseHeaders(0, 137, 2, 4128);
			var tile79 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 18).UseHeaders(0, 32, 0, 32);
			var tile80 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 54).UseSlope(2).UseHeaders(0, 16, 0, 8224);
			var tile81 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 18).UseHeaders(0, 16, 0, 32);
			var tile82 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 18).UseHeaders(0, 16, 0, 32);
			var tile83 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 108).UseHeaders(0, 0, 0, 32);
			var tile84 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 36).UseHeaders(0, 16, 0, 32);
			var tile85 = new TileDefinitionStructure(TileID.TallGateClosed).UseHeaders(0, 0, 0, 32);
			var tile86 = new TileDefinitionStructure(TileID.TallGateClosed).UseFrame(0, 20).UseHeaders(0, 0, 0, 32);
			var tile87 = new TileDefinitionStructure(TileID.TallGateClosed).UseFrame(0, 38).UseHeaders(0, 0, 0, 32);
			var tile88 = new TileDefinitionStructure(TileID.TallGateClosed).UseFrame(0, 56).UseHeaders(0, 0, 0, 32);
			var tile89 = new TileDefinitionStructure(TileID.TallGateClosed).UseFrame(0, 74).UseHeaders(0, 0, 0, 32);
			var tile90 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 72).UseSlope(4).UseHeaders(0, 32, 0, 16416);
			var tile91 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 216, 216).UseHeaders(0, 198, 6, 0);
			var tile92 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 252, 0).UseHeaders(0, 71, 0, 0);
			var tile93 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 144, 0).UseFrame(180, 162).UseSlope(1).UseHeaders(0, 4, 0, 4128);
			var tile94 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 72, 216).UseFrame(90, 144).UseSlope(1).UseHeaders(0, 210, 6, 4128);
			var tile95 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 18).UseHeaders(0, 32, 0, 32);
			var tile96 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile97 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 18).UseHeaders(0, 0, 0, 32);
			var tile98 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 18).UseHeaders(0, 16, 0, 32);
			var tile99 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 72).UseSlope(3).UseHeaders(0, 32, 0, 12320);
			var tile100 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 288, 0).UseHeaders(0, 136, 0, 0);
			var tile101 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 180, 0).UseHeaders(0, 5, 0, 0);
			var tile102 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 144, 144).UseFrame(90, 54).UseSlope(1).UseHeaders(0, 164, 4, 4128);
			var tile103 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 36).UseHeaders(0, 16, 0, 32);
			var tile104 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(108, 72).UseHeaders(0, 32, 0, 32);
			var tile105 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 324, 0).UseHeaders(0, 9, 0, 0);
			var tile106 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateWorkbench>()).UseHeaders(0, 0, 0, 32);
			var tile107 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 324, 108).UseFrame(216, 162).UseHeaders(0, 9, 3, 32);
			var tile108 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 432, 36).UseFrame(180, 162).UseSlope(1).UseHeaders(0, 76, 1, 4128);
			var tile109 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 54).UseSlope(1).UseHeaders(0, 32, 0, 4128);
			var tile110 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 0, 108).UseFrame(18, 72).UseSlope(3).UseHeaders(0, 32, 3, 12320);
			var tile111 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 180, 36).UseHeaders(0, 69, 1, 0);
			var tile112 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 432, 36).UseHeaders(0, 76, 1, 32);
			var tile113 = new TileDefinitionStructure(TileID.FishingCrate).UseFrame(0, 18).UseHeaders(0, 0, 0, 32);
			var tile114 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 72, 0).UseHeaders(0, 66, 0, 32);
			var tile115 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 36, 72).UseFrame(0, 18).UseHeaders(0, 1, 2, 32);
			var tile116 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 0).UseHeaders(0, 16, 0, 32);
			var tile117 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 36, 144).UseHeaders(0, 1, 4, 0);
			var tile118 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateWorkbench>()).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile119 = new TileDefinitionStructure(TileID.Platforms).UseFrame(0, 162).UseHeaders(0, 0, 0, 32);
			var tile120 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 324, 0).UseFrame(180, 162).UseSlope(1).UseHeaders(0, 9, 0, 4128);
			var tile121 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 72, 108).UseFrame(54, 72).UseSlope(3).UseHeaders(0, 82, 3, 12320);
			var tile122 = new TileDefinitionStructure(TileID.FishingCrate).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile123 = new TileDefinitionStructure(TileID.FishingCrate).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile124 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 72, 0).UseFrame(18, 0).UseHeaders(0, 66, 0, 32);
			var tile125 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 36, 72).UseFrame(18, 18).UseHeaders(0, 1, 2, 32);
			var tile126 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 90).UseHeaders(0, 0, 0, 32);
			var tile127 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 36).UseHeaders(0, 0, 0, 32);
			var tile128 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 0, 144).UseHeaders(0, 0, 4, 0);
			var tile129 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 108, 0).UseHeaders(0, 131, 0, 0);
			var tile130 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 72, 144).UseFrame(180, 162).UseSlope(1).UseHeaders(0, 66, 4, 4128);
			var tile131 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 216, 0).UseHeaders(0, 6, 0, 0);
			var tile132 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 360, 180).UseHeaders(0, 202, 5, 32);
			var tile133 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 180, 144).UseFrame(0, 18).UseHeaders(0, 133, 4, 32);
			var tile134 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 0).UseHeaders(0, 32, 0, 32);
			var tile135 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 144, 0).UseHeaders(0, 4, 0, 0);
			var tile136 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 252, 108).UseHeaders(0, 71, 3, 0);
			var tile137 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateWorkbench>()).UseWall(WallID.TinPlating, 360, 108).UseFrame(18, 0).UseHeaders(0, 74, 3, 32);
			var tile138 = new TileDefinitionStructure(TileID.TinkerersWorkbench).UseWall(WallID.TinPlating, 36, 108).UseHeaders(0, 1, 3, 32);
			var tile139 = new TileDefinitionStructure(TileID.TinkerersWorkbench).UseWall(WallID.TinPlating, 252, 72).UseFrame(0, 18).UseHeaders(0, 71, 2, 32);
			var tile140 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 0, 0).UseFrame(216, 0).UseHeaders(0, 16, 0, 32);
			var tile141 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLantern>()).UseWall(WallID.TinPlating, 72, 72).UseHeaders(0, 66, 2, 32);
			var tile142 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLantern>()).UseFrame(0, 18).UseHeaders(0, 0, 0, 32);
			var tile143 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 252, 144).UseFrame(18, 0).UseHeaders(0, 71, 4, 32);
			var tile144 = new TileDefinitionStructure(TileID.TinkerersWorkbench).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile145 = new TileDefinitionStructure(TileID.TinkerersWorkbench).UseWall(WallID.TinPlating, 36, 216).UseFrame(18, 18).UseHeaders(0, 193, 6, 32);
			var tile146 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 144, 72).UseFrame(54, 162).UseHeaders(0, 132, 2, 32);
			var tile147 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 108, 144).UseHeaders(0, 67, 4, 0);
			var tile148 = new TileDefinitionStructure(TileID.Solidifier).UseHeaders(0, 0, 0, 32);
			var tile149 = new TileDefinitionStructure(TileID.Solidifier).UseWall(WallID.TinPlating, 432, 36).UseFrame(0, 18).UseHeaders(0, 76, 1, 32);
			var tile150 = new TileDefinitionStructure(TileID.Solidifier).UseFrame(0, 36).UseHeaders(0, 0, 0, 32);
			var tile151 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 90).UseHeaders(0, 16, 0, 32);
			var tile152 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 324, 36).UseHeaders(0, 73, 1, 0);
			var tile153 = new TileDefinitionStructure(TileID.TinkerersWorkbench).UseFrame(36, 0).UseHeaders(0, 0, 0, 32);
			var tile154 = new TileDefinitionStructure(TileID.TinkerersWorkbench).UseFrame(36, 18).UseHeaders(0, 0, 0, 32);
			var tile155 = new TileDefinitionStructure(TileID.Solidifier).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile156 = new TileDefinitionStructure(TileID.Solidifier).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile157 = new TileDefinitionStructure(TileID.Solidifier).UseFrame(18, 36).UseHeaders(0, 0, 0, 32);
			var tile158 = new TileDefinitionStructure(ModContent.TileType<VoidChest>()).UseHeaders(0, 0, 0, 32);
			var tile159 = new TileDefinitionStructure(ModContent.TileType<VoidChest>()).UseWall(WallID.TinPlating, 432, 36).UseFrame(0, 18).UseHeaders(0, 76, 1, 32);
			var tile160 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 324, 108).UseHeaders(0, 9, 3, 0);
			var tile161 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 324, 0).UseFrame(0, 162).UseHeaders(0, 9, 0, 32);
			var tile162 = new TileDefinitionStructure(TileID.Solidifier).UseFrame(36, 0).UseHeaders(0, 0, 0, 32);
			var tile163 = new TileDefinitionStructure(TileID.Solidifier).UseWall(WallID.TinPlating, 252, 0).UseFrame(36, 18).UseHeaders(0, 71, 0, 32);
			var tile164 = new TileDefinitionStructure(TileID.Solidifier).UseWall(WallID.TinPlating, 0, 144).UseFrame(36, 36).UseHeaders(0, 0, 4, 32);
			var tile165 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 36, 216).UseHeaders(0, 193, 6, 0);
			var tile166 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 144, 144).UseHeaders(0, 132, 4, 0);
			var tile167 = new TileDefinitionStructure(ModContent.TileType<VoidChest>()).UseFrame(18, 0).UseHeaders(0, 0, 0, 32);
			var tile168 = new TileDefinitionStructure(ModContent.TileType<VoidChest>()).UseFrame(18, 18).UseHeaders(0, 0, 0, 32);
			var tile169 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateWorkbench>()).UseWall(WallID.TinPlating, 0, 216).UseHeaders(0, 192, 6, 32);
			var tile170 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 288, 36).UseFrame(0, 162).UseHeaders(0, 136, 1, 32);
			var tile171 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 72, 144).UseHeaders(0, 66, 4, 0);
			var tile172 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 216, 144).UseHeaders(0, 6, 4, 0);
			var tile173 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 90).UseHeaders(0, 32, 0, 32);
			var tile174 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 144, 216).UseHeaders(0, 196, 6, 0);
			var tile175 = new TileDefinitionStructure(TileID.FishingCrate).UseFrame(36, 0).UseHeaders(0, 0, 0, 32);
			var tile176 = new TileDefinitionStructure(TileID.FishingCrate).UseFrame(36, 18).UseHeaders(0, 0, 0, 32);
			var tile177 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateWorkbench>()).UseWall(WallID.TinPlating, 108, 108).UseFrame(18, 0).UseHeaders(0, 67, 3, 32);
			var tile178 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 360, 0).UseFrame(0, 162).UseHeaders(0, 10, 0, 32);
			var tile179 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 108, 180).UseHeaders(0, 195, 5, 0);
			var tile180 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 288, 144).UseHeaders(0, 136, 4, 0);
			var tile181 = new TileDefinitionStructure(TileID.FishingCrate).UseFrame(54, 0).UseHeaders(0, 0, 0, 32);
			var tile182 = new TileDefinitionStructure(TileID.FishingCrate).UseFrame(54, 18).UseHeaders(0, 0, 0, 32);
			var tile183 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 324, 0).UseFrame(54, 18).UseHeaders(0, 9, 0, 32);
			var tile184 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 36, 0).UseFrame(72, 162).UseHeaders(0, 1, 0, 32);
			var tile185 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 72, 72).UseHeaders(0, 66, 2, 0);
			var tile186 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 36, 72).UseHeaders(0, 1, 2, 0);
			var tile187 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 360, 108).UseHeaders(0, 74, 3, 0);
			var tile188 = new TileDefinitionStructure(TileID.Anvils).UseFrame(36, 0).UseHeaders(0, 0, 0, 32);
			var tile189 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 72, 108).UseHeaders(0, 66, 3, 0);
			var tile190 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 396, 0).UseHeaders(0, 11, 0, 0);
			var tile191 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateWorkbench>()).UseWall(WallID.TinPlating, 0, 180).UseFrame(18, 0).UseHeaders(0, 192, 5, 32);
			var tile192 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 288, 36).UseFrame(162, 36).UseHeaders(0, 136, 1, 32);
			var tile193 = new TileDefinitionStructure(TileID.FishingCrate).UseHeaders(0, 0, 0, 32);
			var tile194 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 216, 144).UseFrame(0, 18).UseHeaders(0, 6, 4, 32);
			var tile195 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 36).UseHeaders(0, 32, 0, 32);
			var tile196 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(144, 72).UseHeaders(0, 32, 0, 32);
			var tile197 = new TileDefinitionStructure(TileID.Anvils).UseFrame(54, 0).UseHeaders(0, 0, 0, 32);
			var tile198 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 432, 180).UseHeaders(0, 204, 5, 0);
			var tile199 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 144, 180).UseHeaders(0, 196, 5, 0);
			var tile200 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 72, 36).UseFrame(144, 162).UseSlope(2).UseHeaders(0, 66, 1, 8224);
			var tile201 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 360, 0).UseFrame(108, 72).UseHeaders(0, 10, 0, 32);
			var tile202 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 0, 108).UseFrame(54, 18).UseHeaders(0, 0, 3, 32);
			var tile203 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 0, 180).UseFrame(18, 0).UseHeaders(0, 192, 5, 32);
			var tile204 = new TileDefinitionStructure(TileID.FishingCrate).UseWall(WallID.TinPlating, 108, 72).UseFrame(18, 18).UseHeaders(0, 131, 2, 32);
			var tile205 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 72, 36).UseHeaders(0, 66, 1, 0);
			var tile206 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 108, 108).UseHeaders(0, 67, 3, 0);
			var tile207 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 144, 0).UseFrame(18, 0).UseHeaders(0, 4, 0, 32);
			var tile208 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 144, 36).UseFrame(36, 72).UseSlope(4).UseHeaders(0, 68, 1, 16416);
			var tile209 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 216, 72).UseHeaders(0, 6, 2, 0);
			var tile210 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 288, 36).UseHeaders(0, 136, 1, 0);
			var tile211 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 216, 36).UseHeaders(0, 6, 1, 0);
			var tile212 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 396, 180).UseHeaders(0, 203, 5, 0);
			var tile213 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 108, 36).UseHeaders(0, 131, 1, 0);
			var tile214 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 0, 36).UseFrame(144, 162).UseSlope(2).UseHeaders(0, 64, 1, 8224);
			var tile215 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 216, 108).UseFrame(0, 54).UseSlope(2).UseHeaders(0, 6, 3, 8224);
			var tile216 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 126).UseHeaders(0, 0, 0, 32);
			var tile217 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 36, 108).UseFrame(0, 72).UseSlope(4).UseHeaders(0, 17, 3, 16416);
			var tile218 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 180, 180).UseHeaders(0, 197, 5, 0);
			var tile219 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 108, 72).UseHeaders(0, 131, 2, 0);
			var tile220 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 252, 36).UseHeaders(0, 71, 1, 0);
			var tile221 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 360, 0).UseHeaders(0, 10, 0, 0);
			var tile222 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 360, 72).UseHeaders(0, 138, 2, 0);
			var tile223 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 36, 36).UseFrame(144, 162).UseSlope(2).UseHeaders(0, 1, 1, 8224);
			var tile224 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 108, 216).UseFrame(72, 144).UseSlope(2).UseHeaders(0, 195, 6, 8224);
			var tile225 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 18).UseHeaders(0, 32, 0, 32);
			var tile226 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 18).UseHeaders(0, 32, 0, 32);
			var tile227 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 108).UseHeaders(0, 32, 0, 32);
			var tile228 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 18).UseHeaders(0, 32, 0, 32);
			var tile229 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 288, 108).UseHeaders(0, 136, 3, 0);
			var tile230 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 180, 144).UseFrame(72, 54).UseSlope(2).UseHeaders(0, 133, 4, 8224);
			var tile231 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 36, 0).UseHeaders(0, 1, 0, 0);
			var tile232 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 36, 144).UseFrame(0, 54).UseSlope(2).UseHeaders(0, 33, 4, 8224);
			var tile233 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 72).UseSlope(3).UseHeaders(0, 16, 0, 12320);
			var tile234 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(36, 18).UseHeaders(0, 0, 0, 32);
			var tile235 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 396, 108).UseHeaders(0, 139, 3, 0);
			var tile236 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 36, 0).UseFrame(180, 162).UseSlope(1).UseHeaders(0, 1, 0, 4128);
			var tile237 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 108, 180).UseFrame(216, 162).UseHeaders(0, 195, 5, 32);
			var tile238 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 0).UseHeaders(0, 16, 0, 32);
			var tile239 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 72).UseSlope(3).UseHeaders(0, 16, 0, 12320);
			var tile240 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 54).UseHeaders(0, 16, 0, 32);
			var tile241 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 0).UseHeaders(0, 0, 0, 32);
			var tile242 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 126).UseHeaders(0, 32, 0, 32);
			var tile243 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(90, 72).UseSlope(3).UseHeaders(0, 16, 0, 12320);
			var tile244 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 54).UseHeaders(0, 0, 0, 32);
			var tile245 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(90, 162).UseSlope(3).UseHeaders(0, 32, 0, 12320);
			var tile246 = new TileDefinitionStructure(TileID.Dirt, false).UseWall(WallID.TinPlating, 0, 216).UseHeaders(0, 192, 6, 0);
			var tile247 = new TileDefinitionStructure(TileID.Platforms).UseFrame(54, 162).UseHeaders(0, 0, 0, 32);
			var tile248 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 108, 108).UseFrame(36, 72).UseSlope(4).UseHeaders(0, 99, 3, 16416);
			var tile249 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseWall(WallID.TinPlating, 0, 108).UseHeaders(0, 0, 3, 32);
			var tile250 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseWall(WallID.TinPlating, 252, 72).UseFrame(0, 18).UseHeaders(0, 71, 2, 32);
			var tile251 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseWall(WallID.TinPlating, 36, 36).UseFrame(0, 36).UseHeaders(0, 1, 1, 32);
			var tile252 = new TileDefinitionStructure(TileID.Platforms).UseFrame(18, 162).UseHeaders(0, 0, 0, 32);
			var tile253 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 126).UseHeaders(0, 32, 0, 32);
			var tile254 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLantern>()).UseWall(WallID.TinPlating, 108, 0).UseHeaders(0, 131, 0, 32);
			var tile255 = new TileDefinitionStructure(ModContent.TileType<PlaguedPlateLantern>()).UseWall(WallID.TinPlating, 72, 72).UseFrame(0, 18).UseHeaders(0, 66, 2, 32);
			var tile256 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseWall(WallID.TinPlating, 108, 0).UseFrame(18, 0).UseHeaders(0, 131, 0, 32);
			var tile257 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseWall(WallID.TinPlating, 144, 36).UseFrame(18, 18).UseHeaders(0, 68, 1, 32);
			var tile258 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseWall(WallID.TinPlating, 216, 36).UseFrame(18, 36).UseHeaders(0, 6, 1, 32);
			var tile259 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseWall(WallID.TinPlating, 216, 144).UseFrame(36, 0).UseHeaders(0, 6, 4, 32);
			var tile260 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseFrame(36, 18).UseHeaders(0, 0, 0, 32);
			var tile261 = new TileDefinitionStructure(TileID.HeavyWorkBench).UseWall(WallID.TinPlating, 108, 0).UseFrame(36, 36).UseHeaders(0, 131, 0, 32);
			var tile262 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(18, 54).UseSlope(1).UseHeaders(0, 0, 0, 4128);
			var tile263 = new TileDefinitionStructure(TileID.TinPlating).UseWall(WallID.TinPlating, 36, 108).UseFrame(0, 72).UseSlope(4).UseHeaders(0, 33, 3, 16416);
			var tile264 = new TileDefinitionStructure(TileID.Platforms).UseWall(WallID.TinPlating, 108, 144).UseFrame(72, 162).UseHeaders(0, 67, 4, 32);
			var tile265 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(0, 126).UseHeaders(0, 16, 0, 32);
			var tile266 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(54, 54).UseSlope(1).UseHeaders(0, 32, 0, 4128);
			var tile267 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 0).UseHeaders(0, 16, 0, 32);
			var tile268 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(90, 126).UseHeaders(0, 32, 0, 32);
			var tile269 = new TileDefinitionStructure(TileID.TinPlating).UseFrame(72, 36).UseHeaders(0, 0, 0, 32);
			Dictionary<Color, TileDefinitionStructure> colorTileMap = new Dictionary<Color, TileDefinitionStructure>()
				{
					{ new Color(255, 255, 255), tile1},
					{ new Color(252, 121, 99), tile2},
					{ new Color(242, 71, 169), tile3},
					{ new Color(86, 71, 29), tile4},
					{ new Color(45, 149, 46), tile5},
					{ new Color(169, 41, 205), tile6},
					{ new Color(46, 102, 64), tile7},
					{ new Color(62, 97, 176), tile8},
					{ new Color(63, 102, 198), tile9},
					{ new Color(197, 184, 30), tile10},
					{ new Color(85, 232, 204), tile11},
					{ new Color(122, 100, 163), tile12},
					{ new Color(207, 132, 243), tile13},
					{ new Color(134, 145, 189), tile14},
					{ new Color(41, 147, 33), tile15},
					{ new Color(212, 118, 13), tile16},
					{ new Color(188, 182, 217), tile17},
					{ new Color(238, 124, 57), tile18},
					{ new Color(98, 214, 224), tile19},
					{ new Color(19, 189, 18), tile20},
					{ new Color(157, 44, 143), tile21},
					{ new Color(139, 1, 94), tile22},
					{ new Color(80, 178, 48), tile23},
					{ new Color(139, 217, 164), tile24},
					{ new Color(217, 168, 212), tile25},
					{ new Color(130, 21, 205), tile26},
					{ new Color(143, 106, 240), tile27},
					{ new Color(184, 9, 1), tile28},
					{ new Color(68, 102, 108), tile29},
					{ new Color(147, 23, 141), tile30},
					{ new Color(194, 188, 199), tile31},
					{ new Color(224, 232, 100), tile32},
					{ new Color(46, 158, 146), tile33},
					{ new Color(194, 132, 195), tile34},
					{ new Color(221, 48, 221), tile35},
					{ new Color(53, 20, 211), tile36},
					{ new Color(100, 224, 193), tile37},
					{ new Color(18, 132, 82), tile38},
					{ new Color(34, 228, 35), tile39},
					{ new Color(141, 70, 154), tile40},
					{ new Color(241, 189, 154), tile41},
					{ new Color(162, 200, 29), tile42},
					{ new Color(221, 248, 191), tile43},
					{ new Color(111, 84, 119), tile44},
					{ new Color(59, 204, 230), tile45},
					{ new Color(45, 219, 216), tile46},
					{ new Color(36, 15, 82), tile47},
					{ new Color(152, 46, 55), tile48},
					{ new Color(204, 176, 56), tile49},
					{ new Color(116, 190, 3), tile50},
					{ new Color(65, 161, 87), tile51},
					{ new Color(247, 208, 198), tile52},
					{ new Color(40, 59, 104), tile53},
					{ new Color(191, 87, 27), tile54},
					{ new Color(19, 245, 139), tile55},
					{ new Color(73, 214, 183), tile56},
					{ new Color(108, 244, 9), tile57},
					{ new Color(74, 104, 54), tile58},
					{ new Color(72, 89, 143), tile59},
					{ new Color(98, 213, 24), tile60},
					{ new Color(229, 105, 57), tile61},
					{ new Color(188, 45, 179), tile62},
					{ new Color(31, 67, 251), tile63},
					{ new Color(32, 4, 159), tile64},
					{ new Color(112, 101, 184), tile65},
					{ new Color(54, 133, 56), tile66},
					{ new Color(172, 130, 217), tile67},
					{ new Color(128, 8, 201), tile68},
					{ new Color(249, 247, 56), tile69},
					{ new Color(33, 175, 119), tile70},
					{ new Color(54, 197, 101), tile71},
					{ new Color(79, 217, 238), tile72},
					{ new Color(226, 87, 199), tile73},
					{ new Color(216, 42, 147), tile74},
					{ new Color(188, 75, 240), tile75},
					{ new Color(106, 217, 3), tile76},
					{ new Color(126, 18, 211), tile77},
					{ new Color(86, 182, 82), tile78},
					{ new Color(62, 101, 96), tile79},
					{ new Color(112, 194, 54), tile80},
					{ new Color(122, 253, 147), tile81},
					{ new Color(131, 233, 62), tile82},
					{ new Color(58, 32, 139), tile83},
					{ new Color(201, 84, 45), tile84},
					{ new Color(113, 211, 88), tile85},
					{ new Color(69, 195, 188), tile86},
					{ new Color(217, 143, 29), tile87},
					{ new Color(52, 162, 157), tile88},
					{ new Color(163, 223, 14), tile89},
					{ new Color(19, 17, 116), tile90},
					{ new Color(141, 113, 149), tile91},
					{ new Color(144, 93, 44), tile92},
					{ new Color(255, 57, 98), tile93},
					{ new Color(177, 48, 185), tile94},
					{ new Color(120, 180, 189), tile95},
					{ new Color(166, 229, 227), tile96},
					{ new Color(250, 248, 162), tile97},
					{ new Color(164, 150, 50), tile98},
					{ new Color(25, 70, 91), tile99},
					{ new Color(246, 223, 9), tile100},
					{ new Color(47, 38, 15), tile101},
					{ new Color(22, 60, 226), tile102},
					{ new Color(151, 224, 117), tile103},
					{ new Color(43, 70, 137), tile104},
					{ new Color(90, 40, 95), tile105},
					{ new Color(99, 188, 238), tile106},
					{ new Color(223, 253, 250), tile107},
					{ new Color(43, 24, 24), tile108},
					{ new Color(210, 233, 219), tile109},
					{ new Color(99, 119, 23), tile110},
					{ new Color(209, 9, 90), tile111},
					{ new Color(88, 129, 9), tile112},
					{ new Color(170, 97, 120), tile113},
					{ new Color(219, 14, 4), tile114},
					{ new Color(109, 206, 178), tile115},
					{ new Color(24, 73, 110), tile116},
					{ new Color(210, 181, 137), tile117},
					{ new Color(108, 22, 225), tile118},
					{ new Color(15, 4, 14), tile119},
					{ new Color(247, 68, 82), tile120},
					{ new Color(6, 52, 105), tile121},
					{ new Color(94, 89, 60), tile122},
					{ new Color(47, 2, 166), tile123},
					{ new Color(86, 185, 90), tile124},
					{ new Color(118, 4, 238), tile125},
					{ new Color(245, 189, 73), tile126},
					{ new Color(101, 186, 160), tile127},
					{ new Color(109, 144, 193), tile128},
					{ new Color(141, 100, 243), tile129},
					{ new Color(120, 72, 124), tile130},
					{ new Color(250, 178, 29), tile131},
					{ new Color(37, 212, 218), tile132},
					{ new Color(155, 15, 116), tile133},
					{ new Color(117, 232, 71), tile134},
					{ new Color(199, 124, 252), tile135},
					{ new Color(47, 246, 17), tile136},
					{ new Color(243, 26, 70), tile137},
					{ new Color(196, 145, 137), tile138},
					{ new Color(178, 153, 164), tile139},
					{ new Color(168, 208, 245), tile140},
					{ new Color(73, 183, 185), tile141},
					{ new Color(41, 91, 6), tile142},
					{ new Color(60, 80, 48), tile143},
					{ new Color(20, 90, 174), tile144},
					{ new Color(212, 240, 209), tile145},
					{ new Color(88, 165, 19), tile146},
					{ new Color(196, 94, 110), tile147},
					{ new Color(225, 132, 46), tile148},
					{ new Color(54, 54, 33), tile149},
					{ new Color(147, 114, 58), tile150},
					{ new Color(53, 242, 63), tile151},
					{ new Color(127, 43, 48), tile152},
					{ new Color(141, 157, 32), tile153},
					{ new Color(245, 242, 165), tile154},
					{ new Color(225, 223, 192), tile155},
					{ new Color(152, 240, 160), tile156},
					{ new Color(184, 89, 243), tile157},
					{ new Color(144, 227, 113), tile158},
					{ new Color(134, 104, 50), tile159},
					{ new Color(138, 243, 37), tile160},
					{ new Color(228, 169, 222), tile161},
					{ new Color(245, 222, 103), tile162},
					{ new Color(111, 84, 196), tile163},
					{ new Color(160, 203, 8), tile164},
					{ new Color(243, 207, 108), tile165},
					{ new Color(200, 255, 165), tile166},
					{ new Color(110, 158, 69), tile167},
					{ new Color(129, 219, 24), tile168},
					{ new Color(71, 164, 15), tile169},
					{ new Color(205, 248, 195), tile170},
					{ new Color(253, 2, 170), tile171},
					{ new Color(251, 16, 72), tile172},
					{ new Color(199, 236, 0), tile173},
					{ new Color(89, 41, 155), tile174},
					{ new Color(219, 23, 142), tile175},
					{ new Color(235, 157, 20), tile176},
					{ new Color(5, 190, 104), tile177},
					{ new Color(141, 28, 85), tile178},
					{ new Color(223, 99, 205), tile179},
					{ new Color(197, 173, 57), tile180},
					{ new Color(87, 161, 91), tile181},
					{ new Color(1, 162, 200), tile182},
					{ new Color(94, 247, 190), tile183},
					{ new Color(35, 0, 19), tile184},
					{ new Color(164, 21, 116), tile185},
					{ new Color(170, 165, 196), tile186},
					{ new Color(138, 91, 7), tile187},
					{ new Color(251, 200, 58), tile188},
					{ new Color(90, 112, 230), tile189},
					{ new Color(84, 27, 172), tile190},
					{ new Color(123, 2, 62), tile191},
					{ new Color(198, 1, 135), tile192},
					{ new Color(63, 218, 116), tile193},
					{ new Color(198, 140, 165), tile194},
					{ new Color(85, 226, 189), tile195},
					{ new Color(85, 232, 6), tile196},
					{ new Color(224, 52, 190), tile197},
					{ new Color(9, 59, 81), tile198},
					{ new Color(50, 92, 217), tile199},
					{ new Color(33, 167, 50), tile200},
					{ new Color(225, 9, 220), tile201},
					{ new Color(17, 168, 254), tile202},
					{ new Color(212, 222, 20), tile203},
					{ new Color(237, 107, 202), tile204},
					{ new Color(79, 196, 207), tile205},
					{ new Color(97, 165, 230), tile206},
					{ new Color(124, 4, 135), tile207},
					{ new Color(224, 115, 230), tile208},
					{ new Color(238, 113, 198), tile209},
					{ new Color(237, 147, 165), tile210},
					{ new Color(174, 29, 50), tile211},
					{ new Color(66, 228, 131), tile212},
					{ new Color(201, 67, 57), tile213},
					{ new Color(190, 129, 10), tile214},
					{ new Color(242, 243, 201), tile215},
					{ new Color(243, 185, 119), tile216},
					{ new Color(130, 209, 182), tile217},
					{ new Color(243, 164, 163), tile218},
					{ new Color(170, 1, 149), tile219},
					{ new Color(245, 35, 54), tile220},
					{ new Color(55, 231, 74), tile221},
					{ new Color(110, 63, 77), tile222},
					{ new Color(152, 13, 223), tile223},
					{ new Color(75, 152, 97), tile224},
					{ new Color(172, 189, 130), tile225},
					{ new Color(125, 237, 128), tile226},
					{ new Color(29, 250, 183), tile227},
					{ new Color(79, 106, 194), tile228},
					{ new Color(238, 186, 121), tile229},
					{ new Color(143, 151, 227), tile230},
					{ new Color(237, 212, 32), tile231},
					{ new Color(3, 135, 154), tile232},
					{ new Color(191, 131, 180), tile233},
					{ new Color(123, 91, 172), tile234},
					{ new Color(151, 54, 56), tile235},
					{ new Color(84, 71, 230), tile236},
					{ new Color(32, 44, 19), tile237},
					{ new Color(21, 216, 41), tile238},
					{ new Color(126, 231, 124), tile239},
					{ new Color(135, 128, 132), tile240},
					{ new Color(212, 8, 117), tile241},
					{ new Color(252, 94, 196), tile242},
					{ new Color(65, 168, 54), tile243},
					{ new Color(232, 190, 106), tile244},
					{ new Color(204, 161, 158), tile245},
					{ new Color(11, 184, 51), tile246},
					{ new Color(137, 153, 115), tile247},
					{ new Color(146, 111, 107), tile248},
					{ new Color(207, 216, 251), tile249},
					{ new Color(247, 132, 159), tile250},
					{ new Color(29, 55, 3), tile251},
					{ new Color(47, 167, 83), tile252},
					{ new Color(54, 155, 216), tile253},
					{ new Color(116, 19, 158), tile254},
					{ new Color(175, 56, 110), tile255},
					{ new Color(169, 72, 54), tile256},
					{ new Color(138, 115, 47), tile257},
					{ new Color(73, 253, 230), tile258},
					{ new Color(17, 66, 152), tile259},
					{ new Color(10, 45, 134), tile260},
					{ new Color(200, 73, 35), tile261},
					{ new Color(151, 202, 134), tile262},
					{ new Color(102, 156, 249), tile263},
					{ new Color(75, 212, 28), tile264},
					{ new Color(90, 20, 133), tile265},
					{ new Color(212, 226, 55), tile266},
					{ new Color(252, 37, 143), tile267},
					{ new Color(197, 108, 17), tile268},
					{ new Color(111, 212, 58), tile269},
				};
			return new ColorTileMap(colorTileMap);
		}
	}
}
